// ── Module 06 — Database Administration (50) ─────────────────────────────────
QUESTIONS["06"] = [
  {
    q: "What is the difference between data administration and database administration?",
    options: [
      "They are the same thing with different names",
      "Data administration is organization-wide policy; database administration is technical work on one specific system",
      "Database administration only applies to NoSQL systems",
      "Data administration is a subset of the DBA's technical tasks",
    ],
    answer: 1,
    explain: "Data administration concerns organization-wide privacy/security policy across all systems. Database administration is the technical, system-specific work of keeping one particular database and its applications running correctly.",
  },
  {
    q: "Which role is primarily responsible for building and maintaining pipelines that move data between systems?",
    options: [
      "Data architect",
      "Database administrator (DBA)",
      "Data engineer",
      "End user",
    ],
    answer: 2,
    explain: "The data engineer builds and maintains ETL/ELT pipelines moving data between source systems and destinations like a data warehouse — distinct from the DBA (operational health of a running database) and the architect (long-term data model design).",
  },
  {
    q: "Two clerks read the same 'berths_available' value, both compute a decrement, and the second write overwrites the first with no error. What is this called?",
    options: [
      "Dirty read",
      "Lost update problem",
      "Phantom read",
      "Deadlock",
    ],
    answer: 1,
    explain: "The lost update problem occurs when two transactions read the same stale value and one transaction's write silently overwrites the other's, losing one of the updates entirely.",
  },
  {
    q: "What is the difference between a shared lock and an exclusive lock?",
    options: [
      "A shared lock allows other transactions to read but not write; an exclusive lock allows neither",
      "A shared lock allows writing only; an exclusive lock allows reading only",
      "They are identical in behavior",
      "A shared lock is only used in single-user systems",
    ],
    answer: 0,
    explain: "A shared lock permits other transactions to read the locked data but not change it. An exclusive lock blocks both reading and writing by any other transaction.",
  },
  {
    q: "What is the finest (most granular) level of locking commonly supported by modern DBMSs?",
    options: [
      "Table-level",
      "Database-level",
      "Row-level",
      "Column-level",
    ],
    answer: 2,
    explain: "Row-level locking locks only the specific rows being changed, maximizing concurrency for unrelated rows. PostgreSQL defaults to row-level locking for ordinary UPDATE/DELETE statements.",
  },
  {
    q: "Which concurrency control approach locks data before doing any work and holds the lock through the transaction?",
    options: [
      "Optimistic concurrency control",
      "Pessimistic concurrency control",
      "Deferred concurrency control",
      "Stateless concurrency control",
    ],
    answer: 1,
    explain: "Pessimistic concurrency control assumes conflicts will happen, so it locks data up front (e.g., via SELECT ... FOR UPDATE) and holds the lock until the transaction commits or rolls back.",
  },
  {
    q: "Optimistic concurrency control typically detects a conflict by...",
    options: [
      "Locking every table in the database",
      "Comparing a version number or timestamp at write time against what was originally read",
      "Never checking for conflicts at all",
      "Requiring a DBA to manually approve each write",
    ],
    answer: 1,
    explain: "Optimistic control reads data without locking, then at write time checks whether a version/timestamp column still matches what was originally read; if not, the transaction retries with fresh data.",
  },
  {
    q: "What does the SQL clause SELECT ... FOR UPDATE do?",
    options: [
      "Marks rows for deletion",
      "Takes an exclusive row lock on the selected rows immediately, blocking other transactions from locking them until commit or rollback",
      "Creates a backup of the selected rows",
      "Runs the query without any transaction context",
    ],
    answer: 1,
    explain: "SELECT ... FOR UPDATE is a pessimistic locking mechanism: it immediately takes an exclusive lock on the returned rows so no other transaction can lock or update them until the current transaction finishes.",
  },
  {
    q: "What is two-phase locking (2PL)?",
    options: [
      "A technique where a transaction only acquires locks in a growing phase, then only releases them in a shrinking phase, guaranteeing serializability",
      "A method for encrypting locked rows twice",
      "A backup strategy involving two copies of the database",
      "A way to avoid using any locks at all",
    ],
    answer: 0,
    explain: "2PL splits a transaction's lock activity into a growing phase (only acquiring new locks) followed by a shrinking phase (only releasing locks), which is sufficient to guarantee serializable schedules.",
  },
  {
    q: "Transaction A holds a lock on row X and waits for row Y; Transaction B holds a lock on row Y and waits for row X. What is this called?",
    options: [
      "A phantom read",
      "A deadlock (deadly embrace)",
      "A non-repeatable read",
      "A rollforward",
    ],
    answer: 1,
    explain: "This circular wait, where neither transaction can proceed because each needs a resource the other holds, is a deadlock, also called the deadly embrace.",
  },
  {
    q: "How does PostgreSQL typically resolve a detected deadlock?",
    options: [
      "It halts the entire server until manually restarted",
      "It automatically picks one transaction as a victim, aborts it with an error, and lets the other proceed",
      "It silently merges both transactions into one",
      "It ignores the deadlock and continues both transactions",
    ],
    answer: 1,
    explain: "PostgreSQL's deadlock detector identifies the circular wait, aborts one transaction (the victim) with a 'deadlock detected' error, and the application is expected to catch this and retry.",
  },
  {
    q: "What SQL statements make up the transaction control language (TCL) covered in this module?",
    options: [
      "SELECT, INSERT, UPDATE",
      "BEGIN, COMMIT, ROLLBACK",
      "CREATE, ALTER, DROP",
      "GRANT, REVOKE, DENY",
    ],
    answer: 1,
    explain: "BEGIN (or START TRANSACTION) marks the start of a transaction, COMMIT makes its changes permanent, and ROLLBACK undoes everything since BEGIN — the core transaction control statements.",
  },
  {
    q: "What does the 'Atomic' property of an ACID transaction guarantee?",
    options: [
      "All the transaction's steps happen, or none of them do",
      "The transaction runs faster than non-atomic ones",
      "Only one user can access the database at a time",
      "Data is automatically backed up after every transaction",
    ],
    answer: 0,
    explain: "Atomicity means a transaction's series of steps are all-or-nothing — if any step fails, every prior step in that transaction is undone, leaving no partial changes.",
  },
  {
    q: "What does the 'Durable' property of an ACID transaction guarantee?",
    options: [
      "The transaction can be paused and resumed later",
      "Once committed, the transaction's changes survive even a crash immediately afterward",
      "The transaction uses the least possible disk space",
      "The transaction can never be rolled back",
    ],
    answer: 1,
    explain: "Durability guarantees that once a COMMIT succeeds, the changes are permanent, surviving crashes or power loss — implemented in PostgreSQL via write-ahead logging (WAL).",
  },
  {
    q: "Which mechanism does PostgreSQL use to guarantee durability of committed transactions?",
    options: [
      "Write-ahead logging (WAL)",
      "In-memory caching only",
      "Manual nightly snapshots",
      "Replicating to a second server is the only method",
    ],
    answer: 0,
    explain: "PostgreSQL writes every change to the write-ahead log (WAL) before it is applied to the actual data files and before COMMIT is acknowledged, so committed changes can be replayed and recovered after a crash.",
  },
  {
    q: "What is a dirty read?",
    options: [
      "Reading a row that has since been deleted",
      "Reading another transaction's uncommitted change, which might later be rolled back",
      "Reading the same row twice and getting different values both times",
      "A read that returns no rows at all",
    ],
    answer: 1,
    explain: "A dirty read occurs when a transaction reads data written by another transaction that has not yet committed — if that other transaction rolls back, the reader acted on data that never really existed.",
  },
  {
    q: "What is a non-repeatable read?",
    options: [
      "Reading uncommitted data from another transaction",
      "Re-reading the same row twice within one transaction and getting a different value because another transaction committed a change in between",
      "A query that returns rows in random order",
      "Re-running the same filtered query and getting a different set of matching rows",
    ],
    answer: 1,
    explain: "A non-repeatable read happens when a transaction reads a specific row, another transaction commits a change to that same row, and the first transaction re-reads it and sees the new value — inconsistent within its own transaction.",
  },
  {
    q: "What is a phantom read?",
    options: [
      "Reading a row that was never actually inserted",
      "Re-running the same filtered query twice within a transaction and getting a different set of matching rows because rows were inserted/deleted in between",
      "A read operation that never completes",
      "Reading a column that does not exist",
    ],
    answer: 1,
    explain: "A phantom read occurs when a transaction re-executes the same filtering query and finds new rows (or missing rows) because another transaction inserted or deleted matching rows in the interim.",
  },
  {
    q: "Which SQL standard isolation level prevents dirty reads but still allows non-repeatable reads and phantom reads?",
    options: [
      "READ UNCOMMITTED",
      "READ COMMITTED",
      "REPEATABLE READ",
      "SERIALIZABLE",
    ],
    answer: 1,
    explain: "READ COMMITTED guarantees a transaction never sees another transaction's uncommitted data (no dirty reads), but does not protect against non-repeatable reads or phantom reads.",
  },
  {
    q: "Which SQL standard isolation level prevents both dirty reads and non-repeatable reads, but still allows phantom reads?",
    options: [
      "READ UNCOMMITTED",
      "READ COMMITTED",
      "REPEATABLE READ",
      "SERIALIZABLE",
    ],
    answer: 2,
    explain: "REPEATABLE READ ensures that if a transaction reads the same row twice, it sees the same value both times, but new rows matching a filter can still appear (phantom reads) unless SERIALIZABLE is used.",
  },
  {
    q: "Which isolation level prevents dirty reads, non-repeatable reads, and phantom reads all at once?",
    options: [
      "READ UNCOMMITTED",
      "READ COMMITTED",
      "REPEATABLE READ",
      "SERIALIZABLE",
    ],
    answer: 3,
    explain: "SERIALIZABLE is the strictest isolation level, guaranteeing the result is equivalent to running all transactions one at a time in some order, preventing all three classic anomalies.",
  },
  {
    q: "What isolation level does MySQL/InnoDB default to, in contrast to PostgreSQL and Oracle?",
    options: [
      "READ UNCOMMITTED",
      "READ COMMITTED",
      "REPEATABLE READ",
      "SERIALIZABLE",
    ],
    answer: 2,
    explain: "MySQL/InnoDB defaults to REPEATABLE READ, while PostgreSQL and Oracle default to READ COMMITTED — a common surprise for developers moving code between the two without adjusting isolation-level assumptions.",
  },
  {
    q: "Why doesn't PostgreSQL truly implement READ UNCOMMITTED as a distinct behavior?",
    options: [
      "PostgreSQL rejects the syntax entirely",
      "Its MVCC (multiversion concurrency control) storage engine never lets one transaction see another's uncommitted rows, so it silently behaves like READ COMMITTED",
      "READ UNCOMMITTED is only valid in MySQL",
      "PostgreSQL requires a special extension to support any isolation levels",
    ],
    answer: 1,
    explain: "PostgreSQL accepts the READ UNCOMMITTED syntax for standards compliance but treats it identically to READ COMMITTED, because its MVCC architecture inherently prevents dirty reads regardless of the requested level.",
  },
  {
    q: "What is the difference between authentication and authorization?",
    options: [
      "They are synonyms",
      "Authentication proves who you are; authorization determines what you're allowed to do",
      "Authentication only applies to database administrators",
      "Authorization happens before authentication in every system",
    ],
    answer: 1,
    explain: "Authentication verifies identity (username/password, certificate, etc.). Authorization then determines what actions that authenticated identity is permitted to perform.",
  },
  {
    q: "What SQL statement is used to grant a user or role a database privilege?",
    options: [
      "ALLOW",
      "GRANT",
      "PERMIT",
      "ENABLE",
    ],
    answer: 1,
    explain: "GRANT is the standard SQL statement for assigning privileges (SELECT, INSERT, UPDATE, DELETE, etc.) to a user or role, with REVOKE used to take privileges back.",
  },
  {
    q: "What is the principle of least privilege?",
    options: [
      "Every user should have full administrative access by default for convenience",
      "Each user or role should be granted only the access strictly necessary for its job, and nothing more",
      "Privileges should never be granted to roles, only to individuals",
      "All privileges should be revoked at the end of every session",
    ],
    answer: 1,
    explain: "Least privilege means limiting each account's access to exactly what it needs — e.g., an application's database login should not have DROP TABLE rights, limiting the blast radius of a compromised connection.",
  },
  {
    q: "Why is it best practice to grant permissions to roles rather than directly to individual users?",
    options: [
      "Individual grants are technically impossible in SQL",
      "Roles group related permissions so that changing a person's job only requires changing role membership, not re-auditing individual grants",
      "Roles are always faster to execute at query time",
      "Individual user accounts cannot log in if given any GRANT",
    ],
    answer: 1,
    explain: "Granting to roles (e.g., booking_clerk, reporting_readonly) centralizes permission management — when someone changes jobs, you change their role membership rather than tracking down every individual grant they were given.",
  },
  {
    q: "What is a key syntax difference between PostgreSQL and MySQL regarding user/role management?",
    options: [
      "MySQL does not support GRANT at all",
      "PostgreSQL uses CREATE ROLE (a role with LOGIN acts as a user); MySQL uses CREATE USER, and privileges are tied to a user plus the host they connect from",
      "PostgreSQL requires a GUI tool to create users",
      "There is no difference; the syntax is identical",
    ],
    answer: 1,
    explain: "PostgreSQL unifies users and roles (CREATE ROLE ... WITH LOGIN). MySQL uses CREATE USER and grants are commonly scoped as user@host, tying privileges to both the account and the connecting host.",
  },
  {
    q: "What are the three backup strategies discussed, ordered from capturing the most data per backup to the least?",
    options: [
      "Incremental, differential, full",
      "Full, differential, incremental",
      "Differential, full, incremental",
      "Full, incremental, differential",
    ],
    answer: 1,
    explain: "A full backup captures everything. A differential backup captures changes since the last full backup (a growing subset). An incremental backup captures changes only since the last backup of any kind (the smallest subset).",
  },
  {
    q: "What does point-in-time recovery (PITR) allow that a simple full backup restore does not?",
    options: [
      "Restoring the database to any specific timestamp, not just the moment of the last backup",
      "Restoring only table structures without any data",
      "Skipping the need for any backup at all",
      "Restoring data from a different DBMS product entirely",
    ],
    answer: 0,
    explain: "PITR restores the last full backup and then replays the transaction log (WAL in PostgreSQL) up to any specific point in time — e.g., one minute before an accidental mass delete — rather than only to the last backup's moment.",
  },
  {
    q: "In PostgreSQL, what is the role of the write-ahead log (WAL) in point-in-time recovery?",
    options: [
      "It has no role in recovery, only in query optimization",
      "Archived WAL segments, replayed after restoring a base backup, let the database be brought forward to any specific moment in time",
      "WAL only records SELECT statements",
      "WAL is deleted immediately after each COMMIT",
    ],
    answer: 1,
    explain: "Because every committed change is durably recorded in the WAL before being applied to data files, archived WAL segments can be replayed on top of a base backup to reconstruct the database state at any specific timestamp.",
  },
  {
    q: "What is the difference between a before-image and an after-image in a transaction log?",
    options: [
      "A before-image is a screenshot of the database UI; an after-image is not used in recovery",
      "A before-image is a row's value before a change (used for rollback); an after-image is its value after the change (used for rollforward)",
      "They are two names for the same log record",
      "Before-images are only used in NoSQL systems",
    ],
    answer: 1,
    explain: "Before-images let the DBMS undo a transaction by restoring prior values (rollback). After-images let it redo a transaction by reapplying the new values (rollforward), typically used to catch a restored backup up to the present.",
  },
  {
    q: "What is the main downside of recovery via reprocessing (redoing all activity since the last backup from original input records)?",
    options: [
      "It requires no transaction log at all",
      "It can take as long as the original processing took, and a heavily loaded system may never catch up",
      "It only works for read-only databases",
      "It is faster than rollback/rollforward in every case",
    ],
    answer: 1,
    explain: "Reprocessing redoes every transaction from original inputs, taking roughly the same amount of time as it did originally — for a busy system, that reprocessing time may exceed the time available before it's needed, so it never catches up.",
  },
  {
    q: "Why should a DBA periodically test restoring a backup rather than just confirming the backup job 'succeeded'?",
    options: [
      "Testing restores is purely optional and rarely useful",
      "A backup that has never been restored is an untested assumption — corruption or incompleteness may not be discovered until a real incident",
      "Backup files never need to be tested if stored on redundant disks",
      "Restoring backups voids most database licenses",
    ],
    answer: 1,
    explain: "A successful backup job doesn't guarantee a successful restore. Periodically restoring to a scratch environment verifies the backup actually works, rather than discovering a corrupt or incomplete backup during a real outage.",
  },
  {
    q: "Which of the following is a DBA responsibility distinct from a data architect's typical focus?",
    options: [
      "Designing the long-term canonical data model across the whole organization",
      "Day-to-day performance tuning, security administration, and backup/recovery of a specific running database",
      "Deciding which entities should exist company-wide",
      "Defining master data standards across departments",
    ],
    answer: 1,
    explain: "The DBA's focus is operational and system-specific: keeping a particular running database healthy (performance, security, backups). The data architect instead focuses on the long-term, organization-wide canonical data model.",
  },
  {
    q: "Which of these tasks falls under 'data administration' rather than 'database administration'?",
    options: [
      "Tuning a slow query on the production PostgreSQL server",
      "Setting organization-wide policy on who may access customer PII across every system, independent of any one database",
      "Running EXPLAIN ANALYZE on a report",
      "Restoring last night's backup after a failed migration",
    ],
    answer: 1,
    explain: "Data administration is the organization-wide policy layer (privacy rules, data quality standards) that applies across all systems, distinct from database administration's technical, system-specific work like tuning or restoring one particular database.",
  },
  {
    q: "A DBA is described as being judged less by 'features shipped' and more by what?",
    options: [
      "The number of new tables created per quarter",
      "Things that don't happen — no data loss, no multi-hour outage, no silent corruption, no breach",
      "How many GRANT statements were issued",
      "The size of the database in gigabytes",
    ],
    answer: 1,
    explain: "The notes frame DBA success as largely invisible: the job is done well when nothing goes wrong — no outages, no corruption, no breaches — rather than by visible new features.",
  },
  {
    q: "Which of the following is explicitly listed as something cloud-managed databases (RDS, Cloud SQL, Azure SQL) do NOT eliminate the need for?",
    options: [
      "Applying OS security patches",
      "Designing the schema well, choosing the right indexes, reviewing slow queries, and deciding who gets access to what",
      "Taking automated backups",
      "Handling server failover",
    ],
    answer: 1,
    explain: "Cloud-managed databases automate patching, backups, and failover, but someone still has to do the schema design, indexing, query review, and access-control decisions — the notes are explicit that the DBA role isn't eliminated by managed services.",
  },
  {
    q: "Two transactions each read berths_available = 1 for the same boat before either commits, and the second UPDATE silently overwrites the first. Besides 'lost update,' what related failure mode involves reading another transaction's uncommitted, in-progress change?",
    options: [
      "A phantom read",
      "A dirty (inconsistent) read",
      "A checkpoint failure",
      "A two-phase commit",
    ],
    answer: 1,
    explain: "A dirty read is a related but distinct problem: reading data another transaction has changed but not yet committed. If that writer later rolls back, the reader acted on data that never actually existed in the committed database.",
  },
  {
    q: "Which locking granularity offers the highest concurrency but the most overhead from tracking many small locks?",
    options: [
      "Table-level locking",
      "Page-level locking",
      "Row-level locking",
      "Database-level locking",
    ],
    answer: 2,
    explain: "Row-level locking locks only the specific rows being changed, maximizing concurrency for unrelated rows, at the cost of more bookkeeping overhead compared to coarser table- or page-level locks.",
  },
  {
    q: "What is the simplest application-level defense against deadlocks suggested in the concurrency notes?",
    options: [
      "Never use transactions at all",
      "Always acquire locks on multiple rows in the same order across every transaction, e.g., always lock the lowest primary key first",
      "Always use SERIALIZABLE isolation for every transaction",
      "Disable the DBMS's automatic deadlock detector",
    ],
    answer: 1,
    explain: "If every transaction agrees on a consistent lock acquisition order (such as always locking the lowest primary key value first), circular waits — the root cause of deadlocks — become impossible.",
  },
  {
    q: "A transaction runs BEGIN; SELECT ... FOR UPDATE; UPDATE ...; COMMIT;. A second transaction tries to SELECT ... FOR UPDATE the exact same row before the first commits. What happens?",
    options: [
      "The second transaction reads the pre-update value immediately and proceeds",
      "The second transaction waits until the first transaction commits or rolls back before it can acquire the lock",
      "PostgreSQL raises a syntax error",
      "Both transactions proceed simultaneously with no blocking",
    ],
    answer: 1,
    explain: "SELECT ... FOR UPDATE takes an exclusive row lock immediately. A second transaction requesting the same lock must wait until the first transaction finishes (commit or rollback), which is exactly how pessimistic concurrency control prevents acting on stale data.",
  },
  {
    q: "Under optimistic concurrency control using a row_version column, what does an UPDATE ... WHERE row_version = 7 affecting zero rows tell the application?",
    options: [
      "The row was permanently deleted and can never be recovered",
      "Someone else already updated the row since it was read, so the application should reload and retry with fresh data",
      "The database connection has failed",
      "The WHERE clause contains a syntax error",
    ],
    answer: 1,
    explain: "Zero affected rows means the row_version no longer matches what was read — another transaction won the race and updated it first. The application detects this conflict and retries with a fresh read rather than silently losing the update.",
  },
  {
    q: "Which situation is the best candidate for optimistic rather than pessimistic concurrency control?",
    options: [
      "A high-contention hot row updated by dozens of transactions per second",
      "A form where most users read a record, think for a while, and rarely collide with another editor of the same record",
      "A financial transfer that must never lose an update under any circumstance",
      "A single-user embedded database with no concurrent access at all",
    ],
    answer: 1,
    explain: "Optimistic concurrency control is best when conflicts are rare — like a record most users read and occasionally edit without colliding — since it avoids the cost of locking on every read and only pays a retry cost on the occasional actual conflict.",
  },
  {
    q: "In two-phase locking (2PL), once a transaction releases its first lock, what is it no longer allowed to do?",
    options: [
      "Release any further locks",
      "Acquire any new locks — it has entered the shrinking phase",
      "Commit the transaction",
      "Read any data at all",
    ],
    answer: 1,
    explain: "2PL splits lock activity into a growing phase (only acquiring locks) followed by a shrinking phase (only releasing locks). Once the first release happens, the transaction has entered the shrinking phase and may not acquire any new locks.",
  },
  {
    q: "A transaction reads a customer's store_credit, then INSERTs a new charter row referencing that customer within the same BEGIN/COMMIT block. If the INSERT fails a CHECK constraint, what should happen to the earlier store_credit UPDATE?",
    options: [
      "It should remain applied since it already succeeded",
      "It should be rolled back along with the failed INSERT, since the whole transaction is one atomic unit",
      "It should be applied to a different customer instead",
      "PostgreSQL automatically converts it into a separate committed transaction",
    ],
    answer: 1,
    explain: "Atomicity requires that all of a transaction's steps succeed together or none do. If the INSERT fails, ROLLBACK must undo the earlier UPDATE too, or the customer's credit would vanish with nothing to show for it.",
  },
  {
    q: "Which ACID property is specifically responsible for rejecting a transaction step that would violate a CHECK constraint like store_credit >= 0?",
    options: [
      "Atomicity",
      "Consistency",
      "Isolation",
      "Durability",
    ],
    answer: 1,
    explain: "Consistency guarantees a transaction only takes the database from one valid state to another, respecting every constraint. A step that would push store_credit negative violates that constraint and is rejected to preserve consistency.",
  },
  {
    q: "A report transaction reads a balance, performs some calculations, and reads the same balance again a moment later expecting it to be unchanged, protecting against another transaction committing a change in between. Which isolation level is the minimum needed to guarantee that?",
    options: [
      "READ UNCOMMITTED",
      "READ COMMITTED",
      "REPEATABLE READ",
      "None; no isolation level can guarantee this",
    ],
    answer: 2,
    explain: "REPEATABLE READ guarantees that if a transaction reads the same row twice, it sees the same value both times, preventing the non-repeatable read this report scenario depends on. READ COMMITTED alone would not prevent it.",
  },
  {
    q: "Why does the module recommend reserving SERIALIZABLE isolation for a small number of transactions, such as financial transfers, rather than using it everywhere by default?",
    options: [
      "SERIALIZABLE is deprecated and will be removed from the SQL standard",
      "SERIALIZABLE guarantees the most safety but trades throughput for it, and may cause PostgreSQL to abort and require a retry when it detects a conflict",
      "SERIALIZABLE cannot be combined with COMMIT or ROLLBACK",
      "SERIALIZABLE is only available in MySQL, not PostgreSQL",
    ],
    answer: 1,
    explain: "Higher isolation isn't free — SERIALIZABLE blocks more and may cause PostgreSQL to abort a transaction on conflict detection, asking the application to retry. It's reserved for cases where correctness can't tolerate any anomaly, not used blanket-wide for performance reasons.",
  },
  {
    q: "A DBA wants to grant a reporting tool read-only access to every table in a schema without listing each table individually. Which statement accomplishes this in PostgreSQL?",
    options: [
      "GRANT SELECT ON ALL TABLES IN SCHEMA public TO reporting_readonly;",
      "GRANT ALL PRIVILEGES ON DATABASE mydb TO reporting_readonly;",
      "CREATE USER reporting_readonly WITH SUPERUSER;",
      "REVOKE ALL ON SCHEMA public FROM reporting_readonly;",
    ],
    answer: 0,
    explain: "GRANT SELECT ON ALL TABLES IN SCHEMA public grants read-only access across every current table in that schema to the role in one statement, matching the least-privilege goal of a reporting-only account.",
  },
];
