// ── Module 04 — Data Modeling & E-R Diagrams (100) ───────────────────────────
QUESTIONS["04"] = [
  {
    q: "What is the difference between 'data' and 'information' as used in data modeling?",
    options: [
      "They are synonyms with no meaningful difference",
      "Data is recorded facts and numbers; information is data given meaning through context or processing",
      "Data only exists in spreadsheets; information only exists in databases",
      "Information always precedes data chronologically",
    ],
    answer: 1,
    explain: "Data is a raw recorded fact (a number, a name, a date). Information is data that has been processed or presented in a meaningful context — summarized, compared, grouped.",
  },
  {
    q: "What are the five stages of the Systems Development Life Cycle (SDLC), in order?",
    options: [
      "Design, Analysis, Definition, Maintenance, Implementation",
      "System definition, Requirements analysis, Component design, Implementation, System maintenance",
      "Planning, Coding, Testing, Deployment, Retirement",
      "Analysis, Design, Coding, Debugging, Documentation",
    ],
    answer: 1,
    explain: "The classic SDLC sequence is: system definition (project plan) → requirements analysis (approved requirements) → component design (system design) → implementation (working system) → maintenance (updates, feeding the next cycle).",
  },
  {
    q: "What is the deliverable of the 'requirements analysis' step of the SDLC?",
    options: [
      "A working, installed system",
      "A set of approved user requirements",
      "The project plan",
      "A maintenance schedule",
    ],
    answer: 1,
    explain: "Requirements analysis takes the project plan as input and produces approved user requirements as its output, gathered via interviews, existing-system review, and identifying needed reports/queries.",
  },
  {
    q: "What are the three main stages of the (narrower) database development process nested inside the SDLC?",
    options: [
      "Coding, Testing, Deployment",
      "Planning, Analysis, Design, Implementation (four stages, with planning as an initial scoping step)",
      "Requirements analysis, Component design, Implementation",
      "Normalization, Denormalization, Indexing",
    ],
    answer: 2,
    explain: "The database development process is commonly described as Requirements analysis (producing the conceptual E-R model), Component design (producing the relational schema), and Implementation (building the actual database).",
  },
  {
    q: "During which phase of database development is the E-R diagram (conceptual data model) typically created?",
    options: ["Implementation", "Analysis", "Maintenance", "Component design only, never analysis"],
    answer: 1,
    explain: "The analysis phase determines specific data requirements and produces the conceptual data model — the E-R diagram — along with documented business rules.",
  },
  {
    q: "What is a business rule?",
    options: [
      "A SQL statement that creates a table",
      "A statement that defines or constrains some aspect of how an organization operates",
      "A rule that only applies to relational databases, never NoSQL",
      "A rule enforced exclusively by the DBMS query optimizer",
    ],
    answer: 1,
    explain: "A business rule is a policy statement — e.g., 'no advisor may have more than 25 advisees' — that shapes what the data model must allow or forbid.",
  },
  {
    q: "Why must business rules be gathered before drawing an E-R diagram, rather than after?",
    options: [
      "Because SQL syntax requires it",
      "Because cardinality and even entity/relationship structure are determined by business rules, not guessed from the data alone",
      "Business rules are actually optional for a correct diagram",
      "Only DBAs are allowed to define business rules",
    ],
    answer: 1,
    explain: "Cardinalities, minimum participation, and even whether two things should be separate entities all trace back to specific business rules. Modeling without them is guessing.",
  },
  {
    q: "In E-R modeling, what is an 'entity'?",
    options: [
      "A single row of data only",
      "Something the business wants to track — a person, place, object, event, or concept",
      "A SQL constraint",
      "Only a table that has a foreign key",
    ],
    answer: 1,
    explain: "An entity is a class of things the organization tracks — EMPLOYEE, DEPARTMENT, PROJECT. An entity instance is one specific occurrence, like employee #14.",
  },
  {
    q: "How should entity class names be written on an E-R diagram, per convention?",
    options: [
      "lowercase and plural, e.g. 'employees'",
      "UPPERCASE and singular, e.g. 'EMPLOYEE'",
      "camelCase, e.g. 'employeeRecord'",
      "Always prefixed with 'tbl_'",
    ],
    answer: 1,
    explain: "Convention writes entity classes in uppercase and singular — EMPLOYEE (the class), not employees or Employee.",
  },
  {
    q: "What is an 'identifier' in E-R terms?",
    options: [
      "Any attribute at all",
      "An attribute (or set of attributes) that uniquely names/identifies entity instances",
      "A relationship between two entities",
      "A foreign key shown on a conceptual diagram",
    ],
    answer: 1,
    explain: "An identifier uniquely distinguishes one entity instance from another — e.g., EmployeeNumber identifies a specific EMPLOYEE instance.",
  },
  {
    q: "Who created the entity-relationship model, and when?",
    options: ["James Martin, 1990", "Peter Chen, 1976", "Edgar Codd, 1970", "IBM, 1985"],
    answer: 1,
    explain: "Peter Chen introduced the entity-relationship model in 1976; it remains the standard conceptual modeling approach, later extended and adapted (e.g., into Crow's Foot notation).",
  },
  {
    q: "What notation style uses 'crow's feet' to depict the many side of a relationship, and is common in tools like draw.io?",
    options: ["Chen notation", "Crow's Foot (Information Engineering) notation", "UML class diagrams only", "IDEF0"],
    answer: 1,
    explain: "Crow's Foot notation (from James Martin's Information Engineering) draws cardinality symbols directly on the relationship line — bars, circles, and the three-pronged crow's foot.",
  },
  {
    q: "In Crow's Foot notation, what does a single straight bar closest to an entity mean?",
    options: ["Zero", "Exactly one (mandatory, maximum = 1)", "Many", "Zero or many"],
    answer: 1,
    explain: "A single bar represents 'exactly one' — both minimum and maximum cardinality of 1 on that end of the relationship.",
  },
  {
    q: "In Crow's Foot notation, what does a circle closest to an entity represent?",
    options: [
      "Maximum cardinality of many",
      "Minimum cardinality of zero (this entity's participation is optional)",
      "The entity is weak",
      "A ternary relationship",
    ],
    answer: 1,
    explain: "A circle denotes an optional minimum cardinality of zero — the entity instance doesn't have to participate in the relationship at all.",
  },
  {
    q: "What does the combination 'circle + crow's foot' (○<) mean at one end of a relationship line?",
    options: [
      "Exactly one, mandatory",
      "Zero or many",
      "Exactly two",
      "One or many",
    ],
    answer: 1,
    explain: "Circle = minimum zero (optional), crow's foot = maximum many. Together: zero or many — the most permissive combination.",
  },
  {
    q: "What does 'bar + crow's foot' (|<) mean at one end of a relationship line?",
    options: ["Zero or one", "Exactly zero", "One or many (at least one required, more allowed)", "Zero or many"],
    answer: 2,
    explain: "Bar = minimum one (mandatory), crow's foot = maximum many. Together: one or many — at least one instance is required, and more are permitted.",
  },
  {
    q: "Why do conceptual E-R diagrams typically NOT show foreign keys inside entity boxes?",
    options: [
      "Foreign keys don't exist until you draw a physical diagram — the conceptual diagram models business meaning, and the relationship line itself represents the connection",
      "Foreign keys are only used in NoSQL databases",
      "It's a formatting limit in most diagramming tools",
      "Conceptual diagrams never show any attributes at all",
    ],
    answer: 0,
    explain: "Foreign keys are a physical/relational implementation detail added later when converting the E-R model into table designs; the conceptual diagram's relationship line already conveys that connection.",
  },
  {
    q: "What is the maximum cardinality of a One-to-One (1:1) relationship?",
    options: [
      "A single instance of each entity relates to at most a single instance of the other",
      "A single instance of one entity relates to many of the other, and vice versa",
      "Many instances of each entity relate to many of the other",
      "1:1 relationships have no maximum cardinality by definition",
    ],
    answer: 0,
    explain: "In a 1:1 relationship, one instance of Entity A pairs with at most one instance of Entity B, and vice versa — e.g., an employee assigned exactly one parking spot.",
  },
  {
    q: "When you discover a strict 1:1 relationship in a data model, what question is it often worth asking?",
    options: [
      "Whether the relationship should instead be N:M",
      "Whether the two entities should simply be merged into a single table",
      "Whether an associative entity is required",
      "Whether the relationship should become unary",
    ],
    answer: 1,
    explain: "1:1 relationships are the rarest cardinality shape; a strict one-to-one pairing often means the 'second' entity is really just optional attributes that belong on the first entity's table.",
  },
  {
    q: "'A DEPARTMENT employs many EMPLOYEEs; each EMPLOYEE works in exactly one DEPARTMENT.' What relationship type is this?",
    options: ["One-to-One (1:1)", "One-to-Many (1:N)", "Many-to-Many (N:M)", "Ternary"],
    answer: 1,
    explain: "One department relates to many employees, but each employee relates to only one department — the classic 1:N shape, the most common in real schemas.",
  },
  {
    q: "'A STUDENT enrolls in many COURSEs; each COURSE has many STUDENTs enrolled.' What relationship type is this?",
    options: ["One-to-One (1:1)", "One-to-Many (1:N)", "Many-to-Many (N:M)", "Unary"],
    answer: 2,
    explain: "Both sides allow many — many students per course, many courses per student — making this a Many-to-Many (N:M) relationship.",
  },
  {
    q: "Why can't a pure N:M relationship line directly hold an attribute like 'EnrollmentDate'?",
    options: [
      "N:M relationships never have any attributes by SQL rule",
      "EnrollmentDate describes the specific pairing (this student, this course), not either entity alone, and a bare relationship line can't store per-pairing facts durably as a table would",
      "Dates can never be attributes in E-R diagrams",
      "It actually can, with no special construct needed",
    ],
    answer: 1,
    explain: "An attribute belonging to a relationship rather than either entity is the signal to convert that relationship into an associative entity, which can hold pairing-specific attributes as its own columns.",
  },
  {
    q: "What is an associative (intersection/linking) entity used for?",
    options: [
      "Storing metadata about the database schema itself",
      "Resolving an N:M relationship into two 1:N relationships, and holding attributes specific to the pairing",
      "Replacing the need for foreign keys entirely",
      "Only used for unary relationships",
    ],
    answer: 1,
    explain: "An associative entity sits between the two original entities, links to both via foreign keys, and holds attributes that belong to the relationship itself — e.g., ASSIGNMENT holding HoursWorked for each EMPLOYEE-PROJECT pairing.",
  },
  {
    q: "In the Wedgewood Pacific schema, what role does the ASSIGNMENT table play?",
    options: [
      "It's a weak entity with no relationship to EMPLOYEE or PROJECT",
      "It's the associative entity resolving the EMPLOYEE-PROJECT many-to-many relationship, holding HoursWorked",
      "It's a lookup table for department names",
      "It replaces the need for a PROJECT table",
    ],
    answer: 1,
    explain: "ASSIGNMENT links EMPLOYEE and PROJECT with a composite key (ProjectID, EmployeeNumber) and stores HoursWorked — a fact specific to that employee/project pairing.",
  },
  {
    q: "What is a weak entity?",
    options: [
      "Any entity with fewer than three attributes",
      "An entity that cannot exist in the database without the existence of another (parent) entity",
      "An entity that has no relationships at all",
      "An entity used only in ternary relationships",
    ],
    answer: 1,
    explain: "A weak entity's existence depends on a parent entity — e.g., a DEPENDENT record only makes sense in relation to the EMPLOYEE it belongs to.",
  },
  {
    q: "What distinguishes an 'ID-dependent' weak entity from a 'non-ID-dependent' weak entity?",
    options: [
      "ID-dependent entities have no identifier of their own and use a composite key including the parent's identifier; non-ID-dependent entities have their own identifier but still depend on the parent for existence",
      "There is no real difference between the two",
      "Non-ID-dependent entities never have foreign keys",
      "ID-dependent entities are always strong entities",
    ],
    answer: 0,
    explain: "ID-dependent weak entities (e.g., DEPENDENT identified by EmployeeID+DependentID) borrow part of their identity from the parent. Non-ID-dependent weak entities (e.g., a VEHICLE with its own VIN) have their own identifier but still can't exist without the parent.",
  },
  {
    q: "What line style represents an identifying relationship between a strong entity and an ID-dependent weak entity?",
    options: ["Dashed line", "Solid line", "Dotted line with an arrow", "No line is drawn"],
    answer: 1,
    explain: "Identifying relationships (to ID-dependent weak entities) are drawn with a solid line; non-identifying relationships (to non-ID-dependent weak entities, or between two strong entities) use a dashed line.",
  },
  {
    q: "What does 'degree' mean in the context of an E-R relationship?",
    options: [
      "The maximum cardinality of the relationship",
      "The number of distinct entity types participating in the relationship",
      "The number of attributes on the relationship",
      "Whether the relationship is mandatory or optional",
    ],
    answer: 1,
    explain: "Degree counts how many entity types are involved: one (unary), two (binary), or three (ternary) — a separate property from cardinality.",
  },
  {
    q: "'An EMPLOYEE supervises other EMPLOYEEs.' What is the degree of this relationship, and what is it also called?",
    options: [
      "Degree 2 (binary)",
      "Degree 1 (unary), also called a recursive relationship",
      "Degree 3 (ternary)",
      "Degree 0",
    ],
    answer: 1,
    explain: "Only one entity type (EMPLOYEE) participates, related back to itself — this is a unary, or recursive, relationship of degree 1.",
  },
  {
    q: "How is a recursive (unary) relationship like EMPLOYEE-supervises-EMPLOYEE typically implemented in SQL?",
    options: [
      "As two separate tables that never connect",
      "As a self-referencing foreign key (e.g., Supervisor referencing EmployeeNumber in the same table), queried with a self join",
      "It cannot be implemented in a relational database",
      "As a ternary relationship with a third table",
    ],
    answer: 1,
    explain: "A foreign key column on EMPLOYEE (e.g., Supervisor) that references EMPLOYEE's own primary key implements the recursive relationship; querying it uses a self join with two table aliases.",
  },
  {
    q: "Which relationship degree is the most common in real-world data models?",
    options: ["Unary", "Binary", "Ternary", "Quaternary"],
    answer: 1,
    explain: "Binary relationships (between two distinct entity types) are by far the most common shape — most textbook examples (department/employee, student/course) are binary.",
  },
  {
    q: "What characterizes a true ternary relationship, as opposed to three separate binary relationships?",
    options: [
      "It always has more attributes than a binary relationship",
      "A single fact genuinely requires all three entity types present simultaneously to be meaningful — decomposing it into pairwise relationships would lose information",
      "It can only exist between weak entities",
      "It must always be 1:1 on all three sides",
    ],
    answer: 1,
    explain: "A ternary relationship (e.g., SUPPLIER ships PART to WAREHOUSE) records a fact that ties three entities together at once; splitting it into three independent binary relationships loses the connection between which specific instances co-occurred.",
  },
  {
    q: "How is a ternary relationship typically implemented in a relational schema?",
    options: [
      "As three separate two-column tables",
      "As an associative entity with a foreign key to each of the three participating entities",
      "It cannot be implemented — ternary relationships are purely conceptual",
      "As a single column that lists all three IDs concatenated",
    ],
    answer: 1,
    explain: "A ternary relationship becomes one table (e.g., SHIPMENT) with foreign keys to all three participants, plus any attributes belonging to that three-way combination.",
  },
  {
    q: "Two systems both involve PROFESSOR, CLASS, and DEPARTMENT. One connects PROFESSOR directly to CLASS; the other connects PROFESSOR directly to DEPARTMENT. What determines which is 'correct'?",
    options: [
      "Only one of the two models can ever be correct in an absolute sense",
      "The context — specifically, which business questions the particular system must answer",
      "Whichever model has fewer entities is always correct",
      "PROFESSOR must always connect to both, with no exceptions",
    ],
    answer: 1,
    explain: "Both models can be equally valid; the correct choice depends on the system's purpose (e.g., an enrollment system needs PROFESSOR-CLASS; an HR system needs PROFESSOR-DEPARTMENT), not on some universally 'true' structure.",
  },
  {
    q: "A training center changes its policy from 'each class has exactly one instructor' to 'classes may be co-taught by multiple instructors.' How does this affect the INSTRUCTOR-CLASS relationship's cardinality?",
    options: [
      "It has no effect on cardinality, only on attributes",
      "It changes the relationship from 1:N to N:M, likely requiring a new associative entity",
      "It changes the relationship's degree from binary to ternary",
      "It makes INSTRUCTOR a weak entity",
    ],
    answer: 1,
    explain: "Since a CLASS can now have more than one INSTRUCTOR, the maximum cardinality on the CLASS side changes from one to many — flipping the relationship from 1:N to N:M, typically resolved with an associative entity like CLASS_ASSIGNMENT.",
  },
  {
    q: "A retailer only creates a CUSTOMER record after a completed purchase (no record for browsers). What should the minimum cardinality be on the CUSTOMER side of the CUSTOMER-PURCHASE relationship?",
    options: [
      "Zero, because purchases are optional",
      "One (mandatory), because being in CUSTOMER implies at least one PURCHASE already exists under this policy",
      "Cardinality doesn't apply to minimums, only maximums",
      "Undefined until the database is implemented",
    ],
    answer: 1,
    explain: "Given this specific business rule, every CUSTOMER row is guaranteed to have at least one related PURCHASE — so minimum cardinality on the CUSTOMER side is 1, not 0. A different policy (recording leads before any purchase) would require minimum 0 instead.",
  },
  {
    q: "In Crow's Foot notation, what does 'bar + bar' (||) at both ends of a relationship line indicate overall?",
    options: [
      "A many-to-many relationship",
      "A one-to-one (1:1) relationship where both sides are mandatory",
      "A unary relationship",
      "An optional relationship on both sides",
    ],
    answer: 1,
    explain: "A single bar at each end means 'exactly one' on both sides — the signature of a mandatory 1:1 relationship, such as EMPLOYEE and their single assigned PARKING_SPOT.",
  },
  {
    q: "Reading a relationship line, the trick is to cover everything except the entity box and its nearest symbol, then finish which sentence?",
    options: [
      "\"This entity was created before...\"",
      "\"One instance of [this entity] relates to ___ instance(s) of the other entity.\"",
      "\"This entity has ___ attributes.\"",
      "\"This entity's identifier is...\"",
    ],
    answer: 1,
    explain: "Reading Crow's Foot notation one end at a time — 'one instance of this entity relates to ___ of the other' — avoids the common beginner mistake of trying to interpret both ends of the line simultaneously.",
  },
  {
    q: "A hospital's business rule: 'Every PATIENT must be assigned to at least one ROOM; a ROOM may currently have zero or more PATIENTs.' What symbol combination appears on the PATIENT end of the line (nearest the PATIENT box)?",
    options: ["Circle + crow's foot (zero or many)", "Bar + crow's foot (one or many)", "Bar + bar (exactly one)", "Circle only (zero)"],
    answer: 1,
    explain: "'At least one ROOM' means the PATIENT side's minimum is 1 and, if a patient could occupy more than one room concurrently, the maximum would be many — bar + crow's foot reads as 'one or many.'",
  },
  {
    q: "A library rule: 'A BOOK_COPY may currently be checked out to zero or one BORROWER at a time.' What symbol combination sits on the BORROWER end of this relationship (nearest the BORROWER box, from BOOK_COPY's perspective)?",
    options: ["Bar + crow's foot", "Circle + bar (zero or one)", "Crow's foot only", "Bar + bar"],
    answer: 1,
    explain: "'Zero or one' is minimum 0, maximum 1 — drawn as a circle (zero, optional) plus a single bar (maximum one), not a crow's foot, since more than one borrower per copy at a time isn't allowed.",
  },
  {
    q: "Which of the following is the best real-world example of a 1:1 relationship?",
    options: [
      "STUDENT enrolls in COURSE",
      "COUNTRY has one CAPITAL_CITY, and a CAPITAL_CITY belongs to exactly one COUNTRY",
      "AUTHOR writes many BOOKs",
      "CUSTOMER places many ORDERs",
    ],
    answer: 1,
    explain: "A country has exactly one capital, and a capital city belongs to exactly one country — a clean, if rare, 1:1 pairing. The others are 1:N or N:M shapes.",
  },
  {
    q: "A gym tracks 'A MEMBER may book many CLASS_SESSIONs; a CLASS_SESSION has many MEMBERs booked into it.' What relationship shape is this, and what will implementing it in SQL require?",
    options: [
      "1:1 — no extra table needed",
      "N:M — an associative entity (e.g., BOOKING) with foreign keys to both MEMBER and CLASS_SESSION",
      "1:N — a foreign key directly on MEMBER",
      "Ternary — three foreign keys required",
    ],
    answer: 1,
    explain: "Many members per session and many sessions per member is N:M — implemented with an associative/linking table holding a foreign key to each side, exactly like WP's ASSIGNMENT table for EMPLOYEE-PROJECT.",
  },
  {
    q: "In the gym-booking scenario above, where would a 'CheckInTime' attribute (the exact time a member checked into a specific session) belong?",
    options: [
      "On MEMBER, since it's about a person",
      "On CLASS_SESSION, since it's about an event",
      "On the associative entity (BOOKING), since it describes one specific member-session pairing",
      "It cannot be stored in a relational database",
    ],
    answer: 2,
    explain: "CheckInTime describes one particular pairing of a member and a session — the same reasoning as HoursWorked on WP's ASSIGNMENT table — so it belongs on the associative entity, not on either parent.",
  },
  {
    q: "What is the key difference between an ID-dependent weak entity and an associative entity, given that both often use composite primary keys made of foreign keys?",
    options: [
      "There is no difference — they are the same construct with two names",
      "An ID-dependent weak entity typically resolves a 1:N relationship to a single parent it can't exist without; an associative entity typically resolves an N:M relationship between two independent parent entities",
      "Associative entities can never have their own attributes",
      "Weak entities are always ternary, associative entities are always binary",
    ],
    answer: 1,
    explain: "Both use inherited keys, but conceptually a weak entity (e.g., DEPENDENT) exists because of a single owning parent, while an associative entity (e.g., ASSIGNMENT) exists specifically to resolve a many-to-many relationship between two peers.",
  },
  {
    q: "Which of these is the best example of a non-ID-dependent weak entity?",
    options: [
      "A DEPENDENT identified only by (EmployeeNumber, DependentSeq)",
      "A SECTION of a COURSE that has its own SectionID, but cannot exist if the COURSE is deleted",
      "An ASSIGNMENT identified by (ProjectID, EmployeeNumber)",
      "A DEPARTMENT with its own DepartmentID",
    ],
    answer: 1,
    explain: "SECTION has its own independent identifier (SectionID) — unlike DEPENDENT or ASSIGNMENT, which borrow part of their identity from a parent — yet it still can't logically exist without its parent COURSE, making it non-ID-dependent.",
  },
  {
    q: "What visual cue distinguishes an identifying relationship from a non-identifying relationship on an E-R diagram?",
    options: [
      "Identifying relationships are drawn in a different color",
      "Identifying relationships use a solid line; non-identifying relationships use a dashed line",
      "Identifying relationships never have cardinality symbols",
      "There is no visual distinction; both look identical",
    ],
    answer: 1,
    explain: "A solid line signals an identifying relationship (to an ID-dependent weak entity, whose key includes the parent's key); a dashed line signals a non-identifying relationship (to a non-ID-dependent weak entity, or between two strong entities).",
  },
  {
    q: "'A PART may be composed of other PARTs (a sub-assembly built from smaller parts).' What degree and shape best describes this bill-of-materials relationship?",
    options: ["Binary 1:N", "Unary (recursive), typically N:M", "Ternary 1:1", "Binary N:M"],
    answer: 1,
    explain: "Only one entity type (PART) is involved, related back to itself, so it's unary/recursive — and since a part can be made of many sub-parts and also be a sub-part of many larger parts, it's typically modeled as N:M, resolved with an associative entity.",
  },
  {
    q: "'A COURSE may have zero or more prerequisite COURSEs, and may itself be a prerequisite for zero or more other COURSEs.' What degree and cardinality is this?",
    options: ["Binary, 1:N", "Unary, N:M", "Ternary, 1:1", "Unary, 1:1"],
    answer: 1,
    explain: "Only COURSE is involved (unary/recursive), and since a course can require multiple prerequisites and also be a prerequisite for multiple other courses, the cardinality is N:M — typically resolved with an associative entity like COURSE_PREREQUISITE.",
  },
  {
    q: "Why can't a bill-of-materials PART-composed-of-PART relationship be implemented with a single self-referencing foreign key column, the way EMPLOYEE-supervises-EMPLOYEE is?",
    options: [
      "It actually can, in exactly the same way",
      "Because it's N:M (a part can have many sub-parts and be a sub-part of many others), while supervisor is 1:N (one supervisor per employee) — N:M unary relationships need an associative entity, not just one FK column",
      "Because PART is always a weak entity",
      "Because SQL doesn't allow self-referencing foreign keys",
    ],
    answer: 1,
    explain: "A single FK column works for 1:N unary relationships (each employee has exactly one supervisor). A part can be composed of many sub-parts AND be used in many larger assemblies — that's N:M, which needs an associative entity (e.g., PART_COMPONENT with parent_part_id and child_part_id) just like any other N:M relationship.",
  },
  {
    q: "A shipping company records 'DRIVER delivers PACKAGE using VEHICLE' as a single fact tying all three together for insurance purposes. What degree is this relationship, and how is it typically implemented?",
    options: [
      "Binary — as two separate tables",
      "Ternary — as one associative entity with a foreign key to DRIVER, PACKAGE, and VEHICLE",
      "Unary — as a self-referencing key on PACKAGE",
      "It cannot be modeled relationally",
    ],
    answer: 1,
    explain: "Because the single delivery-event fact genuinely requires all three entities present together, this is ternary, and like the SUPPLIER-PART-WAREHOUSE example, it's implemented as one associative entity (e.g., DELIVERY) with three foreign keys.",
  },
  {
    q: "Why might modeling 'SUPPLIER ships PART to WAREHOUSE' as three separate binary relationships (SUPPLIER-PART, PART-WAREHOUSE, SUPPLIER-WAREHOUSE) lose information compared to one ternary relationship?",
    options: [
      "It wouldn't lose anything — the two approaches are always equivalent",
      "Three pairwise relationships can't record which specific supplier shipped which specific part to which specific warehouse in one shipment event",
      "Binary relationships can't have attributes at all",
      "SQL forbids more than two foreign keys in a single table",
    ],
    answer: 1,
    explain: "Decomposing into pairwise relationships tells you 'this supplier deals with this part' and 'this part goes to this warehouse' separately, but not that a specific shipment event tied one particular supplier, part, and warehouse together — that combined fact only survives in a true ternary relationship.",
  },
  {
    q: "In the James River Jewelry case, why does the business rule 'a CUSTOMER record is only created after a completed purchase' matter for the CUSTOMER-PURCHASE relationship's minimum cardinality?",
    options: [
      "It doesn't affect cardinality, only naming",
      "It makes the minimum cardinality on the CUSTOMER side 1 (mandatory), since every CUSTOMER row is guaranteed to already have at least one PURCHASE",
      "It means CUSTOMER and PURCHASE must be merged into one table",
      "It forces the relationship to become N:M",
    ],
    answer: 1,
    explain: "Because the business never creates a CUSTOMER without a completed purchase already existing, that policy alone justifies a mandatory (minimum 1) relationship from CUSTOMER to PURCHASE — a different policy (tracking leads) would require minimum 0 instead.",
  },
  {
    q: "A CRM system, unlike the James River Jewelry retail model, wants to track prospective customers before any purchase happens. What does this imply for the data model?",
    options: [
      "Nothing changes; the same model works for both",
      "The CUSTOMER-PURCHASE relationship (or an added LEAD entity) needs a zero-minimum, not a mandatory one, since a customer can exist with no purchases yet",
      "PURCHASE must become a weak entity of CUSTOMER",
      "The relationship must become ternary",
    ],
    answer: 1,
    explain: "Once the business rule changes to allow customers who haven't purchased anything, the strict 'minimum 1' assumption breaks — the model needs a zero-minimum relationship, or a separate LEAD entity upstream of CUSTOMER, to reflect the new policy.",
  },
  {
    q: "According to this module, what should you write down BEFORE translating a cardinality decision into bars, circles, and crow's feet?",
    options: [
      "Nothing — go straight from intuition to symbols",
      "The business rule in a full, plain-English sentence",
      "The final SQL CREATE TABLE statement",
      "A list of every possible cardinality combination",
    ],
    answer: 1,
    explain: "The recommended discipline is to state the business rule in plain English first (\"a customer must have made at least one purchase to exist in this database\") and only then translate it into notation — if you can't state the rule, you're guessing at the cardinality, not deriving it.",
  },
  {
    q: "A company's PROFESSOR-CLASS model differs from its PROFESSOR-DEPARTMENT model. According to this module, what determines which relationship the data model should emphasize?",
    options: [
      "Whichever relationship was discovered first during interviews",
      "The specific questions that particular system is being built to answer",
      "PROFESSOR must always connect to both with equal emphasis, no exceptions",
      "Departmental relationships always take priority over academic ones",
    ],
    answer: 1,
    explain: "Both PROFESSOR-CLASS and PROFESSOR-DEPARTMENT are valid models of the same real-world entities; which one a given system emphasizes depends entirely on the questions that system exists to answer (scheduling vs. payroll/HR), not on any universal truth about professors.",
  },
  {
    q: "What is the main risk of designing an E-R diagram based on 'how these entities usually relate' rather than a stated business rule?",
    options: [
      "There is no risk; intuition is always correct",
      "You may pick the wrong cardinality or even the wrong entities for this specific organization's actual policies",
      "The diagram will fail to render in draw.io",
      "SQL will reject the resulting CREATE TABLE statements",
    ],
    answer: 1,
    explain: "Cardinality (and even entity structure) is determined by the specific business's rules and needs, not by a generic assumption about how similar entities 'usually' behave elsewhere — designing from intuition risks building the wrong model for this organization.",
  },
  {
    q: "Which of the following pairs is degree-independent of cardinality, meaning you must check both separately?",
    options: [
      "Whether a relationship is binary AND whether it is 1:N, N:M, or 1:1",
      "Whether an entity has an identifier",
      "Whether a table has a primary key",
      "Whether a column allows NULLs",
    ],
    answer: 0,
    explain: "Degree (unary/binary/ternary) and cardinality (1:1, 1:N, N:M) are two separate, independent properties of any relationship — you must determine each one from the business rules; neither implies the other.",
  },
  {
    q: "Which combination is possible according to this module: a unary relationship that is also many-to-many?",
    options: [
      "No — unary relationships are always 1:N",
      "Yes — e.g., a COURSE that can require many prerequisite COURSEs and be a prerequisite for many others",
      "No — unary relationships are always 1:1",
      "Only if the entity is weak",
    ],
    answer: 1,
    explain: "Degree and cardinality combine freely: the course-prerequisite example is unary (only COURSE is involved) and N:M (many prerequisites per course, and a course can be a prerequisite for many others).",
  },
  {
    q: "A retail chain's ORDER-PRODUCT relationship needs to record 'QuantityOrdered' and 'UnitPriceAtTimeOfOrder' per order-product combination. What construct is required?",
    options: [
      "Nothing extra — ORDER and PRODUCT alone suffice",
      "An associative entity (e.g., ORDER_LINE) holding QuantityOrdered and UnitPriceAtTimeOfOrder, linked to both ORDER and PRODUCT",
      "A ternary relationship with a third entity called PRICE",
      "A weak entity dependent only on PRODUCT",
    ],
    answer: 1,
    explain: "Since QuantityOrdered and UnitPriceAtTimeOfOrder describe a specific order-product pairing (not either entity alone), they belong on an associative entity like ORDER_LINE — the same pattern as WP's ASSIGNMENT table.",
  },
  {
    q: "Why does UnitPriceAtTimeOfOrder need to live on the associative entity rather than simply being read from PRODUCT's current price?",
    options: [
      "It doesn't matter; both approaches are identical",
      "Because a product's price can change over time, and the order needs to preserve the price that applied at the moment of that specific order",
      "Because PRODUCT never has a price attribute",
      "Because associative entities cannot reference PRODUCT",
    ],
    answer: 1,
    explain: "If price is only stored on PRODUCT and it later changes, historical orders would incorrectly show the new price. Storing UnitPriceAtTimeOfOrder on the associative entity preserves the actual price in effect for that specific transaction.",
  },
  {
    q: "A university wants to model 'STUDENT has ADVISOR' where each student has exactly one advisor, and a professor may advise many students but some professors advise none. What is the correct cardinality reading from the ADVISOR (professor) side toward STUDENT?",
    options: ["Exactly one (bar + bar)", "Zero or many (circle + crow's foot)", "One or many (bar + crow's foot)", "Zero or one (circle + bar)"],
    answer: 1,
    explain: "Since a professor can advise many students but some advise zero, the minimum is 0 and the maximum is many — circle + crow's foot, read from the professor's end toward STUDENT.",
  },
  {
    q: "In the same STUDENT-ADVISOR scenario, what is the correct cardinality reading from the STUDENT side toward ADVISOR (professor)?",
    options: ["Zero or many", "Exactly one (bar + bar), since every student has exactly one advisor", "One or many", "Zero or one"],
    answer: 1,
    explain: "Each student has exactly one advisor with no exceptions stated — minimum 1, maximum 1 — bar + bar on the STUDENT end of the line.",
  },
  {
    q: "What does it mean when a relationship line's business rule can't be stated without both entities and describes one combined event, rather than being reducible to 'A relates to B' and 'B relates to C' separately?",
    options: [
      "The relationship must be 1:1",
      "It's a strong signal you may be looking at a genuine ternary relationship rather than two binary ones",
      "It means one of the entities is redundant and should be deleted",
      "It means the relationship cannot be implemented in SQL",
    ],
    answer: 1,
    explain: "The defining test for a true ternary relationship is that the fact requires all three entities present simultaneously to be meaningful — if it can be split into independent pairwise facts without losing anything, it was never truly ternary.",
  },
  {
    q: "What is the practical effect, in SQL terms, of resolving an N:M relationship with an associative entity?",
    options: [
      "It has no practical effect — N:M relationships can be stored directly with a single foreign key",
      "It converts one N:M relationship into two 1:N relationships (each parent to the associative entity), which is the only way a relational table can represent a many-to-many link",
      "It eliminates the need for primary keys on the associative entity",
      "It converts the relationship into a unary relationship",
    ],
    answer: 1,
    explain: "A relational table can only hold a foreign key pointing to one row on the 'many' side of a 1:N relationship. Since a table can't natively store 'many-to-many' directly, the associative entity converts the N:M shape into two ordinary 1:N relationships — one from each original entity to the new entity.",
  },
  {
    q: "Which statement about conceptual E-R diagrams and physical table design is accurate?",
    options: [
      "They are the same thing, produced in the same step",
      "The conceptual E-R diagram models business meaning and comes first; converting it into actual tables (with foreign keys) is a later, separate step covered under database design",
      "Foreign keys must be decided before any E-R diagram is drawn",
      "E-R diagrams are only used after the database is already built, for documentation purposes",
    ],
    answer: 1,
    explain: "The E-R diagram is a conceptual model built during analysis, focused on business meaning; the mechanical conversion into relational tables — including adding foreign keys — happens afterward, in database design (see Module 05).",
  },
  {
    q: "Two departments in the same company use different scheduling policies: Department A says 'each class has exactly one instructor,' Department B says 'classes may be co-taught.' Can both departments' INSTRUCTOR-CLASS relationships be modeled differently within the same overall system?",
    options: [
      "No, every relationship in a system must use the same cardinality everywhere",
      "Yes — cardinality is driven by each specific business rule in its own context, so different parts of an organization can legitimately need different shapes for what looks like 'the same' relationship",
      "No, because INSTRUCTOR and CLASS can only ever have one correct relationship",
      "Yes, but only if the departments are modeled as ternary relationships",
    ],
    answer: 1,
    explain: "Cardinality is a direct reflection of stated business rules, not a fixed property of the entity types involved — different policies in different contexts legitimately produce different cardinalities for what appears to be the same kind of relationship.",
  },
  {
    q: "What is the first deliverable-producing phase of the database development process, and what does it hand off to the next phase?",
    options: [
      "Implementation; hands off a maintenance plan",
      "Requirements analysis; hands off the approved requirements and business rules that shape the conceptual E-R model",
      "Component design; hands off the working system",
      "Maintenance; hands off the original project plan",
    ],
    answer: 1,
    explain: "Requirements analysis gathers and documents business rules and needs, producing approved requirements — the direct input for building the conceptual (E-R) model in the following phase.",
  },
  {
    q: "Why is skipping straight from a vague idea to a Crow's Foot diagram, without first writing out business rules, considered a bad practice in this module?",
    options: [
      "It's actually the recommended fast-track approach",
      "Cardinality decisions become guesses rather than derivations from a stated rule, risking a model that doesn't match how the organization actually operates",
      "draw.io requires business rules to be typed in before symbols can be added",
      "SQL will not compile without documented business rules",
    ],
    answer: 1,
    explain: "Without a stated business rule to point to, cardinality choices (and even entity choices) become guesswork. The discipline of writing the rule first, then translating it to notation, is what keeps the model grounded in the organization's actual policies.",
  },
  {
    q: "An airline's FLIGHT and AIRPLANE: 'Each FLIGHT (a specific scheduled departure) uses exactly one AIRPLANE; an AIRPLANE may be used for many FLIGHTs over its lifetime.' What cardinality shape is this?",
    options: ["1:1", "1:N (one airplane, many flights; each flight has one airplane)", "N:M", "Ternary"],
    answer: 1,
    explain: "One AIRPLANE relates to many FLIGHTs, but each FLIGHT uses only one AIRPLANE at a time — the classic 1:N shape, just like DEPARTMENT-EMPLOYEE.",
  },
  {
    q: "Continuing the airline example, if the airline later allows 'code-share' flights operated jointly using more than one AIRPLANE per FLIGHT (e.g., swapping aircraft mid-route with connecting legs each having a plane), and also wants planes usable by many flights, what would the FLIGHT-AIRPLANE relationship likely need to become?",
    options: [
      "It would stay 1:N with no changes",
      "N:M, since a flight could now involve multiple airplanes and airplanes still serve multiple flights, likely resolved with an associative entity per flight leg",
      "1:1, since each flight is now unique",
      "Unary, since only one entity type would be involved",
    ],
    answer: 1,
    explain: "If a single flight record could now be associated with more than one airplane (e.g., per leg), the maximum cardinality on the FLIGHT side changes from one to many, flipping the relationship to N:M and typically requiring an associative entity (e.g., FLIGHT_LEG) to track which plane covered which segment.",
  },
  {
    q: "What is the main lesson of comparing the airline FLIGHT-AIRPLANE example under two different policies?",
    options: [
      "Airlines never change their aircraft-assignment policies",
      "The same two entity types can require a different cardinality shape purely because the business's operational policy changed — not because the entities themselves changed",
      "FLIGHT and AIRPLANE must always be modeled as N:M",
      "Cardinality is fixed once chosen and cannot be revisited",
    ],
    answer: 1,
    explain: "This mirrors the INSTRUCTOR-CLASS co-teaching example: cardinality tracks business policy, not the inherent nature of the entities, so a policy change can legitimately flip 1:N into N:M (or vice versa) for what looks like the same pair of entity types.",
  },
  {
    q: "A conceptual E-R diagram shows PROJECT connected to EMPLOYEE with a crow's foot and circle on the EMPLOYEE end, and a crow's foot and circle on the PROJECT end too. What relationship shape does this describe?",
    options: [
      "1:1",
      "1:N",
      "N:M — zero or many on both ends",
      "This combination is invalid notation",
    ],
    answer: 2,
    explain: "Circle + crow's foot ('zero or many') appearing on BOTH ends of the line describes a many-to-many relationship where participation is optional on both sides — exactly WP's EMPLOYEE-PROJECT relationship before ASSIGNMENT resolves it.",
  },
  {
    q: "Once WP's EMPLOYEE-PROJECT N:M relationship is resolved into an associative entity (ASSIGNMENT), what does the new diagram look like?",
    options: [
      "A single N:M line remains, unchanged",
      "Two separate 1:N relationships: EMPLOYEE-to-ASSIGNMENT and PROJECT-to-ASSIGNMENT",
      "One ternary relationship connecting all three",
      "EMPLOYEE and PROJECT merge into a single entity",
    ],
    answer: 1,
    explain: "Introducing the associative entity always converts one N:M relationship into two 1:N relationships — EMPLOYEE relates to many ASSIGNMENT rows, and PROJECT relates to many ASSIGNMENT rows, with ASSIGNMENT holding a foreign key to each.",
  },
  {
    q: "A subscription streaming service models 'ACCOUNT has PROFILEs' where an account can have 1 to 5 profiles, and each profile belongs to exactly one account. What is the maximum-cardinality symbol on the PROFILE end, nearest the PROFILE box?",
    options: ["Bar (exactly one)", "Circle (zero)", "Crow's foot (many)", "No symbol is needed"],
    answer: 0,
    explain: "Each PROFILE belongs to exactly one ACCOUNT, so the symbol nearest PROFILE (describing PROFILE's own participation) is a single bar — exactly one.",
  },
  {
    q: "In the same streaming-service example, what is the cardinality on the ACCOUNT end (nearest the ACCOUNT box)?",
    options: [
      "Exactly one",
      "Zero or many",
      "One or many, since every account has at least 1 profile and up to 5",
      "Zero or one",
    ],
    answer: 2,
    explain: "The stated rule is '1 to 5 profiles' — meaning at least one profile is always required (minimum 1) and more than one is allowed (maximum many) — bar + crow's foot, 'one or many,' on the ACCOUNT end.",
  },
  {
    q: "Which of these best explains why an entity's identifier is shown underlined (or key-icon marked) inside its box on an E-R diagram?",
    options: [
      "It signals the attribute is optional",
      "It marks the attribute (or attribute set) that uniquely distinguishes one entity instance from every other instance of that same entity type",
      "It marks which attribute will become a foreign key",
      "It has no functional meaning, purely stylistic",
    ],
    answer: 1,
    explain: "The identifier (e.g., EmployeeNumber) is the attribute — or combination of attributes for a composite identifier — guaranteed to uniquely pick out one entity instance, which is why it's visually distinguished on the diagram.",
  },
  {
    q: "A weak entity ORDER_ITEM is identified by (OrderID, LineNumber) where LineNumber alone means nothing without an OrderID. What kind of weak entity is this?",
    options: [
      "Non-ID-dependent — it has its own identifier",
      "ID-dependent — its identifier is a composite including the parent ORDER's identifier",
      "It is not a weak entity at all",
      "It must be modeled as a ternary relationship",
    ],
    answer: 1,
    explain: "Since LineNumber only has meaning combined with OrderID (LineNumber '2' by itself is ambiguous across every order), ORDER_ITEM is ID-dependent — connected to ORDER with a solid identifying-relationship line.",
  },
  {
    q: "Would the relationship line connecting ORDER to ORDER_ITEM (from the previous question) be drawn solid or dashed?",
    options: ["Dashed, because ORDER_ITEM has attributes", "Solid, because it is an identifying relationship to an ID-dependent weak entity", "Dotted, a third valid style", "No line at all is used for weak entities"],
    answer: 1,
    explain: "ID-dependent weak entities are connected to their parent by a solid line, denoting an identifying relationship — the child's identity is only complete in combination with the parent's key.",
  },
  {
    q: "According to this module, once every entity in a design is given its own independent surrogate key (auto-incrementing ID), what happens to the practical importance of the weak-vs-strong entity distinction?",
    options: [
      "It becomes more important than ever",
      "It mainly stops mattering for how the final tables are built, since the resulting tables end up looking similar either way — it still matters for how key choices are justified conceptually",
      "It means no entity can ever be weak again",
      "It requires all relationships to become N:M",
    ],
    answer: 1,
    explain: "The notes point out that once every entity — even dependents and sections — has its own surrogate identifier, the physical tables converge in shape; the weak/strong distinction mostly matters for how you reason about and justify the design, not for the final schema's structure.",
  },
  {
    q: "A car dealership models 'SALESPERSON sells VEHICLE.' Business rule: 'Each VEHICLE (once sold) is sold by exactly one SALESPERSON; a SALESPERSON may sell many VEHICLEs, or none yet.' What is this relationship's shape?",
    options: ["N:M", "1:N, with the SALESPERSON side being zero-or-many", "1:1", "Ternary, involving DEALERSHIP too"],
    answer: 1,
    explain: "One SALESPERSON can relate to many VEHICLEs sold, but each sold VEHICLE has exactly one SALESPERSON — 1:N — and since some salespeople may have zero sales yet, that side is zero-or-many rather than one-or-many.",
  },
  {
    q: "Why would adding 'CommissionRate for this specific sale' as an attribute push the dealership model above toward needing more structure, even though VEHICLE-SALESPERSON is already 1:N (not N:M)?",
    options: [
      "It wouldn't — CommissionRate can simply be an attribute on VEHICLE, since a 1:N relationship's 'many' side (VEHICLE) can safely hold attributes describing that specific relationship instance",
      "It would force the relationship to become ternary regardless",
      "It would require deleting the SALESPERSON entity",
      "1:N relationships can never have any related attributes",
    ],
    answer: 0,
    explain: "Unlike N:M relationships, a 1:N relationship's 'many' side already has exactly one matching row on the 'one' side, so a per-sale attribute like CommissionRate can live directly on VEHICLE (the many side) without needing an extra associative entity — associative entities are specifically an N:M-resolution tool.",
  },
  {
    q: "What does it mean to say degree and cardinality 'combine freely,' as this module states?",
    options: [
      "They cancel each other out mathematically",
      "Any of the three degrees (unary, binary, ternary) can, in principle, pair with any of the cardinality shapes (1:1, 1:N, N:M), though some combinations are rarer than others in practice",
      "Only binary relationships can have a cardinality at all",
      "Ternary relationships are always N:M by definition",
    ],
    answer: 1,
    explain: "Degree answers 'how many entity types,' cardinality answers 'how many instances' — independent questions. The module's table shows unary-N:M (prerequisite courses), binary-1:N (department-employee), and ternary-N:M (supplier-part-warehouse) as valid, real combinations, among others.",
  },
  {
    q: "Which scenario is the clearest real-world case for treating something as a true ternary relationship rather than three binary ones?",
    options: [
      "A STUDENT enrolling in a COURSE",
      "A SUPPLIER, PART, and WAREHOUSE combination where a single shipment record must specify all three together with a quantity and date",
      "An EMPLOYEE reporting to a SUPERVISOR",
      "A CUSTOMER placing an ORDER",
    ],
    answer: 1,
    explain: "The shipment fact ties supplier, part, and warehouse together simultaneously — losing any one of the three loses the meaning of the fact — the textbook signature of a genuine ternary relationship, unlike the other options which are simple binary pairs.",
  },
  {
    q: "In the SHIPMENT associative entity resolving a ternary relationship, how many foreign keys does the table typically need, at minimum?",
    options: ["One", "Two", "Three — one to each of the three participating entities", "Zero; ternary relationships need no foreign keys"],
    answer: 2,
    explain: "A ternary relationship's associative entity needs a foreign key to each of the three participants (e.g., supplier_id, part_id, warehouse_id in SHIPMENT), often combined into a composite primary key alongside any additional attributes.",
  },
  {
    q: "True or false: 'Business rules must be gathered and documented before an E-R diagram can be considered reliable.'",
    options: ["False — diagrams should always come first, rules documented afterward for reference", "True — cardinality and structural decisions are derived from business rules, not guessed independently", "False — business rules only matter for SQL implementation, not for E-R diagrams", "True, but only for N:M relationships"],
    answer: 1,
    explain: "This module repeatedly emphasizes that cardinalities (and sometimes even entity/relationship structure itself) are derived directly from stated business rules — modeling without them first is guessing, not designing.",
  },
  {
    q: "What common mistake does the module warn against when reading a Crow's Foot relationship line?",
    options: [
      "Reading only the crow's foot symbol and ignoring bars/circles entirely",
      "Trying to interpret both ends of the relationship line in a single pass instead of reading each end's symbols independently",
      "Assuming every relationship is 1:N",
      "Assuming every entity has an identifier",
    ],
    answer: 1,
    explain: "The recommended technique is to cover everything except one entity box and its adjacent symbol, interpret that end alone, then repeat for the other end — trying to read both ends at once is a common source of misreading cardinality.",
  },
  {
    q: "A veterinary clinic tracks 'PET receives TREATMENT from VETERINARIAN,' where a single treatment record always specifies exactly which pet, which treatment type, and which vet performed it together. Is this most naturally ternary, or decomposable into binary relationships?",
    options: [
      "Always decomposable into three independent binary relationships with no loss of information",
      "Likely genuinely ternary, if the fact 'this vet performed this exact treatment on this exact pet, on this date' can't be reconstructed from separate PET-VET and PET-TREATMENT pairs alone",
      "Always 1:1 by definition",
      "It must be modeled as a weak entity of PET only",
    ],
    answer: 1,
    explain: "If knowing 'PET saw VET' and 'PET received TREATMENT-type' separately can't tell you which vet performed which specific treatment on which visit, the combined three-way fact requires a true ternary relationship (or an associative TREATMENT_EVENT entity with three foreign keys).",
  },
  {
    q: "Which statement correctly distinguishes 'relationship degree' from 'relationship cardinality' in one sentence?",
    options: [
      "Degree counts entity types involved; cardinality counts how many instances of one entity can relate to an instance of another",
      "Degree and cardinality are two names for the exact same concept",
      "Degree only applies to N:M relationships; cardinality only applies to 1:N relationships",
      "Cardinality determines whether a relationship is identifying or non-identifying",
    ],
    answer: 0,
    explain: "Degree (unary/binary/ternary) is about how many distinct entity types are involved in one relationship; cardinality (1:1/1:N/N:M) is about how many instances of each can pair up — two separate, independently-determined properties.",
  },
  {
    q: "Why does the module recommend labeling a relationship line so it reads naturally in BOTH directions (e.g., 'DEPARTMENT employs EMPLOYEE' and 'EMPLOYEE works in DEPARTMENT')?",
    options: [
      "It's purely cosmetic and has no effect on the model",
      "Writing both directions forces you to explicitly pin down cardinality on both ends, rather than assuming one side without checking it",
      "SQL requires bidirectional relationship names to generate foreign keys",
      "Only one direction is ever actually needed; the other is redundant",
    ],
    answer: 1,
    explain: "Explicitly stating both readings of a relationship (from each entity's point of view) prevents the common mistake of carefully specifying cardinality on one end while assuming (and getting wrong) the other end.",
  },
  {
    q: "A fitness app models 'USER logs WORKOUT.' Business rule: 'A user may log zero or many workouts; every workout entry belongs to exactly one user.' Which symbol pair sits nearest the WORKOUT box?",
    options: ["Circle + crow's foot", "Bar + bar (exactly one)", "Bar + crow's foot", "Circle only"],
    answer: 1,
    explain: "Every WORKOUT belongs to exactly one USER with no exceptions stated — minimum 1, maximum 1 — bar + bar, nearest the WORKOUT box (describing WORKOUT's own mandatory, single-parent participation).",
  },
  {
    q: "Continuing the fitness-app example, which symbol pair sits nearest the USER box?",
    options: ["Bar + bar", "Circle + crow's foot, since a user can log zero or many workouts", "Bar + crow's foot", "Circle only"],
    answer: 1,
    explain: "A user may have logged no workouts yet, or many — minimum 0, maximum many — circle + crow's foot, nearest the USER box.",
  },
  {
    q: "What is the practical reason a conceptual E-R diagram is drawn before, rather than after, writing CREATE TABLE statements?",
    options: [
      "E-R diagrams are only decorative documentation with no bearing on the schema",
      "The E-R diagram captures the business meaning and rules first, so the subsequent table design (with foreign keys, data types, and constraints) has a correct structural blueprint to implement",
      "SQL syntax cannot be written without an accompanying diagram file",
      "There is no meaningful order; either can come first with identical results",
    ],
    answer: 1,
    explain: "The conceptual model exists specifically to nail down entities, relationships, and cardinalities based on business rules before physical implementation details (foreign keys, data types) are added — building tables first risks encoding accidental or incorrect structure.",
  },
  {
    q: "A ternary SHIPMENT relationship needs to also track 'BatchNumber' for a specific shipment. Where does BatchNumber belong?",
    options: [
      "On SUPPLIER only",
      "On the SHIPMENT associative entity itself, since BatchNumber describes that specific three-way combination of supplier, part, and warehouse",
      "On WAREHOUSE only",
      "It must be split across all three parent entities equally",
    ],
    answer: 1,
    explain: "Just as HoursWorked belongs on WP's ASSIGNMENT (the associative entity resolving EMPLOYEE-PROJECT), any attribute describing the specific three-way shipment event belongs on the SHIPMENT associative entity, not on any single parent.",
  },
  {
    q: "Which of the following would most strongly suggest a 1:1 relationship should instead be merged into a single entity?",
    options: [
      "The two entities have completely unrelated attribute sets and independent lifecycles",
      "Every instance of Entity A always has exactly one matching instance of Entity B, and vice versa, with no case where they diverge",
      "Entity A has many more rows than Entity B",
      "The relationship is optional on both ends",
    ],
    answer: 1,
    explain: "When a 1:1 pairing is truly universal and mandatory on both sides with no exceptions, the 'second' entity often turns out to just be a set of optional or supplementary attributes that could live directly on the first entity's table instead.",
  },
  {
    q: "A hotel chain models 'GUEST stays in ROOM.' A guest may book the same room again on a future date, and each individual STAY has a check-in date, check-out date, and rate. What construct is needed to capture repeated GUEST-ROOM pairings over time?",
    options: [
      "Nothing extra; GUEST and ROOM alone suffice",
      "An associative entity, e.g. STAY, linking GUEST and ROOM and holding CheckInDate, CheckOutDate, and Rate for each specific visit",
      "A ternary relationship with a third entity called DATE",
      "GUEST and ROOM must be merged into one entity",
    ],
    answer: 1,
    explain: "Since a guest can stay in the same room multiple times, and each stay has its own dates and rate, those facts belong on an associative entity (STAY) rather than on GUEST or ROOM alone — the same pattern as ENROLLMENT or ASSIGNMENT.",
  },
  {
    q: "Why is GUEST-ROOM through repeated stays best modeled as N:M rather than 1:N?",
    options: [
      "Because a guest can stay in many different rooms over time, and a room can be stayed in by many different guests over time — neither side caps at one",
      "Because hotels never allow repeat guests",
      "Because ROOM is always a weak entity",
      "Because check-in dates make it automatically ternary",
    ],
    answer: 0,
    explain: "Over time, one guest uses many rooms and one room hosts many guests — the many-to-many shape — which is why an associative STAY entity (not a single foreign key) is required to capture every individual visit.",
  },
  {
    q: "A ride-share app models 'DRIVER completes RIDE.' Each ride has exactly one driver, and a driver may complete many rides (or none yet, if newly registered). What is the cardinality nearest the RIDE box?",
    options: ["Bar + bar (exactly one)", "Circle + crow's foot", "Bar + crow's foot", "Circle only"],
    answer: 0,
    explain: "Every RIDE has exactly one DRIVER — minimum 1, maximum 1 — bar + bar, nearest the RIDE box.",
  },
  {
    q: "In the same ride-share example, what is the cardinality nearest the DRIVER box?",
    options: ["Bar + bar", "Circle + crow's foot, since a driver may have zero or many completed rides", "Bar + crow's foot", "Crow's foot only, with no minimum symbol"],
    answer: 1,
    explain: "A newly registered driver may have zero rides so far, and an experienced driver may have many — minimum 0, maximum many — circle + crow's foot, nearest the DRIVER box.",
  },
  {
    q: "What role does an associative entity's composite primary key typically play?",
    options: [
      "It has no special role beyond uniqueness",
      "It usually combines the foreign keys to each parent entity (e.g., ProjectID + EmployeeNumber), which together also guarantee no duplicate pairing is stored twice",
      "It replaces the need for foreign keys entirely",
      "It is only used for ternary relationships, never for N:M binary ones",
    ],
    answer: 1,
    explain: "An associative entity's composite key (like ASSIGNMENT's ProjectID+EmployeeNumber) both links back to each parent and naturally enforces that a given pairing appears only once — a second identical pairing would violate the primary key.",
  },
  {
    q: "A furniture retailer wants to track 'DESIGNER collaborates with MANUFACTURER on PRODUCT_LINE,' where a single collaboration record must specify designer, manufacturer, and product line together with a royalty percentage. Which construct fits best?",
    options: [
      "Three independent binary relationships with no shared table",
      "A ternary relationship modeled as one associative entity with foreign keys to DESIGNER, MANUFACTURER, and PRODUCT_LINE, plus a RoyaltyPercentage attribute",
      "A unary relationship on DESIGNER only",
      "A 1:1 relationship between DESIGNER and MANUFACTURER",
    ],
    answer: 1,
    explain: "Since the royalty percentage and the collaboration fact depend on the specific combination of all three entities, this is a ternary relationship — implemented as one associative entity with three foreign keys, following the same pattern as SUPPLIER-PART-WAREHOUSE shipments.",
  },
];
