// ── Module 03 — SQL Fundamentals (100) ───────────────────────────────────────
QUESTIONS["03"] = [
  {
    q: "Which SQL statement category includes CREATE, ALTER, and DROP?",
    options: ["DML", "DDL", "DCL", "TCL"],
    answer: 1,
    explain: "Data Definition Language (DDL) statements create and modify database structures — tables, constraints, indexes. DML (INSERT/UPDATE/DELETE/SELECT) manipulates the data inside those structures.",
  },
  {
    q: "Which SQL statement category includes INSERT, UPDATE, and DELETE?",
    options: ["DDL", "DML", "DCL", "TCL"],
    answer: 1,
    explain: "Data Manipulation Language (DML) covers querying and changing data: SELECT, INSERT, UPDATE, DELETE.",
  },
  {
    q: "In a CREATE TABLE statement, what does a FOREIGN KEY constraint enforce?",
    options: [
      "The column must be unique across all rows",
      "The column's value must exist as a primary key value in the referenced table",
      "The column can never be NULL",
      "The column must be numeric",
    ],
    answer: 1,
    explain: "A foreign key (referential integrity) constraint requires that any non-null value in the FK column already exists as a primary key value in the table it references.",
  },
  {
    q: "What is the effect of a CHECK constraint such as CHECK (hours_worked >= 0)?",
    options: [
      "It automatically fills in 0 when no value is given",
      "It rejects any INSERT or UPDATE that would set hours_worked below 0",
      "It creates an index on hours_worked",
      "It makes hours_worked the primary key",
    ],
    answer: 1,
    explain: "CHECK constraints enforce a boolean condition on every row; any statement that would violate it is rejected by the database itself.",
  },
  {
    q: "Which PostgreSQL data type would you use for an exact, non-rounding monetary or hours value like 145.50?",
    options: ["INTEGER", "NUMERIC(p,s)", "BOOLEAN", "TEXT"],
    answer: 1,
    explain: "NUMERIC(p,s) stores exact fixed-point decimals — the right choice whenever rounding error is unacceptable, such as money or precise hour totals.",
  },
  {
    q: "In PostgreSQL, what does the SERIAL type do when used as a column type?",
    options: [
      "Stores a serialized JSON blob",
      "Auto-generates an incrementing integer, commonly used for surrogate primary keys",
      "Forces the column to always be NULL",
      "Stores a fixed-length string",
    ],
    answer: 1,
    explain: "SERIAL creates an auto-incrementing integer column, Postgres's equivalent to MySQL's AUTO_INCREMENT or SQL Server's IDENTITY(1,1).",
  },
  {
    q: "What is the MySQL equivalent of PostgreSQL's SERIAL for an auto-incrementing primary key?",
    options: ["AUTO_INCREMENT", "IDENTITY(1,1)", "SEQUENCE", "ROWID"],
    answer: 0,
    explain: "MySQL uses INT AUTO_INCREMENT; SQL Server uses INT IDENTITY(1,1); Postgres uses SERIAL or GENERATED ALWAYS AS IDENTITY.",
  },
  {
    q: "Which PostgreSQL type is best suited to store a flexible, semi-structured document alongside strict relational columns?",
    options: ["TEXT", "JSONB", "VARCHAR", "BOOLEAN"],
    answer: 1,
    explain: "JSONB stores JSON in a binary, indexable form, letting you query into document fields with operators like -> and ->> while keeping the rest of the table strictly relational.",
  },
  {
    q: "What does ALTER TABLE employee DROP COLUMN office_phone; do?",
    options: [
      "Sets every row's office_phone to NULL but keeps the column",
      "Removes the office_phone column and its data from the table structure entirely",
      "Renames the column to 'dropped_phone'",
      "Deletes every row in the table",
    ],
    answer: 1,
    explain: "DROP COLUMN permanently removes the column definition (and its stored data) from the table.",
  },
  {
    q: "What is the difference between DROP TABLE and TRUNCATE TABLE?",
    options: [
      "They are identical in every database",
      "DROP TABLE removes the structure and all data; TRUNCATE TABLE removes all rows but keeps the structure",
      "TRUNCATE TABLE removes the structure; DROP TABLE only removes rows",
      "DROP TABLE only works on empty tables",
    ],
    answer: 1,
    explain: "DROP TABLE deletes the table definition itself. TRUNCATE TABLE empties all rows but leaves the table (and its constraints/columns) intact for future use.",
  },
  {
    q: "In an INSERT statement, does the order of columns listed after the table name have to match the table's physical column order?",
    options: [
      "Yes, always",
      "No — it only has to match the order of the values supplied in VALUES",
      "Only for the primary key column",
      "Only in MySQL",
    ],
    answer: 1,
    explain: "The column list defines the mapping for that statement; as long as VALUES supplies data in the same order as the column list, the physical table order is irrelevant.",
  },
  {
    q: "What happens if you run DELETE FROM assignment; with no WHERE clause?",
    options: [
      "Nothing — SQL requires a WHERE clause on DELETE",
      "Every row in the assignment table is deleted",
      "Only the first row is deleted",
      "The table structure is dropped",
    ],
    answer: 1,
    explain: "DELETE without a WHERE clause is fully valid SQL and removes every row in the table. Always test the WHERE condition with a SELECT first.",
  },
  {
    q: "What does PostgreSQL's INSERT ... ON CONFLICT (key) DO UPDATE SET ... accomplish?",
    options: [
      "It always inserts a new row, ignoring duplicates",
      "It performs an 'upsert' — insert the row, or update it if a row with that key already exists",
      "It deletes the conflicting row",
      "It rolls back the entire transaction",
    ],
    answer: 1,
    explain: "ON CONFLICT DO UPDATE is Postgres's upsert syntax: on a key collision, it updates the existing row instead of failing or silently skipping.",
  },
  {
    q: "What is the MySQL equivalent of PostgreSQL's INSERT ... ON CONFLICT DO UPDATE?",
    options: ["MERGE INTO", "INSERT ... ON DUPLICATE KEY UPDATE", "UPSERT INTO", "REPLACE ONLY"],
    answer: 1,
    explain: "MySQL's idiomatic upsert syntax is INSERT ... ON DUPLICATE KEY UPDATE. SQL Server instead typically uses the more general MERGE statement.",
  },
  {
    q: "In the EXCLUDED pseudo-table used with Postgres's ON CONFLICT DO UPDATE, what does EXCLUDED refer to?",
    options: [
      "Rows that were deleted by the statement",
      "The row that would have been inserted, had there been no conflict",
      "Rows excluded by the WHERE clause",
      "A backup copy of the table",
    ],
    answer: 1,
    explain: "EXCLUDED represents the proposed new row's values — useful for writing DO UPDATE SET col = EXCLUDED.col to overwrite with the newly attempted values.",
  },
  {
    q: "Which clause comes first in the standard SQL query framework?",
    options: ["WHERE", "FROM", "SELECT (logically the framework is SELECT columns / FROM table / WHERE rows, written in that order)", "ORDER BY"],
    answer: 2,
    explain: "The written and conceptual order is SELECT (which columns), FROM (which table), WHERE (which rows) — even though execution internally evaluates FROM/WHERE before SELECT.",
  },
  {
    q: "What does SELECT DISTINCT department_name FROM employee; return?",
    options: [
      "Every employee's department, with duplicates",
      "Each distinct department name exactly once",
      "Only departments with more than one employee",
      "An error, because DISTINCT requires GROUP BY",
    ],
    answer: 1,
    explain: "DISTINCT removes duplicate rows from the result set, so each department name appears only once even if many employees share it.",
  },
  {
    q: "Why does WHERE office_phone = NULL never match any rows, even rows where office_phone is genuinely missing?",
    options: [
      "NULL must be written in lowercase",
      "NULL represents 'unknown/no value' and never equals anything, including another NULL, via the = operator",
      "= only works on numeric columns",
      "PostgreSQL disables NULL comparisons by default",
    ],
    answer: 1,
    explain: "NULL is not a value that can be equal to anything under three-valued logic. You must use IS NULL / IS NOT NULL to test for missing values.",
  },
  {
    q: "What does COALESCE(office_phone, 'No phone on file') return for a row where office_phone is NULL?",
    options: [
      "NULL",
      "'No phone on file'",
      "An empty string",
      "An error",
    ],
    answer: 1,
    explain: "COALESCE returns the first non-NULL argument in its list — a common way to supply a fallback display value for missing data.",
  },
  {
    q: "Which wildcard character in a LIKE pattern matches exactly one character?",
    options: ["%", "_", "*", "?"],
    answer: 1,
    explain: "In SQL LIKE patterns, % matches any sequence of zero or more characters, while _ matches exactly one character.",
  },
  {
    q: "What does WHERE position LIKE 'OPS_'; match?",
    options: [
      "'OPS' and anything starting with 'OPS'",
      "Exactly 'OPS1', 'OPS2', etc. — 'OPS' plus exactly one more character",
      "Only the literal string 'OPS_'",
      "Any string containing 'OPS' anywhere",
    ],
    answer: 1,
    explain: "The underscore wildcard matches exactly one character, so 'OPS_' matches four-character strings starting with 'OPS' — not 'OPS' alone, and not 'OPS10'.",
  },
  {
    q: "What is the key difference between LIKE and ILIKE in PostgreSQL?",
    options: [
      "ILIKE is faster but less accurate",
      "ILIKE performs a case-insensitive pattern match; LIKE is case-sensitive by default in Postgres",
      "LIKE only works on numeric columns",
      "There is no difference",
    ],
    answer: 1,
    explain: "PostgreSQL's LIKE is case-sensitive by default. ILIKE is a Postgres-specific extension that performs the same pattern match ignoring case.",
  },
  {
    q: "In PostgreSQL, how do you retrieve rows 6 through 10 (page 2 of a 5-per-page list), ordered by last_name?",
    options: [
      "SELECT * FROM employee ORDER BY last_name TOP 5 SKIP 5;",
      "SELECT * FROM employee ORDER BY last_name LIMIT 5 OFFSET 5;",
      "SELECT * FROM employee ORDER BY last_name PAGE 2;",
      "SELECT * FROM employee ORDER BY last_name ROWNUM BETWEEN 6 AND 10;",
    ],
    answer: 1,
    explain: "PostgreSQL (and MySQL) use LIMIT n OFFSET m to skip m rows and return the next n. SQL Server instead uses TOP or OFFSET...FETCH NEXT...ROWS ONLY.",
  },
  {
    q: "How would SQL Server retrieve the same 'first 5 rows' result that PostgreSQL gets from LIMIT 5?",
    options: [
      "SELECT TOP 5 * FROM employee ORDER BY last_name;",
      "SELECT * FROM employee LIMIT 5;",
      "SELECT * FROM employee FETCH 5;",
      "SELECT * FROM employee ROWCOUNT 5;",
    ],
    answer: 0,
    explain: "SQL Server historically uses SELECT TOP n; newer versions also support standard OFFSET ... FETCH NEXT ... ROWS ONLY for paging.",
  },
  {
    q: "An INNER JOIN between DEPARTMENT and EMPLOYEE will exclude which rows?",
    options: [
      "Nothing is ever excluded from an INNER JOIN",
      "Departments with no employees, and (if it could exist) employees with no matching department",
      "Only employees whose last name starts with a vowel",
      "Rows where department_name is alphabetically first",
    ],
    answer: 1,
    explain: "INNER JOIN keeps only rows that match on both sides of the join condition — unmatched rows on either side (department with zero employees, or an orphaned employee row) are dropped.",
  },
  {
    q: "In the Venn-diagram framing of joins, what does the overlapping (middle) region represent?",
    options: [
      "Rows found only in the left table",
      "Rows found only in the right table",
      "Rows that match the join condition on both tables — the INNER JOIN result",
      "Rows that were deleted",
    ],
    answer: 2,
    explain: "The overlap of the two circles is exactly the set of rows returned by an INNER JOIN — present in both tables and satisfying the join condition.",
  },
  {
    q: "To find every project with NO employees assigned to it, which pattern should you use?",
    options: [
      "INNER JOIN project to assignment, then WHERE hours_worked > 0",
      "LEFT OUTER JOIN project to assignment, then WHERE assignment.project_id IS NULL",
      "RIGHT OUTER JOIN assignment to project, then WHERE project_id = 0",
      "CROSS JOIN project and assignment",
    ],
    answer: 1,
    explain: "The 'find rows with no match' pattern: LEFT OUTER JOIN keeps every project (NULL-padding unmatched ones), then filtering for IS NULL on the right table's join column isolates the unmatched projects.",
  },
  {
    q: "Which JOIN type keeps every row from the right-hand table, padding unmatched left-side columns with NULL?",
    options: ["INNER JOIN", "LEFT OUTER JOIN", "RIGHT OUTER JOIN", "CROSS JOIN"],
    answer: 2,
    explain: "RIGHT OUTER JOIN preserves every row of the right table; unmatched rows get NULLs for the left table's columns.",
  },
  {
    q: "Which JOIN type returns every row from both tables, matched where possible and NULL-padded on either side otherwise?",
    options: ["INNER JOIN", "LEFT OUTER JOIN", "RIGHT OUTER JOIN", "FULL OUTER JOIN"],
    answer: 3,
    explain: "FULL OUTER JOIN is the union of LEFT and RIGHT OUTER JOIN results — every row from both sides appears, matched or NULL-padded.",
  },
  {
    q: "Why does MySQL require a UNION of a LEFT JOIN and a RIGHT JOIN to emulate a FULL OUTER JOIN?",
    options: [
      "MySQL has no JOIN support at all",
      "MySQL does not implement the FULL OUTER JOIN keyword natively",
      "MySQL only allows joins on primary keys",
      "UNION is required by the SQL standard for all joins",
    ],
    answer: 1,
    explain: "Unlike PostgreSQL and SQL Server, MySQL has no native FULL OUTER JOIN syntax, so it's commonly emulated with UNION of a LEFT JOIN and a RIGHT JOIN result.",
  },
  {
    q: "What is a 'self join' used for?",
    options: [
      "Joining two completely unrelated tables",
      "Joining a table to itself, typically to relate rows within the same table (e.g., employee to their own supervisor)",
      "A join that requires no ON clause",
      "A join that only works on a single-column table",
    ],
    answer: 1,
    explain: "A self join uses two aliases for the same table to compare rows against other rows in that table — the classic example is an employee/supervisor hierarchy stored in one EMPLOYEE table.",
  },
  {
    q: "In a self join modeling employee-supervisor relationships, why is LEFT OUTER JOIN preferred over INNER JOIN?",
    options: [
      "LEFT OUTER JOIN runs faster in every case",
      "INNER JOIN would drop the top-level employee (e.g., the CEO) who has no supervisor (NULL)",
      "LEFT OUTER JOIN is required by SQL syntax rules for self joins",
      "There's no difference for self joins",
    ],
    answer: 1,
    explain: "The CEO's supervisor column is NULL. An INNER JOIN would silently exclude that employee since NULL never matches in the ON clause; LEFT OUTER JOIN keeps them with NULL supervisor columns.",
  },
  {
    q: "What does a CROSS JOIN produce?",
    options: [
      "Only matching rows between two tables",
      "Every possible combination of rows from both tables (a Cartesian product)",
      "Rows that exist in one table but not the other",
      "An error unless an ON clause is supplied",
    ],
    answer: 1,
    explain: "CROSS JOIN pairs every row of one table with every row of the other, producing rows(A) × rows(B) results — no matching condition involved.",
  },
  {
    q: "What is the main structural difference between a subquery and a join, in terms of what columns can be displayed?",
    options: [
      "A subquery can display columns from any table involved; a join can only display columns from the outer table",
      "A join can display columns from any table involved; a subquery can only display columns from the outermost (top) table",
      "Both can always display columns from every table equally",
      "Neither can ever display more than one column",
    ],
    answer: 1,
    explain: "A subquery's outer query only ever sees the outer table's columns — the subquery is used purely to filter, not to add displayable columns. A join can select and display columns from every table in the FROM/JOIN chain.",
  },
  {
    q: "What is a correlated subquery?",
    options: [
      "A subquery that never references anything from the outer query",
      "A subquery that references a column from the outer query, effectively re-running once per outer row",
      "A subquery that must always use GROUP BY",
      "A subquery that can only appear in the FROM clause",
    ],
    answer: 1,
    explain: "A correlated subquery references a column from its enclosing (outer) query, so conceptually it's evaluated once per row of the outer query rather than once overall.",
  },
  {
    q: "What does COUNT(office_phone) count, as opposed to COUNT(*)?",
    options: [
      "The exact same thing as COUNT(*)",
      "The number of rows where office_phone IS NOT NULL",
      "The number of distinct phone numbers only",
      "Always zero",
    ],
    answer: 1,
    explain: "COUNT(column) counts only non-NULL values in that column, while COUNT(*) counts every row regardless of NULLs.",
  },
  {
    q: "In GROUP BY department_name, why can't you also SELECT first_name unless it's wrapped in an aggregate function?",
    options: [
      "SQL doesn't allow VARCHAR columns in SELECT",
      "For a department with multiple employees, SQL has no way to know which single first_name to display for that one summarized row",
      "first_name must always be the GROUP BY column",
      "This restriction only applies in MySQL",
    ],
    answer: 1,
    explain: "GROUP BY collapses many rows into one summary row per group; any non-aggregated column must be part of the grouping key, or SQL can't determine a single value to show.",
  },
  {
    q: "What is the difference between WHERE and HAVING?",
    options: [
      "They are interchangeable in every case",
      "WHERE filters individual rows before grouping; HAVING filters groups after aggregation",
      "HAVING filters rows before grouping; WHERE filters after",
      "WHERE can only be used with SELECT *",
    ],
    answer: 1,
    explain: "WHERE operates on raw rows prior to GROUP BY; HAVING operates on the aggregated groups afterward, and can reference aggregate functions like SUM() or COUNT() directly.",
  },
  {
    q: "Which SQL statement category do GRANT and REVOKE belong to?",
    options: ["DDL", "DML", "DCL", "TCL"],
    answer: 2,
    explain: "GRANT and REVOKE are Data Control Language (DCL) statements — they manage permissions rather than defining structures (DDL) or manipulating data (DML).",
  },
  {
    q: "Which SQL statement category do COMMIT and ROLLBACK belong to?",
    options: ["DDL", "DML", "DCL", "TCL"],
    answer: 3,
    explain: "COMMIT and ROLLBACK are Transaction Control Language (TCL) statements — they mark the boundaries of a transaction rather than defining structures or changing data directly.",
  },
  {
    q: "In CREATE TABLE project (..., CONSTRAINT fk_project_department FOREIGN KEY (department_name) REFERENCES department(department_name)), what is the purpose of writing the constraint as a named table constraint instead of inline?",
    options: [
      "It has no purpose; it is purely stylistic and behaves identically to an inline constraint",
      "It gives the constraint an explicit name, which makes it easier to reference later (e.g., when dropping or altering it), and is required for composite-column foreign keys",
      "It forces the column to allow NULLs",
      "It disables referential integrity checking",
    ],
    answer: 1,
    explain: "Named table constraints are easier to manage later (ALTER TABLE ... DROP CONSTRAINT fk_project_department) and are necessary when the constraint spans multiple columns, as with composite keys.",
  },
  {
    q: "Why does the assignment table in the Wedgewood Pacific schema use a composite PRIMARY KEY (project_id, employee_number) instead of a single-column key?",
    options: [
      "Because PostgreSQL requires every table to have at least two key columns",
      "Because the same employee can appear on many projects and the same project can have many employees, but each employee/project pairing should appear only once",
      "Because project_id and employee_number are both foreign keys, and foreign keys can never be primary keys alone",
      "Because composite keys are faster to index than single-column keys",
    ],
    answer: 1,
    explain: "The composite key (project_id, employee_number) makes the pairing itself unique — the intersection table for an N:M relationship needs the combination, not either column alone, to be unique.",
  },
  {
    q: "What does DEFAULT 0 accomplish in hours_worked NUMERIC(6,2) DEFAULT 0?",
    options: [
      "It forces every row to have hours_worked equal to 0, always",
      "It supplies the value 0 automatically whenever an INSERT doesn't specify hours_worked",
      "It creates a CHECK constraint requiring hours_worked >= 0",
      "It rounds any inserted value down to the nearest whole number",
    ],
    answer: 1,
    explain: "DEFAULT supplies a fallback value only when the column is omitted from an INSERT (or explicitly set to DEFAULT) — it does not restrict values that are explicitly provided.",
  },
  {
    q: "Which statement correctly distinguishes NOT NULL from UNIQUE as column constraints?",
    options: [
      "NOT NULL prevents duplicate values; UNIQUE prevents missing values",
      "NOT NULL requires a value to be present; UNIQUE requires that no two rows share the same value (NULLs aside)",
      "They are functionally identical in every database",
      "UNIQUE can only be applied to primary key columns",
    ],
    answer: 1,
    explain: "NOT NULL simply forbids missing values; UNIQUE forbids duplicate values across rows. A column can have one, both, or neither — PRIMARY KEY implies both together.",
  },
  {
    q: "What is wrong with running DROP TABLE department; while employee.department_name still references department as a foreign key?",
    options: [
      "Nothing — PostgreSQL always silently allows it",
      "The DROP fails because dependent foreign keys exist, unless the statement includes CASCADE",
      "It only deletes the rows in department, not the table itself",
      "It automatically converts department into a view",
    ],
    answer: 1,
    explain: "PostgreSQL blocks dropping a table that other tables still reference via foreign key, to protect referential integrity — you must either drop the dependents first or use DROP TABLE department CASCADE.",
  },
  {
    q: "Why is DROP TABLE ... CASCADE considered risky in a production environment?",
    options: [
      "It runs extremely slowly compared to a normal DROP TABLE",
      "It silently drops every dependent object (foreign keys, views, etc.) along with the table, potentially removing more than intended",
      "It only works on tables with no data",
      "It requires DBA-level permissions that regular users never have",
    ],
    answer: 1,
    explain: "CASCADE doesn't just remove the target table — it removes anything depending on it too, which can silently delete more of the schema than the person running the command realized.",
  },
  {
    q: "In PostgreSQL, what is the practical difference between TEXT and VARCHAR(n) for storing free-form notes?",
    options: [
      "TEXT cannot store more than 255 characters, but VARCHAR(n) can store unlimited text",
      "VARCHAR(n) enforces a maximum length of n characters; TEXT stores variable-length text with no length limit",
      "TEXT is always faster to query than VARCHAR",
      "VARCHAR(n) cannot be indexed",
    ],
    answer: 1,
    explain: "VARCHAR(n) caps the string at n characters and rejects longer input; TEXT stores text of any length. Aside from that constraint, PostgreSQL treats them almost identically internally.",
  },
  {
    q: "Which PostgreSQL data type would best model an is_completed flag on a project?",
    options: ["VARCHAR(1)", "INTEGER", "BOOLEAN", "JSONB"],
    answer: 2,
    explain: "BOOLEAN stores TRUE, FALSE, or NULL directly and is self-documenting; encoding a flag as VARCHAR('Y'/'N') or INTEGER (1/0) works but loses the type's built-in meaning and constraints.",
  },
  {
    q: "What is the SQL Server data type equivalent to PostgreSQL's TIMESTAMP for storing date-and-time values?",
    options: ["DATETIME2", "VARCHAR(MAX)", "BIT", "DECIMAL"],
    answer: 0,
    explain: "SQL Server's DATETIME2 corresponds to Postgres's TIMESTAMP; MySQL uses DATETIME for the same concept.",
  },
  {
    q: "ALTER TABLE employee ALTER COLUMN office_phone TYPE VARCHAR(20); does what?",
    options: [
      "Deletes the office_phone column",
      "Changes the office_phone column's data type/length to VARCHAR(20)",
      "Renames office_phone to VARCHAR",
      "Adds a new column called VARCHAR(20)",
    ],
    answer: 1,
    explain: "ALTER COLUMN ... TYPE changes an existing column's data type (here, widening the allowed string length) without dropping or recreating the table.",
  },
  {
    q: "What does ALTER TABLE employee RENAME COLUMN position TO job_title; accomplish?",
    options: [
      "Deletes the position column and creates a new empty job_title column",
      "Renames the existing position column to job_title, keeping its data intact",
      "Copies position's data into a new column while keeping the old column too",
      "Changes job_title's data type to match position",
    ],
    answer: 1,
    explain: "RENAME COLUMN changes only the column's name; existing data, constraints, and data type are preserved under the new name.",
  },
  {
    q: "In INSERT INTO assignment (project_id, employee_number, hours_worked) VALUES (1000,1,30.00), (1000,6,50.00), (1000,10,50.00);, what is happening?",
    options: [
      "A syntax error, because INSERT only allows one row per statement",
      "A single multi-row INSERT that adds three new assignment rows in one statement",
      "An UPDATE disguised as an INSERT",
      "Three separate tables are being created",
    ],
    answer: 1,
    explain: "Listing multiple parenthesized value sets after VALUES, separated by commas, inserts multiple rows in a single INSERT statement.",
  },
  {
    q: "Why is it good practice to run a SELECT with the same WHERE clause before executing an UPDATE or DELETE against real data?",
    options: [
      "SQL requires it syntactically",
      "It lets you confirm exactly which rows will be affected before you irreversibly change or remove them",
      "It automatically creates a backup of the affected rows",
      "It speeds up the subsequent UPDATE or DELETE",
    ],
    answer: 1,
    explain: "Previewing the WHERE clause with SELECT * shows exactly which rows would be touched, catching a too-broad or too-narrow condition before it does real (and possibly irreversible) damage.",
  },
  {
    q: "What does UPDATE employee SET position = 'Senior ' || position WHERE department_name = 'Sales and Marketing'; do?",
    options: [
      "Replaces every employee's position with the literal text 'Senior position'",
      "Prepends the text 'Senior ' to the existing position value, but only for employees in Sales and Marketing",
      "Deletes the position column",
      "Creates a new column named 'Senior'",
    ],
    answer: 1,
    explain: "The || operator concatenates strings in PostgreSQL, so this SET clause builds a new position value by prefixing the existing one with 'Senior ', scoped by the WHERE clause to just that department.",
  },
  {
    q: "What is the effect of running UPDATE assignment SET hours_worked = 80.00; with no WHERE clause?",
    options: [
      "Nothing happens; UPDATE requires a WHERE clause",
      "Every row in assignment has hours_worked set to 80.00",
      "Only rows where hours_worked was previously NULL are changed",
      "It only affects the first row inserted",
    ],
    answer: 1,
    explain: "Like DELETE, UPDATE without a WHERE clause is valid SQL and applies to every row in the table — a common source of accidental mass overwrites.",
  },
  {
    q: "In PostgreSQL's INSERT ... ON CONFLICT (project_id, employee_number) DO UPDATE SET hours_worked = EXCLUDED.hours_worked;, what does EXCLUDED.hours_worked refer to?",
    options: [
      "The old hours_worked value already stored in the table before the conflict",
      "The hours_worked value that was in the attempted (conflicting) INSERT",
      "The average of all hours_worked values in the table",
      "Always NULL",
    ],
    answer: 1,
    explain: "EXCLUDED represents the row that would have been inserted had there been no conflict, so EXCLUDED.hours_worked is the new value the INSERT attempted to write.",
  },
  {
    q: "Which of the following upsert syntaxes is specific to MySQL?",
    options: [
      "INSERT ... ON CONFLICT DO UPDATE",
      "INSERT ... ON DUPLICATE KEY UPDATE",
      "MERGE INTO ... WHEN MATCHED THEN UPDATE",
      "UPSERT INTO ... VALUES",
    ],
    answer: 1,
    explain: "MySQL's idiomatic upsert syntax is INSERT ... ON DUPLICATE KEY UPDATE. PostgreSQL and SQLite use ON CONFLICT DO UPDATE; SQL Server typically uses MERGE.",
  },
  {
    q: "What does the RETURNING clause let you do in PostgreSQL that you'd otherwise need a separate SELECT for?",
    options: [
      "Undo a statement after it runs",
      "See the rows affected by an INSERT, UPDATE, or DELETE immediately, without a second round-trip query",
      "Automatically log every DML statement to a file",
      "Prevent a statement from committing",
    ],
    answer: 1,
    explain: "RETURNING reports back the affected rows (e.g., a newly generated SERIAL key from an INSERT) as part of the same statement, avoiding a separate SELECT to look the value up afterward.",
  },
  {
    q: "INSERT INTO employee (first_name, last_name, department_name, email_address) VALUES ('Grace', 'Lin', 'InfoSystems', 'Grace.Lin@WP.com') RETURNING employee_number; would return what?",
    options: [
      "Nothing, since RETURNING only works with SELECT",
      "The auto-generated employee_number assigned to Grace Lin's new row",
      "The total count of employees in the table",
      "An error, because employee_number wasn't listed in the INSERT column list",
    ],
    answer: 1,
    explain: "Even though employee_number wasn't explicitly supplied (it's a SERIAL column), RETURNING employee_number reports the value the database automatically generated for the new row.",
  },
  {
    q: "In the standard query framework SELECT / FROM / WHERE, what determines the order that columns appear in the output?",
    options: [
      "The physical column order in the underlying table",
      "The order columns are listed in the SELECT clause",
      "Alphabetical order, always",
      "The order columns were originally created via CREATE TABLE",
    ],
    answer: 1,
    explain: "The SELECT clause's column order is entirely independent of the table's physical storage order — you can list columns in any order you like for display.",
  },
  {
    q: "What does SELECT * FROM project WHERE department_name IN ('Finance', 'Accounting'); return?",
    options: [
      "Only projects where department_name equals the literal string 'Finance, Accounting'",
      "Projects whose department_name matches either 'Finance' or 'Accounting'",
      "An error, because IN requires a subquery",
      "Every project except those in Finance or Accounting",
    ],
    answer: 1,
    explain: "IN (...) with a literal list matches rows whose column equals any one value from that list — equivalent to chaining several equality checks with OR.",
  },
  {
    q: "What does SELECT * FROM project WHERE start_date BETWEEN '2019-05-01' AND '2019-08-01'; include?",
    options: [
      "Only projects starting strictly after 2019-08-01",
      "Projects with start_date on or after 2019-05-01 and on or before 2019-08-01, inclusive of both endpoints",
      "Projects with start_date strictly between the two dates, excluding both endpoints",
      "Only projects with no start_date at all",
    ],
    answer: 1,
    explain: "BETWEEN a AND b is inclusive of both boundary values, so rows with start_date exactly equal to either endpoint are included in the result.",
  },
  {
    q: "Why does WHERE department_name = 'finance' fail to match a row where department_name is stored as 'Finance' in PostgreSQL?",
    options: [
      "Because PostgreSQL string comparisons with = are case-sensitive by default",
      "Because 'finance' is not valid SQL syntax",
      "Because WHERE cannot compare VARCHAR columns to string literals",
      "Because column values are always stored in uppercase",
    ],
    answer: 0,
    explain: "PostgreSQL's default collation makes = case-sensitive for text, so 'finance' and 'Finance' are treated as different strings unless you normalize case or use a case-insensitive comparison.",
  },
  {
    q: "Why should date literals in a WHERE clause use the format 'YYYY-MM-DD' rather than '05/08/2019'?",
    options: [
      "PostgreSQL doesn't support any other date format at all",
      "The ISO format is unambiguous, avoiding confusion between month-first (US) and day-first (many other locales) interpretations",
      "'YYYY-MM-DD' is faster for the database to parse",
      "Slash-separated dates are reserved for TIMESTAMP columns only",
    ],
    answer: 1,
    explain: "'05/08/2019' could mean May 8 or August 5 depending on locale conventions; the ISO 'YYYY-MM-DD' format removes that ambiguity entirely.",
  },
  {
    q: "What does SELECT * FROM employee WHERE NOT department_name = 'Production'; return?",
    options: [
      "Only employees in the Production department",
      "Every employee whose department_name is anything other than 'Production' (NULLs still excluded)",
      "An error, because NOT cannot be combined with =",
      "All employees, ignoring the condition entirely",
    ],
    answer: 1,
    explain: "NOT negates the condition that follows, so this returns employees whose department is not 'Production' — though rows where department_name is NULL are still excluded, since NOT NULL comparisons remain unknown under three-valued logic.",
  },
  {
    q: "What does SELECT * FROM employee WHERE first_name LIKE 'J%'; match?",
    options: [
      "Only names that are exactly 'J'",
      "Any first_name starting with 'J', followed by zero or more additional characters",
      "Any first_name containing 'J' anywhere in the string",
      "Any first_name that is exactly one character after 'J'",
    ],
    answer: 1,
    explain: "% matches zero or more characters, so 'J%' matches any string that begins with 'J' regardless of what (if anything) follows.",
  },
  {
    q: "What does SELECT * FROM employee WHERE email_address LIKE '%@WP.com'; match?",
    options: [
      "Only the literal string '@WP.com'",
      "Any email_address ending in '@WP.com', regardless of what precedes it",
      "Any email_address that starts with '@WP.com'",
      "Email addresses exactly 7 characters long",
    ],
    answer: 1,
    explain: "The leading % allows any sequence of characters before the fixed suffix '@WP.com', matching any address ending with that domain.",
  },
  {
    q: "On a MySQL database with a default case-insensitive collation, how does plain LIKE 'j%' behave compared to PostgreSQL's LIKE 'j%'?",
    options: [
      "Identically — LIKE is always case-sensitive in every database",
      "MySQL's LIKE would still match 'James' despite the lowercase 'j', while PostgreSQL's LIKE (case-sensitive by default) would not",
      "MySQL doesn't support LIKE at all",
      "PostgreSQL's LIKE is case-insensitive by default, unlike MySQL's",
    ],
    answer: 1,
    explain: "MySQL and SQL Server commonly default to case-insensitive collations, so LIKE behaves like ILIKE there. PostgreSQL's LIKE is case-sensitive by default, requiring ILIKE for case-insensitive matching.",
  },
  {
    q: "What is the result of SELECT first_name, last_name, COALESCE(office_phone, 'No phone on file') FROM employee; for a row where office_phone already has a value, e.g. '555-1234'?",
    options: [
      "'No phone on file', because COALESCE always overrides existing values",
      "'555-1234' — COALESCE only substitutes the fallback when the first argument is NULL",
      "NULL",
      "Both values are shown, comma-separated",
    ],
    answer: 1,
    explain: "COALESCE returns its first non-NULL argument; when office_phone already holds a real value, that value passes through unchanged and the fallback is never used.",
  },
  {
    q: "Which query correctly retrieves employees sorted by department first, then by last name within each department?",
    options: [
      "SELECT * FROM employee ORDER BY last_name, department_name;",
      "SELECT * FROM employee ORDER BY department_name, last_name;",
      "SELECT * FROM employee GROUP BY department_name ORDER BY last_name;",
      "SELECT * FROM employee WHERE department_name ORDER BY last_name;",
    ],
    answer: 1,
    explain: "ORDER BY sorts by the first listed column first, using later columns only to break ties — so department_name, last_name groups by department, then alphabetizes last names within each group.",
  },
  {
    q: "What is returned by SELECT * FROM employee ORDER BY last_name LIMIT 5 OFFSET 10;?",
    options: [
      "The first 5 rows, ordered by last_name",
      "Rows 11 through 15 (after skipping the first 10), ordered by last_name",
      "The last 5 rows in the table, unordered",
      "An error — OFFSET cannot be combined with LIMIT",
    ],
    answer: 1,
    explain: "OFFSET 10 skips the first 10 sorted rows, and LIMIT 5 then takes the next 5 — rows 11-15 of the sorted result, useful for paging.",
  },
  {
    q: "A report needs 'the top 3 projects by max_hours' on SQL Server, without using OFFSET/FETCH syntax. Which clause accomplishes this?",
    options: [
      "SELECT TOP 3 * FROM project ORDER BY max_hours DESC;",
      "SELECT * FROM project LIMIT 3;",
      "SELECT * FROM project ORDER BY max_hours DESC ROWS 3;",
      "SELECT * FROM project FETCH 3;",
    ],
    answer: 0,
    explain: "SQL Server's classic (pre-2012) syntax for limiting row count is SELECT TOP n, unlike PostgreSQL/MySQL's LIMIT n.",
  },
  {
    q: "What is the 'implicit join' style, as in FROM department, employee WHERE department.department_name = employee.department_name?",
    options: [
      "A join that requires no matching condition at all",
      "A style that lists tables comma-separated in FROM and moves the join condition into WHERE, producing the same result as an explicit INNER JOIN ... ON",
      "A join that only works with three or more tables",
      "A special PostgreSQL-only syntax not supported elsewhere",
    ],
    answer: 1,
    explain: "The implicit join style is functionally equivalent to INNER JOIN ... ON, but mixes 'how tables relate' and 'which rows to keep' into one WHERE clause — modern style prefers explicit JOIN...ON because it separates those concerns clearly.",
  },
  {
    q: "Why is explicit JOIN ... ON syntax generally preferred over the older implicit comma-join style?",
    options: [
      "Implicit joins run measurably slower in every database engine",
      "Explicit JOIN...ON separates the join condition from row-filtering conditions, making queries harder to get wrong once outer joins or extra filters are involved",
      "Implicit joins cannot return more than one row",
      "Only explicit joins support table aliases",
    ],
    answer: 1,
    explain: "Once you add outer joins or additional WHERE filters, mixing everything into one WHERE clause (implicit style) becomes error-prone; explicit ON clauses keep 'how do these tables relate' visually distinct from 'which rows do I want.'",
  },
  {
    q: "To list every employee's hours logged on every project (project name, employee name, hours), which two joins are chained together in the Wedgewood Pacific schema?",
    options: [
      "employee joined directly to project, with no assignment table needed",
      "project joined to assignment on project_id, then that result joined to employee on employee_number",
      "department joined to project, then project joined to employee",
      "assignment joined to itself twice",
    ],
    answer: 1,
    explain: "project and employee share no direct column, so assignment (the intersection table) bridges them: project JOIN assignment ON project_id, then JOIN employee ON employee_number.",
  },
  {
    q: "In a three-table join like project p JOIN assignment a ON p.project_id = a.project_id JOIN employee e ON a.employee_number = e.employee_number, what role does assignment play?",
    options: [
      "It is unnecessary and could be removed without changing the result",
      "It is the intersection (associative) table that makes the project-to-employee link possible, since neither table has a direct foreign key to the other",
      "It restricts the query to only completed projects",
      "It converts the join into a CROSS JOIN",
    ],
    answer: 1,
    explain: "project and employee have no shared column to join on directly; assignment holds foreign keys to both, so it's the bridge that makes a three-way join meaningful.",
  },
  {
    q: "SELECT d.department_name, e.first_name FROM department d LEFT OUTER JOIN employee e ON d.department_name = e.department_name; — what happens for a department with zero employees?",
    options: [
      "The department is silently omitted from the results",
      "The department still appears once, with e.first_name shown as NULL",
      "The query raises an error",
      "The department appears once per employee in the whole table",
    ],
    answer: 1,
    explain: "LEFT OUTER JOIN preserves every row from the left table (department) regardless of a match; unmatched right-side columns are padded with NULL rather than dropping the row.",
  },
  {
    q: "Walk through why LEFT OUTER JOIN + WHERE <right-side column> IS NULL finds 'projects with no assignments.' What does the WHERE clause actually filter out?",
    options: [
      "It filters out every row, always returning an empty set",
      "It discards the matched rows, keeping only the NULL-padded rows produced for projects that had no matching assignment",
      "It filters out projects, keeping only assignments",
      "It has no effect; the LEFT OUTER JOIN alone already returns unmatched projects only",
    ],
    answer: 1,
    explain: "The LEFT OUTER JOIN first produces a matched row per assignment plus a NULL-padded row for unmatched projects; filtering WHERE a.project_id IS NULL throws away every matched row, isolating just the projects with nothing to match.",
  },
  {
    q: "Which query correctly finds every employee who has never been assigned to a project?",
    options: [
      "SELECT e.* FROM employee e INNER JOIN assignment a ON e.employee_number = a.employee_number WHERE a.employee_number IS NULL;",
      "SELECT e.* FROM employee e LEFT OUTER JOIN assignment a ON e.employee_number = a.employee_number WHERE a.employee_number IS NULL;",
      "SELECT e.* FROM employee e RIGHT OUTER JOIN assignment a ON e.employee_number = a.employee_number WHERE e.employee_number IS NULL;",
      "SELECT e.* FROM employee e CROSS JOIN assignment a WHERE a.employee_number IS NULL;",
    ],
    answer: 1,
    explain: "An INNER JOIN would never produce NULL rows to filter on, since it only returns matches — the 'find unmatched' pattern requires LEFT OUTER JOIN followed by IS NULL on the right table's join column.",
  },
  {
    q: "SELECT e.first_name, a.project_id FROM assignment a RIGHT OUTER JOIN employee e ON a.employee_number = e.employee_number; is equivalent to which LEFT JOIN rewrite?",
    options: [
      "SELECT e.first_name, a.project_id FROM employee e LEFT OUTER JOIN assignment a ON e.employee_number = a.employee_number;",
      "SELECT e.first_name, a.project_id FROM assignment a LEFT OUTER JOIN employee e ON a.employee_number = e.employee_number;",
      "SELECT e.first_name, a.project_id FROM employee e INNER JOIN assignment a ON e.employee_number = a.employee_number;",
      "There is no equivalent LEFT JOIN rewrite; RIGHT OUTER JOIN is a fundamentally different operation",
    ],
    answer: 0,
    explain: "RIGHT OUTER JOIN keeps every row of the right-hand table; swapping the table order and using LEFT OUTER JOIN on the (now left-hand) employee table produces the identical result, which is why many style guides avoid RIGHT JOIN entirely.",
  },
  {
    q: "What result set does FULL OUTER JOIN represent, in Venn-diagram terms?",
    options: [
      "Only the overlapping (matched) region",
      "The union of left-only, matched, and right-only regions — everything from both tables",
      "Only rows unique to the left table",
      "An empty set unless every row matches",
    ],
    answer: 1,
    explain: "FULL OUTER JOIN is the union of what LEFT OUTER JOIN and RIGHT OUTER JOIN each return — every row from both sides, matched where possible and NULL-padded otherwise.",
  },
  {
    q: "How would you emulate FULL OUTER JOIN in MySQL, which lacks the keyword natively?",
    options: [
      "It cannot be emulated; MySQL simply cannot produce this result",
      "UNION of a LEFT JOIN and a RIGHT JOIN between the same two tables",
      "CROSS JOIN followed by a WHERE filter",
      "A single INNER JOIN with an OR condition",
    ],
    answer: 1,
    explain: "Combining a LEFT JOIN (all left rows, matched or not) with a RIGHT JOIN (all right rows, matched or not) via UNION reproduces the full set that FULL OUTER JOIN would return natively in Postgres or SQL Server.",
  },
  {
    q: "In a self join query using employee worker LEFT OUTER JOIN employee boss ON worker.supervisor = boss.employee_number, what do the aliases 'worker' and 'boss' represent?",
    options: [
      "Two entirely separate physical tables",
      "Two different roles the same employee table plays simultaneously in the query — one row acting as the subordinate, another acting as the supervisor",
      "A materialized view created just for this query",
      "worker holds current employees; boss holds former employees",
    ],
    answer: 1,
    explain: "Both aliases reference the same underlying employee table; aliasing lets the query treat one copy as 'the worker being described' and the other as 'that worker's supervisor,' even though both come from identical table structure.",
  },
  {
    q: "What would happen if you used INNER JOIN instead of LEFT OUTER JOIN in the employee self join modeling supervision, and Mary Jacobs (the CEO) has supervisor = NULL?",
    options: [
      "Mary Jacobs would still appear, with NULL supervisor columns",
      "Mary Jacobs would be silently excluded from the results, since NULL never satisfies the ON condition in an INNER JOIN",
      "The query would raise a runtime error",
      "Every other employee would also be excluded",
    ],
    answer: 1,
    explain: "INNER JOIN only returns rows where the ON condition evaluates true; since NULL = anything is never true, an employee with a NULL supervisor column simply drops out of an INNER JOIN self join.",
  },
  {
    q: "Which scenario is a genuine, practical use case for a CROSS JOIN?",
    options: [
      "Matching employees to their correct department",
      "Generating every combination of department and a fixed list of possible position titles, for planning purposes",
      "Finding departments with no employees",
      "Summing hours worked per project",
    ],
    answer: 1,
    explain: "CROSS JOIN's Cartesian product is genuinely useful for generating combinations (like a department-by-position planning grid), calendars, or seed/test data — situations where you want every possible pairing, not a matched relationship.",
  },
  {
    q: "A query accidentally lists FROM employee, department without any WHERE condition linking them. What is the likely, easy-to-miss result?",
    options: [
      "A syntax error is raised immediately",
      "An accidental CROSS JOIN — every employee paired with every department, multiplying the row count far beyond what was intended",
      "PostgreSQL automatically infers the correct join condition from the foreign key",
      "Only the first employee and first department are returned",
    ],
    answer: 1,
    explain: "Without a WHERE clause tying the two tables together, a comma-separated FROM list produces a full Cartesian product — a classic and often silent SQL bug, since it doesn't raise an error, just wildly inflates the row count.",
  },
  {
    q: "Why can't a subquery in a WHERE clause display columns from the table referenced inside the subquery itself?",
    options: [
      "Because subqueries are only allowed to reference numeric columns",
      "Because the outer query's SELECT list is limited to the outer (top) table's columns — the subquery exists only to help filter rows, not to expose extra columns",
      "Because PostgreSQL disables column access inside subqueries entirely",
      "This isn't true — a subquery can display columns from any table it touches",
    ],
    answer: 1,
    explain: "A subquery in WHERE only returns a value or set of values used for filtering; the outer SELECT's displayable columns are still limited to the outer table, unlike a JOIN which can display columns from every table in the FROM/JOIN chain.",
  },
  {
    q: "SELECT project_name, max_hours FROM project WHERE max_hours > (SELECT AVG(max_hours) FROM project); relies on what property of the subquery?",
    options: [
      "The subquery must return multiple rows for the comparison to work",
      "The subquery is guaranteed to return exactly one value (a scalar), so it can be compared directly with >",
      "The subquery must reference the outer query's columns to be valid",
      "AVG() cannot be used inside a subquery",
    ],
    answer: 1,
    explain: "AVG(max_hours) with no GROUP BY always produces a single number, making it a scalar subquery — safe to use directly with a comparison operator like >, <, or =.",
  },
  {
    q: "What is the key difference in what IN and EXISTS subqueries can be used for?",
    options: [
      "IN checks against a list of returned values; EXISTS only checks whether the subquery returns any row at all, ignoring its actual content",
      "EXISTS can only be used with numeric subqueries",
      "IN cannot be used with correlated subqueries under any circumstance",
      "They are entirely different SQL keywords with no functional similarity",
    ],
    answer: 0,
    explain: "IN evaluates whether the outer value matches any value in the subquery's result list; EXISTS doesn't care about the returned values, only whether the subquery produces at least one row — often letting the engine stop early once a match is found.",
  },
  {
    q: "Why is EXISTS sometimes faster than IN on large tables?",
    options: [
      "EXISTS always creates a temporary index automatically",
      "EXISTS can stop searching the moment it finds one matching row, whereas IN with a large returned value list may need to materialize the whole list first",
      "IN is deprecated and always falls back to a full table scan",
      "EXISTS only works on indexed columns, guaranteeing speed",
    ],
    answer: 1,
    explain: "EXISTS is a short-circuiting existence check — the database can quit as soon as one row is found — while IN traditionally needs to build out the comparison list from the subquery's full result set.",
  },
  {
    q: "SELECT department_name FROM department d WHERE EXISTS (SELECT 1 FROM project p WHERE p.department_name = d.department_name); — why is this called a correlated subquery?",
    options: [
      "Because it uses SELECT 1 instead of SELECT *",
      "Because the inner query references d.department_name, a column from the outer query, so it conceptually re-runs once per outer row",
      "Because it contains a JOIN inside the subquery",
      "Because EXISTS always implies correlation, even without an outer column reference",
    ],
    answer: 1,
    explain: "The subquery reaches out to d.department_name from the enclosing query — that outer-column reference is exactly what makes a subquery 'correlated,' evaluated per outer row rather than once overall.",
  },
  {
    q: "In SELECT 1 FROM project p WHERE p.department_name = d.department_name, why is SELECT 1 used instead of SELECT * or a specific column list?",
    options: [
      "SELECT 1 makes the query run in a special 'existence-only' mode required by EXISTS syntax",
      "It's a stylistic convention signaling that only row existence matters, not any particular column value — EXISTS ignores the SELECT list's actual content regardless",
      "SELECT 1 restricts the subquery to returning exactly one row total across the whole table",
      "SELECT * would cause a syntax error inside EXISTS",
    ],
    answer: 1,
    explain: "EXISTS only cares whether any row is returned, not what columns or values appear — SELECT 1 (or SELECT *) works identically; SELECT 1 is just a common convention that communicates 'we only care about existence' to readers.",
  },
  {
    q: "When would a join clearly be preferred over a subquery for a given query?",
    options: [
      "When you only need to check whether a related row exists, with no data from the other table displayed",
      "When you need to display columns from two or more tables side by side in the same result set",
      "When you want to filter rows using a single computed value like an average",
      "Subqueries are always preferred over joins in every scenario",
    ],
    answer: 1,
    explain: "Joins are the right tool when you need combined output from multiple tables at once; subqueries are best suited to existence checks or single-value comparisons where you don't need to display the other table's columns.",
  },
  {
    q: "Which CREATE TABLE fragment correctly enforces that a project's end_date can never fall before its start_date?",
    options: [
      "end_date DATE NOT NULL UNIQUE",
      "CONSTRAINT chk_dates CHECK (end_date >= start_date)",
      "FOREIGN KEY (end_date) REFERENCES start_date",
      "end_date DATE DEFAULT start_date",
    ],
    answer: 1,
    explain: "A CHECK constraint can compare two columns within the same row, so CHECK (end_date >= start_date) rejects any row where the date ordering is invalid — a good example of business-rule enforcement in the schema itself.",
  },
  {
    q: "What is the risk of writing INSERT INTO employee VALUES ('Grace', 'Lin', 'InfoSystems', ...); with no column list, relying purely on table column order?",
    options: [
      "There is no risk; PostgreSQL ignores column order for INSERT",
      "If the table's column order ever changes (e.g., a new column is added), the statement may silently insert values into the wrong columns or fail",
      "It always executes faster than a column-listed INSERT",
      "It automatically fills in NULL for every column",
    ],
    answer: 1,
    explain: "Omitting the column list ties the statement's correctness to the table's current physical column order — any future ALTER TABLE that adds or reorders columns can silently break or misalign such inserts.",
  },
  {
    q: "A project manager wants to see only projects with max_hours between 100 and 200 inclusive, sorted with the largest max_hours first. Which query is correct?",
    options: [
      "SELECT * FROM project WHERE max_hours BETWEEN 100 AND 200 ORDER BY max_hours;",
      "SELECT * FROM project WHERE max_hours BETWEEN 100 AND 200 ORDER BY max_hours DESC;",
      "SELECT * FROM project WHERE max_hours > 100 AND < 200 ORDER BY max_hours DESC;",
      "SELECT * FROM project ORDER BY max_hours DESC WHERE max_hours BETWEEN 100 AND 200;",
    ],
    answer: 1,
    explain: "BETWEEN 100 AND 200 is inclusive of both endpoints, and ORDER BY max_hours DESC sorts largest-first; WHERE must precede ORDER BY in clause order, ruling out the last option.",
  },
  {
    q: "What does SELECT department_name, COUNT(*) FROM employee GROUP BY department_name HAVING COUNT(*) > 1 ORDER BY COUNT(*) DESC; return, in plain terms?",
    options: [
      "Every department, sorted alphabetically",
      "Only departments with more than one employee, sorted from the most-staffed department down to the least",
      "Only departments with exactly one employee",
      "A single row showing the total employee count company-wide",
    ],
    answer: 1,
    explain: "GROUP BY buckets employees by department, HAVING COUNT(*) > 1 keeps only multi-employee departments, and ORDER BY COUNT(*) DESC lists them from most to fewest employees.",
  },
  {
    q: "Which of the following correctly lists the logical order in which SQL clauses are conceptually evaluated for a grouped, filtered, sorted query?",
    options: [
      "ORDER BY, WHERE, GROUP BY, HAVING, SELECT",
      "WHERE (filter rows), GROUP BY (form groups), HAVING (filter groups), then ORDER BY (sort final result)",
      "GROUP BY, ORDER BY, WHERE, HAVING",
      "HAVING, WHERE, GROUP BY, ORDER BY",
    ],
    answer: 1,
    explain: "Even though clauses are written SELECT...FROM...WHERE...GROUP BY...HAVING...ORDER BY, conceptual execution filters rows first (WHERE), forms groups (GROUP BY), filters those groups (HAVING), and sorts the final output last (ORDER BY).",
  },
  {
    q: "A query needs to show each employee's name along with the department's office_number, but only for employees in departments with more than 3 projects. Which combination of clauses is required?",
    options: [
      "A join between employee and department, plus a subquery or join involving project with GROUP BY/HAVING to count projects per department",
      "A single SELECT with no joins at all, since HAVING can filter employee rows directly",
      "CROSS JOIN employee and project, with no WHERE clause",
      "DISTINCT alone, with no join or aggregation needed",
    ],
    answer: 0,
    explain: "This requires combining employee/department (to show office_number) with a project-count condition per department, which needs either a join to project with GROUP BY/HAVING or a subquery counting projects — DISTINCT and joinless queries can't express the project-count filter.",
  },
  {
    q: "What is the outcome of running DELETE FROM assignment WHERE project_id = 1000; when project 1000 has five assignment rows?",
    options: [
      "Only the first matching row is deleted",
      "All five assignment rows for project 1000 are deleted, leaving other projects' assignments untouched",
      "The entire assignment table is emptied",
      "Nothing is deleted unless ORDER BY is specified",
    ],
    answer: 1,
    explain: "DELETE removes every row matching the WHERE condition — all rows where project_id = 1000 — while leaving rows for other project_id values completely unaffected.",
  },
];
