// ── Module 03 — SQL Fundamentals (38) ────────────────────────────────────────
QUESTIONS["03"] = [
  {
    q: "Which SQL statement category includes CREATE, ALTER, and DROP?",
    options: ["DML", "DDL", "DCL", "TCL"],
    answer: 1,
    explain: "Data Definition Language (DDL) statements create and modify database structures — tables, constraints, indexes. DML (INSERT/UPDATE/DELETE/SELECT) manipulates the data inside those structures.",
  },
  {
    q: "Which SQL statement category includes INSERT, UPDATE, and DELETE?",
    options: ["DDL", "DML", "DCL", "TCL"],
    answer: 1,
    explain: "Data Manipulation Language (DML) covers querying and changing data: SELECT, INSERT, UPDATE, DELETE.",
  },
  {
    q: "In a CREATE TABLE statement, what does a FOREIGN KEY constraint enforce?",
    options: [
      "The column must be unique across all rows",
      "The column's value must exist as a primary key value in the referenced table",
      "The column can never be NULL",
      "The column must be numeric",
    ],
    answer: 1,
    explain: "A foreign key (referential integrity) constraint requires that any non-null value in the FK column already exists as a primary key value in the table it references.",
  },
  {
    q: "What is the effect of a CHECK constraint such as CHECK (hours_worked >= 0)?",
    options: [
      "It automatically fills in 0 when no value is given",
      "It rejects any INSERT or UPDATE that would set hours_worked below 0",
      "It creates an index on hours_worked",
      "It makes hours_worked the primary key",
    ],
    answer: 1,
    explain: "CHECK constraints enforce a boolean condition on every row; any statement that would violate it is rejected by the database itself.",
  },
  {
    q: "Which PostgreSQL data type would you use for an exact, non-rounding monetary or hours value like 145.50?",
    options: ["INTEGER", "NUMERIC(p,s)", "BOOLEAN", "TEXT"],
    answer: 1,
    explain: "NUMERIC(p,s) stores exact fixed-point decimals — the right choice whenever rounding error is unacceptable, such as money or precise hour totals.",
  },
  {
    q: "In PostgreSQL, what does the SERIAL type do when used as a column type?",
    options: [
      "Stores a serialized JSON blob",
      "Auto-generates an incrementing integer, commonly used for surrogate primary keys",
      "Forces the column to always be NULL",
      "Stores a fixed-length string",
    ],
    answer: 1,
    explain: "SERIAL creates an auto-incrementing integer column, Postgres's equivalent to MySQL's AUTO_INCREMENT or SQL Server's IDENTITY(1,1).",
  },
  {
    q: "What is the MySQL equivalent of PostgreSQL's SERIAL for an auto-incrementing primary key?",
    options: ["AUTO_INCREMENT", "IDENTITY(1,1)", "SEQUENCE", "ROWID"],
    answer: 0,
    explain: "MySQL uses INT AUTO_INCREMENT; SQL Server uses INT IDENTITY(1,1); Postgres uses SERIAL or GENERATED ALWAYS AS IDENTITY.",
  },
  {
    q: "Which PostgreSQL type is best suited to store a flexible, semi-structured document alongside strict relational columns?",
    options: ["TEXT", "JSONB", "VARCHAR", "BOOLEAN"],
    answer: 1,
    explain: "JSONB stores JSON in a binary, indexable form, letting you query into document fields with operators like -> and ->> while keeping the rest of the table strictly relational.",
  },
  {
    q: "What does ALTER TABLE employee DROP COLUMN office_phone; do?",
    options: [
      "Sets every row's office_phone to NULL but keeps the column",
      "Removes the office_phone column and its data from the table structure entirely",
      "Renames the column to 'dropped_phone'",
      "Deletes every row in the table",
    ],
    answer: 1,
    explain: "DROP COLUMN permanently removes the column definition (and its stored data) from the table.",
  },
  {
    q: "What is the difference between DROP TABLE and TRUNCATE TABLE?",
    options: [
      "They are identical in every database",
      "DROP TABLE removes the structure and all data; TRUNCATE TABLE removes all rows but keeps the structure",
      "TRUNCATE TABLE removes the structure; DROP TABLE only removes rows",
      "DROP TABLE only works on empty tables",
    ],
    answer: 1,
    explain: "DROP TABLE deletes the table definition itself. TRUNCATE TABLE empties all rows but leaves the table (and its constraints/columns) intact for future use.",
  },
  {
    q: "In an INSERT statement, does the order of columns listed after the table name have to match the table's physical column order?",
    options: [
      "Yes, always",
      "No — it only has to match the order of the values supplied in VALUES",
      "Only for the primary key column",
      "Only in MySQL",
    ],
    answer: 1,
    explain: "The column list defines the mapping for that statement; as long as VALUES supplies data in the same order as the column list, the physical table order is irrelevant.",
  },
  {
    q: "What happens if you run DELETE FROM assignment; with no WHERE clause?",
    options: [
      "Nothing — SQL requires a WHERE clause on DELETE",
      "Every row in the assignment table is deleted",
      "Only the first row is deleted",
      "The table structure is dropped",
    ],
    answer: 1,
    explain: "DELETE without a WHERE clause is fully valid SQL and removes every row in the table. Always test the WHERE condition with a SELECT first.",
  },
  {
    q: "What does PostgreSQL's INSERT ... ON CONFLICT (key) DO UPDATE SET ... accomplish?",
    options: [
      "It always inserts a new row, ignoring duplicates",
      "It performs an 'upsert' — insert the row, or update it if a row with that key already exists",
      "It deletes the conflicting row",
      "It rolls back the entire transaction",
    ],
    answer: 1,
    explain: "ON CONFLICT DO UPDATE is Postgres's upsert syntax: on a key collision, it updates the existing row instead of failing or silently skipping.",
  },
  {
    q: "What is the MySQL equivalent of PostgreSQL's INSERT ... ON CONFLICT DO UPDATE?",
    options: ["MERGE INTO", "INSERT ... ON DUPLICATE KEY UPDATE", "UPSERT INTO", "REPLACE ONLY"],
    answer: 1,
    explain: "MySQL's idiomatic upsert syntax is INSERT ... ON DUPLICATE KEY UPDATE. SQL Server instead typically uses the more general MERGE statement.",
  },
  {
    q: "In the EXCLUDED pseudo-table used with Postgres's ON CONFLICT DO UPDATE, what does EXCLUDED refer to?",
    options: [
      "Rows that were deleted by the statement",
      "The row that would have been inserted, had there been no conflict",
      "Rows excluded by the WHERE clause",
      "A backup copy of the table",
    ],
    answer: 1,
    explain: "EXCLUDED represents the proposed new row's values — useful for writing DO UPDATE SET col = EXCLUDED.col to overwrite with the newly attempted values.",
  },
  {
    q: "Which clause comes first in the standard SQL query framework?",
    options: ["WHERE", "FROM", "SELECT (logically the framework is SELECT columns / FROM table / WHERE rows, written in that order)", "ORDER BY"],
    answer: 2,
    explain: "The written and conceptual order is SELECT (which columns), FROM (which table), WHERE (which rows) — even though execution internally evaluates FROM/WHERE before SELECT.",
  },
  {
    q: "What does SELECT DISTINCT department_name FROM employee; return?",
    options: [
      "Every employee's department, with duplicates",
      "Each distinct department name exactly once",
      "Only departments with more than one employee",
      "An error, because DISTINCT requires GROUP BY",
    ],
    answer: 1,
    explain: "DISTINCT removes duplicate rows from the result set, so each department name appears only once even if many employees share it.",
  },
  {
    q: "Why does WHERE office_phone = NULL never match any rows, even rows where office_phone is genuinely missing?",
    options: [
      "NULL must be written in lowercase",
      "NULL represents 'unknown/no value' and never equals anything, including another NULL, via the = operator",
      "= only works on numeric columns",
      "PostgreSQL disables NULL comparisons by default",
    ],
    answer: 1,
    explain: "NULL is not a value that can be equal to anything under three-valued logic. You must use IS NULL / IS NOT NULL to test for missing values.",
  },
  {
    q: "What does COALESCE(office_phone, 'No phone on file') return for a row where office_phone is NULL?",
    options: [
      "NULL",
      "'No phone on file'",
      "An empty string",
      "An error",
    ],
    answer: 1,
    explain: "COALESCE returns the first non-NULL argument in its list — a common way to supply a fallback display value for missing data.",
  },
  {
    q: "Which wildcard character in a LIKE pattern matches exactly one character?",
    options: ["%", "_", "*", "?"],
    answer: 1,
    explain: "In SQL LIKE patterns, % matches any sequence of zero or more characters, while _ matches exactly one character.",
  },
  {
    q: "What does WHERE position LIKE 'OPS_'; match?",
    options: [
      "'OPS' and anything starting with 'OPS'",
      "Exactly 'OPS1', 'OPS2', etc. — 'OPS' plus exactly one more character",
      "Only the literal string 'OPS_'",
      "Any string containing 'OPS' anywhere",
    ],
    answer: 1,
    explain: "The underscore wildcard matches exactly one character, so 'OPS_' matches four-character strings starting with 'OPS' — not 'OPS' alone, and not 'OPS10'.",
  },
  {
    q: "What is the key difference between LIKE and ILIKE in PostgreSQL?",
    options: [
      "ILIKE is faster but less accurate",
      "ILIKE performs a case-insensitive pattern match; LIKE is case-sensitive by default in Postgres",
      "LIKE only works on numeric columns",
      "There is no difference",
    ],
    answer: 1,
    explain: "PostgreSQL's LIKE is case-sensitive by default. ILIKE is a Postgres-specific extension that performs the same pattern match ignoring case.",
  },
  {
    q: "In PostgreSQL, how do you retrieve rows 6 through 10 (page 2 of a 5-per-page list), ordered by last_name?",
    options: [
      "SELECT * FROM employee ORDER BY last_name TOP 5 SKIP 5;",
      "SELECT * FROM employee ORDER BY last_name LIMIT 5 OFFSET 5;",
      "SELECT * FROM employee ORDER BY last_name PAGE 2;",
      "SELECT * FROM employee ORDER BY last_name ROWNUM BETWEEN 6 AND 10;",
    ],
    answer: 1,
    explain: "PostgreSQL (and MySQL) use LIMIT n OFFSET m to skip m rows and return the next n. SQL Server instead uses TOP or OFFSET...FETCH NEXT...ROWS ONLY.",
  },
  {
    q: "How would SQL Server retrieve the same 'first 5 rows' result that PostgreSQL gets from LIMIT 5?",
    options: [
      "SELECT TOP 5 * FROM employee ORDER BY last_name;",
      "SELECT * FROM employee LIMIT 5;",
      "SELECT * FROM employee FETCH 5;",
      "SELECT * FROM employee ROWCOUNT 5;",
    ],
    answer: 0,
    explain: "SQL Server historically uses SELECT TOP n; newer versions also support standard OFFSET ... FETCH NEXT ... ROWS ONLY for paging.",
  },
  {
    q: "An INNER JOIN between DEPARTMENT and EMPLOYEE will exclude which rows?",
    options: [
      "Nothing is ever excluded from an INNER JOIN",
      "Departments with no employees, and (if it could exist) employees with no matching department",
      "Only employees whose last name starts with a vowel",
      "Rows where department_name is alphabetically first",
    ],
    answer: 1,
    explain: "INNER JOIN keeps only rows that match on both sides of the join condition — unmatched rows on either side (department with zero employees, or an orphaned employee row) are dropped.",
  },
  {
    q: "In the Venn-diagram framing of joins, what does the overlapping (middle) region represent?",
    options: [
      "Rows found only in the left table",
      "Rows found only in the right table",
      "Rows that match the join condition on both tables — the INNER JOIN result",
      "Rows that were deleted",
    ],
    answer: 2,
    explain: "The overlap of the two circles is exactly the set of rows returned by an INNER JOIN — present in both tables and satisfying the join condition.",
  },
  {
    q: "To find every project with NO employees assigned to it, which pattern should you use?",
    options: [
      "INNER JOIN project to assignment, then WHERE hours_worked > 0",
      "LEFT OUTER JOIN project to assignment, then WHERE assignment.project_id IS NULL",
      "RIGHT OUTER JOIN assignment to project, then WHERE project_id = 0",
      "CROSS JOIN project and assignment",
    ],
    answer: 1,
    explain: "The 'find rows with no match' pattern: LEFT OUTER JOIN keeps every project (NULL-padding unmatched ones), then filtering for IS NULL on the right table's join column isolates the unmatched projects.",
  },
  {
    q: "Which JOIN type keeps every row from the right-hand table, padding unmatched left-side columns with NULL?",
    options: ["INNER JOIN", "LEFT OUTER JOIN", "RIGHT OUTER JOIN", "CROSS JOIN"],
    answer: 2,
    explain: "RIGHT OUTER JOIN preserves every row of the right table; unmatched rows get NULLs for the left table's columns.",
  },
  {
    q: "Which JOIN type returns every row from both tables, matched where possible and NULL-padded on either side otherwise?",
    options: ["INNER JOIN", "LEFT OUTER JOIN", "RIGHT OUTER JOIN", "FULL OUTER JOIN"],
    answer: 3,
    explain: "FULL OUTER JOIN is the union of LEFT and RIGHT OUTER JOIN results — every row from both sides appears, matched or NULL-padded.",
  },
  {
    q: "Why does MySQL require a UNION of a LEFT JOIN and a RIGHT JOIN to emulate a FULL OUTER JOIN?",
    options: [
      "MySQL has no JOIN support at all",
      "MySQL does not implement the FULL OUTER JOIN keyword natively",
      "MySQL only allows joins on primary keys",
      "UNION is required by the SQL standard for all joins",
    ],
    answer: 1,
    explain: "Unlike PostgreSQL and SQL Server, MySQL has no native FULL OUTER JOIN syntax, so it's commonly emulated with UNION of a LEFT JOIN and a RIGHT JOIN result.",
  },
  {
    q: "What is a 'self join' used for?",
    options: [
      "Joining two completely unrelated tables",
      "Joining a table to itself, typically to relate rows within the same table (e.g., employee to their own supervisor)",
      "A join that requires no ON clause",
      "A join that only works on a single-column table",
    ],
    answer: 1,
    explain: "A self join uses two aliases for the same table to compare rows against other rows in that table — the classic example is an employee/supervisor hierarchy stored in one EMPLOYEE table.",
  },
  {
    q: "In a self join modeling employee-supervisor relationships, why is LEFT OUTER JOIN preferred over INNER JOIN?",
    options: [
      "LEFT OUTER JOIN runs faster in every case",
      "INNER JOIN would drop the top-level employee (e.g., the CEO) who has no supervisor (NULL)",
      "LEFT OUTER JOIN is required by SQL syntax rules for self joins",
      "There's no difference for self joins",
    ],
    answer: 1,
    explain: "The CEO's supervisor column is NULL. An INNER JOIN would silently exclude that employee since NULL never matches in the ON clause; LEFT OUTER JOIN keeps them with NULL supervisor columns.",
  },
  {
    q: "What does a CROSS JOIN produce?",
    options: [
      "Only matching rows between two tables",
      "Every possible combination of rows from both tables (a Cartesian product)",
      "Rows that exist in one table but not the other",
      "An error unless an ON clause is supplied",
    ],
    answer: 1,
    explain: "CROSS JOIN pairs every row of one table with every row of the other, producing rows(A) × rows(B) results — no matching condition involved.",
  },
  {
    q: "What is the main structural difference between a subquery and a join, in terms of what columns can be displayed?",
    options: [
      "A subquery can display columns from any table involved; a join can only display columns from the outer table",
      "A join can display columns from any table involved; a subquery can only display columns from the outermost (top) table",
      "Both can always display columns from every table equally",
      "Neither can ever display more than one column",
    ],
    answer: 1,
    explain: "A subquery's outer query only ever sees the outer table's columns — the subquery is used purely to filter, not to add displayable columns. A join can select and display columns from every table in the FROM/JOIN chain.",
  },
  {
    q: "What is a correlated subquery?",
    options: [
      "A subquery that never references anything from the outer query",
      "A subquery that references a column from the outer query, effectively re-running once per outer row",
      "A subquery that must always use GROUP BY",
      "A subquery that can only appear in the FROM clause",
    ],
    answer: 1,
    explain: "A correlated subquery references a column from its enclosing (outer) query, so conceptually it's evaluated once per row of the outer query rather than once overall.",
  },
  {
    q: "What does COUNT(office_phone) count, as opposed to COUNT(*)?",
    options: [
      "The exact same thing as COUNT(*)",
      "The number of rows where office_phone IS NOT NULL",
      "The number of distinct phone numbers only",
      "Always zero",
    ],
    answer: 1,
    explain: "COUNT(column) counts only non-NULL values in that column, while COUNT(*) counts every row regardless of NULLs.",
  },
  {
    q: "In GROUP BY department_name, why can't you also SELECT first_name unless it's wrapped in an aggregate function?",
    options: [
      "SQL doesn't allow VARCHAR columns in SELECT",
      "For a department with multiple employees, SQL has no way to know which single first_name to display for that one summarized row",
      "first_name must always be the GROUP BY column",
      "This restriction only applies in MySQL",
    ],
    answer: 1,
    explain: "GROUP BY collapses many rows into one summary row per group; any non-aggregated column must be part of the grouping key, or SQL can't determine a single value to show.",
  },
  {
    q: "What is the difference between WHERE and HAVING?",
    options: [
      "They are interchangeable in every case",
      "WHERE filters individual rows before grouping; HAVING filters groups after aggregation",
      "HAVING filters rows before grouping; WHERE filters after",
      "WHERE can only be used with SELECT *",
    ],
    answer: 1,
    explain: "WHERE operates on raw rows prior to GROUP BY; HAVING operates on the aggregated groups afterward, and can reference aggregate functions like SUM() or COUNT() directly.",
  },
];
