// ── Module 01 — Getting Started (32) ─────────────────────────────────────
QUESTIONS["01"] = [
  {
    q: "What is the primary purpose of a database?",
    options: [
      "To make spreadsheets load faster",
      "To keep track of things — structured data about the people, objects, and events an organization cares about",
      "To replace all programming languages",
      "To store only images and video",
    ],
    answer: 1,
    explain: "A database exists to reliably keep track of things — customers, orders, employees — especially once more than one related theme needs to be tracked together.",
  },
  {
    q: "A spreadsheet has columns Child1, Child2, Child3 to store a customer's children. What is this pattern called?",
    options: [
      "A composite key",
      "A repeating group",
      "A surrogate key",
      "A functional dependency",
    ],
    answer: 1,
    explain: "Bolting on Child1, Child2, Child3 columns to hold a variable number of related values is a repeating group — a classic sign the data belongs in its own related table instead.",
  },
  {
    q: "Why is a repeating group a poor design choice?",
    options: [
      "It runs slower than a single column",
      "It caps how many values can be stored, wastes space for rows with fewer values, and can't be queried as a set",
      "SQL cannot read repeating groups at all",
      "It violates copyright law",
    ],
    answer: 1,
    explain: "A fixed number of repeating columns creates an arbitrary ceiling (what if there are more values than columns?), wastes space when there are fewer, and makes it hard to query 'all values' as a set.",
  },
  {
    q: "An update anomaly occurs when...",
    options: [
      "A row is deleted and unrelated data is lost with it",
      "The same fact is duplicated across multiple rows, and updating one copy but missing another creates inconsistent data",
      "A new row can't be inserted without unrelated data",
      "A table has too many columns",
    ],
    answer: 1,
    explain: "An update anomaly happens when redundant copies of the same fact can fall out of sync if only some copies are updated.",
  },
  {
    q: "An insertion anomaly occurs when...",
    options: [
      "You cannot add a new fact without also supplying unrelated or nonexistent data",
      "Two rows become identical",
      "A column stores the wrong data type",
      "A foreign key constraint is violated",
    ],
    answer: 0,
    explain: "Example: a new customer can't be entered until they make a payment, because every row in a combined table requires a payment amount.",
  },
  {
    q: "A deletion anomaly occurs when...",
    options: [
      "A row insert fails",
      "Removing one row unintentionally destroys an unrelated fact that happened to share that row",
      "A table is dropped entirely",
      "A primary key changes value",
    ],
    answer: 1,
    explain: "Example: deleting a customer's only payment record also erases the customer's name and phone number, even though the customer still exists.",
  },
  {
    q: "What is the underlying design flaw that causes update, insertion, and deletion anomalies?",
    options: [
      "Using too many indexes",
      "Mixing two or more themes into a single table/row",
      "Using VARCHAR instead of TEXT",
      "Not using a cloud provider",
    ],
    answer: 1,
    explain: "All three anomalies trace back to combining facts about more than one theme (e.g., customer info and payment info) on the same row.",
  },
  {
    q: "What is the relational-model fix for modification anomalies?",
    options: [
      "Add more repeating columns",
      "Split data into separate tables, one theme per table, related by shared key columns",
      "Store everything in one giant table with extra rows",
      "Disable referential integrity",
    ],
    answer: 1,
    explain: "Splitting a mixed-theme list into separate single-theme tables, connected by keys, eliminates the anomalies.",
  },
  {
    q: "In relational terminology, a row is also called a...",
    options: ["Field", "Attribute", "Record", "Schema"],
    answer: 2,
    explain: "A row (one occurrence of the theme) is also called a record. A column is also called a field.",
  },
  {
    q: "In relational terminology, a column is also called a...",
    options: ["Tuple", "Field", "Relation", "Domain"],
    answer: 1,
    explain: "A column, which stores a characteristic shared by all rows, is also called a field.",
  },
  {
    q: "What are the four components of a database system?",
    options: [
      "Tables, rows, columns, and keys",
      "Users, database application, DBMS, and database",
      "SQL, NoSQL, XML, and JSON",
      "Server, client, router, and firewall",
    ],
    answer: 1,
    explain: "A database system consists of users, a database application (forms/reports), a DBMS, and the database itself.",
  },
  {
    q: "What role does a database application play?",
    options: [
      "It physically stores the data on disk",
      "It provides forms, reports, and query screens so users can read, enter, and query data",
      "It is a synonym for the DBMS",
      "It replaces the need for a database",
    ],
    answer: 1,
    explain: "The database application is the user-facing layer — forms, reports, queries — that sits on top of the DBMS.",
  },
  {
    q: "What does it mean for a database to be 'self-describing'?",
    options: [
      "It writes its own documentation in English automatically",
      "A description of the database's own structure (metadata) is stored within the database itself",
      "It requires no DBMS",
      "It has no schema at all",
    ],
    answer: 1,
    explain: "Self-describing means the metadata — the structural description — lives inside the database alongside the data.",
  },
  {
    q: "What is metadata?",
    options: [
      "Backup copies of data",
      "Data about the structure of the database — table names, column names, types, constraints",
      "Encrypted data",
      "Data stored only in the cloud",
    ],
    answer: 1,
    explain: "Metadata describes the database's own structure, such as which columns exist and what types/constraints they have.",
  },
  {
    q: "In PostgreSQL, which system view commonly exposes metadata like column names and data types?",
    options: ["pg_data", "information_schema.columns", "sys.tables", "metadata.json"],
    answer: 1,
    explain: "information_schema.columns is a standard SQL view (supported by PostgreSQL) exposing column-level metadata.",
  },
  {
    q: "A referential integrity constraint ensures that...",
    options: [
      "Every column has a default value",
      "A value in one table's column matches an existing value in another table's referenced column",
      "All tables have the same number of rows",
      "Queries run within a time limit",
    ],
    answer: 1,
    explain: "Referential integrity guarantees a foreign key value corresponds to a real row in the referenced table (or is NULL, if optional).",
  },
  {
    q: "What typically enforces referential integrity in a relational database?",
    options: [
      "The web browser",
      "The DBMS, via constraints such as FOREIGN KEY",
      "The end user, by manual review",
      "The operating system",
    ],
    answer: 1,
    explain: "The DBMS enforces referential integrity through constraints (e.g., FOREIGN KEY ... REFERENCES) at insert/update time.",
  },
  {
    q: "How does a personal database system typically differ from an enterprise database system?",
    options: [
      "Personal systems always use SQL Server",
      "Personal systems serve one user with a few tables; enterprise systems serve thousands of concurrent users with hundreds of tables and millions of rows",
      "Enterprise systems never use referential integrity",
      "There is no meaningful difference",
    ],
    answer: 1,
    explain: "Personal database systems are small-scale and single-user; enterprise systems run 24/7 for large numbers of concurrent users across huge datasets.",
  },
  {
    q: "Which of these is most characteristic of an enterprise-class database system?",
    options: [
      "Runs on one laptop, used by one person",
      "Hundreds of tables, millions of rows, expected uptime 24/7",
      "Has no need for a DBMS",
      "Cannot use SQL",
    ],
    answer: 1,
    explain: "Enterprise systems are large-scale, highly concurrent, and expected to run continuously.",
  },
  {
    q: "Which database engine is a single embedded file with no separate server process?",
    options: ["Oracle", "SQL Server", "SQLite", "PostgreSQL"],
    answer: 2,
    explain: "SQLite stores an entire database as a single file and requires no separate server process, making it ideal for embedded and local use.",
  },
  {
    q: "Which database engine is most tightly integrated with the Microsoft/.NET ecosystem?",
    options: ["MySQL", "SQL Server", "SQLite", "MariaDB"],
    answer: 1,
    explain: "SQL Server integrates deeply with .NET, Power BI, Active Directory, and the broader Microsoft stack.",
  },
  {
    q: "Which is a community-driven fork of MySQL?",
    options: ["MariaDB", "SQLite", "Oracle", "PostgreSQL"],
    answer: 0,
    explain: "MariaDB began as a community fork of MySQL after Oracle's acquisition of MySQL.",
  },
  {
    q: "Which of these is NOT a stated reason this course uses PostgreSQL as its primary dialect?",
    options: [
      "It's free and open source",
      "It's rigorously standards-compliant",
      "It's the only engine that can run SELECT statements",
      "It's the default assumption of common data tooling like pandas and SQLAlchemy",
    ],
    answer: 2,
    explain: "All major relational engines run SELECT statements; that's not a distinguishing reason. PostgreSQL is chosen for being free, standards-compliant, feature-rich, and the ecosystem default.",
  },
  {
    q: "Which PostgreSQL data type is commonly cited as a modern strength for semi-structured data?",
    options: ["CHAR", "JSONB", "BLOB", "MONEY"],
    answer: 1,
    explain: "JSONB lets PostgreSQL store and efficiently query semi-structured JSON documents alongside relational data.",
  },
  {
    q: "In PostgreSQL, an auto-incrementing integer primary key is commonly declared using...",
    options: ["AUTO_INCREMENT", "IDENTITY(1,1)", "SERIAL", "ROWID"],
    answer: 2,
    explain: "PostgreSQL traditionally uses SERIAL (or the modern GENERATED ALWAYS AS IDENTITY) for auto-incrementing keys; AUTO_INCREMENT is MySQL, IDENTITY(1,1) is SQL Server.",
  },
  {
    q: "Which dialect uses AUTO_INCREMENT for auto-incrementing primary keys?",
    options: ["PostgreSQL", "MySQL/MariaDB", "SQL Server", "Oracle"],
    answer: 1,
    explain: "AUTO_INCREMENT is the MySQL/MariaDB syntax; PostgreSQL uses SERIAL, SQL Server uses IDENTITY.",
  },
  {
    q: "In a Web database application, what typically connects the browser's requests to SQL commands run against the DBMS?",
    options: [
      "A direct TCP connection from the browser to the database file",
      "An API (application programming interface), often served by backend code",
      "The web browser's built-in SQL engine",
      "A printer driver",
    ],
    answer: 1,
    explain: "The browser calls an API; server-side code translates the request into SQL, executes it against the DBMS, and returns results (often as JSON).",
  },
  {
    q: "OLTP databases are best described as optimized for...",
    options: [
      "Long-running historical trend analysis",
      "Fast, frequent, small transactions like inserting an order or updating a status",
      "Storing only images",
      "Running exclusively on personal computers",
    ],
    answer: 1,
    explain: "OLTP (Online Transaction Processing) systems handle real-time, small, frequent read/write operations.",
  },
  {
    q: "OLAP databases are best described as optimized for...",
    options: [
      "Recording individual checkout transactions",
      "Large, complex, mostly read-only analytical queries over historical data",
      "Real-time password validation",
      "Sending emails",
    ],
    answer: 1,
    explain: "OLAP (Online Analytical Processing) systems support complex aggregations and trend analysis, typically in a separate data warehouse.",
  },
  {
    q: "What does NoSQL generally mean?",
    options: [
      "A database that only supports SELECT, never INSERT",
      "A family of non-relational database engines (document, key-value, wide-column, graph) built for scale or flexible/unstructured data",
      "A stricter dialect of SQL",
      "A database that cannot be queried at all",
    ],
    answer: 1,
    explain: "NoSQL ('Not Only SQL') covers non-relational engines optimized for scale, flexible schemas, or specialized data shapes, like MongoDB (document) or Neo4j (graph).",
  },
  {
    q: "Which of the following is an example of Big Data–oriented technology mentioned in this course?",
    options: ["Microsoft Access", "ArangoDB (a NoSQL database)", "Excel", "CSV files"],
    answer: 1,
    explain: "ArangoDB is a NoSQL database used to store the kind of large, flexible datasets described as Big Data.",
  },
  {
    q: "Which of these is a major cloud provider offering managed relational database services?",
    options: ["ArangoDB", "Amazon Web Services (AWS)", "MariaDB Foundation", "SQLite"],
    answer: 1,
    explain: "AWS (along with Azure and Google Cloud Platform) offers managed relational database services such as RDS.",
  },
  {
    q: "What does a 'managed database service' in the cloud typically handle for you?",
    options: [
      "Writing your SQL queries automatically",
      "Backups, patching, replication, and scaling of the underlying server",
      "Designing your schema for you",
      "Nothing — you still manage the physical hardware",
    ],
    answer: 1,
    explain: "Managed services (e.g., AWS RDS, Azure SQL Database) handle operational tasks like backups and patching while you connect and write SQL exactly as you would against a self-hosted instance.",
  },
];
