// ── Module 08 — Advanced SQL (34) ────────────────────────────────────────────
QUESTIONS["08"] = [
  {
    q: "What does the ALTER TABLE statement allow you to do?",
    options: [
      "Modify the structure of an existing table — add, modify, or drop columns and constraints",
      "Only rename a table",
      "Only delete all rows from a table",
      "Create a brand-new database",
    ],
    answer: 0,
    explain: "ALTER TABLE modifies the structure of a table already created in the database, including adding/dropping columns and constraints.",
  },
  {
    q: "You need to add a NOT NULL column to a table that already has rows. What is the correct order of steps?",
    options: [
      "Add the column as NOT NULL directly; it will default new and existing rows to NULL automatically",
      "Add the column allowing NULLs, backfill every row with a value, then alter the column to enforce NOT NULL",
      "Drop the table and recreate it from scratch every time",
      "NOT NULL columns cannot ever be added to a table with existing rows",
    ],
    answer: 1,
    explain: "You must add the column as nullable first, update all existing rows with real values, and only then apply the NOT NULL constraint.",
  },
  {
    q: "Which clause is used to remove a column from an existing table?",
    options: ["REMOVE COLUMN", "DROP COLUMN", "DELETE COLUMN", "ALTER COLUMN REMOVE"],
    answer: 1,
    explain: "ALTER TABLE ... DROP COLUMN {ColumnName} removes a column from an existing table.",
  },
  {
    q: "Which clause is used to add a table-level CHECK or foreign key constraint to an existing table?",
    options: ["ADD CONSTRAINT", "NEW CONSTRAINT", "INSERT CONSTRAINT", "APPLY CONSTRAINT"],
    answer: 0,
    explain: "ALTER TABLE ... ADD CONSTRAINT {ConstraintName} {definition} adds a named constraint, whether CHECK, FOREIGN KEY, or otherwise.",
  },
  {
    q: "What problem does an upsert (MERGE-style) statement solve?",
    options: [
      "It permanently deletes duplicate rows",
      "It combines insert-or-update logic into a single atomic statement, avoiding a race condition between a separate SELECT-then-INSERT/UPDATE",
      "It creates a new index automatically",
      "It converts a table into a view",
    ],
    answer: 1,
    explain: "Checking for existence and then issuing a separate INSERT or UPDATE is a race condition under concurrent access; upsert statements do both in one atomic operation.",
  },
  {
    q: "In PostgreSQL, which clause implements upsert behavior on INSERT?",
    options: ["ON DUPLICATE KEY UPDATE", "ON CONFLICT ... DO UPDATE", "MERGE INTO", "WITH ROLLUP"],
    answer: 1,
    explain: "PostgreSQL uses INSERT ... ON CONFLICT (key) DO UPDATE SET ... to perform an upsert.",
  },
  {
    q: "In a PostgreSQL ON CONFLICT ... DO UPDATE clause, what does the keyword EXCLUDED refer to?",
    options: [
      "Rows that were skipped due to a WHERE clause",
      "The row values that would have been inserted, usable in the DO UPDATE SET clause",
      "A synonym for NULL",
      "Rows excluded from a set operator like EXCEPT",
    ],
    answer: 1,
    explain: "EXCLUDED represents the proposed new row's values — the ones that would have been inserted had there been no conflict.",
  },
  {
    q: "Which SQL dialect uses ON DUPLICATE KEY UPDATE for upserts, and does NOT support a standard MERGE statement?",
    options: ["PostgreSQL", "Oracle", "MySQL", "SQL Server"],
    answer: 2,
    explain: "MySQL has no MERGE statement; ON DUPLICATE KEY UPDATE is its closest equivalent, requiring a unique/primary key to detect conflicts.",
  },
  {
    q: "Which two database products support a standard MERGE statement (combining INSERT and UPDATE logic driven by a source table or query)?",
    options: ["MySQL and SQLite", "SQL Server and Oracle", "MongoDB and Redis", "PostgreSQL and MySQL"],
    answer: 1,
    explain: "Microsoft SQL Server and Oracle Database both support the standard MERGE statement; MySQL does not.",
  },
  {
    q: "What is an SQL view?",
    options: [
      "A physical copy of a table's data, refreshed nightly",
      "A virtual table with no data of its own, built from a stored SELECT statement",
      "A type of index used to speed up joins",
      "A backup mechanism for disaster recovery",
    ],
    answer: 1,
    explain: "A view stores no data itself — it's a saved SELECT statement that runs every time the view is queried, presented as if it were a table.",
  },
  {
    q: "Which of the following is NOT typically allowed inside the SELECT statement used to define a view?",
    options: ["A WHERE clause", "A JOIN", "An ORDER BY clause", "Column aliases"],
    answer: 2,
    explain: "Standard SQL doesn't allow ORDER BY inside a view's defining query — sort order must be applied by the query that later selects from the view.",
  },
  {
    q: "A view built from a single table with no aggregation or DISTINCT is generally...",
    options: [
      "Never queryable",
      "Updatable — INSERT/UPDATE/DELETE through it are translated onto the underlying table",
      "Automatically materialized permanently",
      "Only usable in PostgreSQL, not any other dialect",
    ],
    answer: 1,
    explain: "Simple single-table views without aggregation are usually updatable; multi-table joins or aggregated views generally are not directly updatable.",
  },
  {
    q: "What is the main problem with using a plain INNER JOIN between PROJECT and ASSIGNMENT when a brand-new project has no assignments yet?",
    options: [
      "It causes a syntax error",
      "The new project silently disappears from the result set because there's nothing to match on the right side",
      "It duplicates the new project's row many times",
      "It automatically inserts a placeholder assignment row",
    ],
    answer: 1,
    explain: "An inner join only returns rows with a match on both sides, so a project with zero matching assignment rows is dropped entirely from the output.",
  },
  {
    q: "Which join keeps every row from the left-hand table, filling unmatched right-hand columns with NULL?",
    options: ["INNER JOIN", "LEFT JOIN", "CROSS JOIN", "SELF JOIN"],
    answer: 1,
    explain: "LEFT JOIN preserves every row of the left table even when there's no match on the right, showing NULLs in place of unmatched right-side columns.",
  },
  {
    q: "What is an 'anti-join' typically used for?",
    options: [
      "Finding rows that DO match between two tables",
      "Finding rows in one table that have NO corresponding match in another (e.g., via NOT EXISTS)",
      "Deleting all rows from a joined result",
      "Sorting a joined result in reverse order",
    ],
    answer: 1,
    explain: "An anti-join, typically written with NOT EXISTS or a LEFT JOIN ... WHERE right.key IS NULL, finds rows in one table with no match in another.",
  },
  {
    q: "What makes a subquery 'correlated' rather than a regular (uncorrelated) subquery?",
    options: [
      "It uses a UNION instead of a JOIN",
      "It references a column from the outer query, effectively re-evaluating once per outer row",
      "It must always use EXISTS",
      "It can only be written against views, never base tables",
    ],
    answer: 1,
    explain: "A correlated subquery references the outer query's current row, so conceptually it re-runs for each row processed by the outer query.",
  },
  {
    q: "What does EXISTS test for in a correlated subquery?",
    options: [
      "The specific values returned by the subquery",
      "Only whether the subquery returns any rows at all",
      "Whether the subquery contains a syntax error",
      "Whether the outer table is empty",
    ],
    answer: 1,
    explain: "EXISTS/NOT EXISTS only check for the presence or absence of rows returned by the subquery — the actual values returned are irrelevant.",
  },
  {
    q: "In a recursive relationship like 'employee supervises employee', how is the relationship represented in the table design?",
    options: [
      "A separate SUPERVISOR table is always required",
      "A foreign key column in the EMPLOYEE table references EMPLOYEE's own primary key",
      "It cannot be represented in a relational database",
      "It requires a NoSQL graph database",
    ],
    answer: 1,
    explain: "A recursive (unary) relationship uses a foreign key that references the same table it lives in — e.g., supervisor_id referencing employee_number in the same EMPLOYEE table.",
  },
  {
    q: "What SQL construct is required to list every employee alongside their supervisor's name, both coming from the same EMPLOYEE table?",
    options: [
      "A UNION of two separate queries",
      "A self-join — the table joined to itself using two different aliases",
      "A CROSS JOIN with a dimension table",
      "A CHECK constraint",
    ],
    answer: 1,
    explain: "A self-join joins a table to itself, distinguished by aliases (e.g., e and s), letting you retrieve related rows from the same table.",
  },
  {
    q: "Why does a fixed-depth chain of self-joins fail for exploring an entire, arbitrarily deep management hierarchy?",
    options: [
      "Self-joins are not supported by any SQL dialect",
      "It only reaches as many levels as you explicitly wrote joins for — it can't adapt to hierarchies of unknown depth",
      "Self-joins always return zero rows for hierarchical data",
      "PostgreSQL disallows more than two self-joins",
    ],
    answer: 1,
    explain: "Stacking a fixed number of self-joins only reaches a fixed depth; a recursive CTE (WITH RECURSIVE) is needed to walk a hierarchy of unknown or variable depth.",
  },
  {
    q: "What are the two parts of a WITH RECURSIVE common table expression?",
    options: [
      "A CHECK constraint and a trigger",
      "An anchor member (starting point) and a recursive member (references the CTE itself)",
      "A SELECT and a DELETE",
      "A view and a materialized view",
    ],
    answer: 1,
    explain: "Every recursive CTE has a non-recursive anchor member that starts the process and a recursive member that repeatedly references the CTE's own growing result.",
  },
  {
    q: "In a recursive CTE walking a hierarchy, what stops the recursion from continuing forever?",
    options: [
      "The database engine always stops after exactly one iteration",
      "The engine stops once an iteration of the recursive member produces zero new rows (plus any explicit guard you add)",
      "Recursive CTEs run for a fixed, hardcoded 10 iterations always",
      "Recursion never actually stops; it must be manually cancelled",
    ],
    answer: 1,
    explain: "The recursive member re-runs until it produces no new rows; adding an explicit depth guard (e.g., WHERE level < 20) protects against cyclical/bad data causing infinite loops.",
  },
  {
    q: "Which SQL Server clause explicitly limits how many levels a recursive CTE can recurse?",
    options: ["MAXRECURSION", "LIMIT RECURSION", "STOP AFTER", "RECURSE_LIMIT"],
    answer: 0,
    explain: "SQL Server supports OPTION (MAXRECURSION n) to cap recursive CTE depth; PostgreSQL has no equivalent session setting and relies on an explicit WHERE guard instead.",
  },
  {
    q: "What must be true of two SELECT statements combined with a set operator like UNION or INTERSECT?",
    options: [
      "They must query the exact same table",
      "They must return the same number of columns, in the same order, with compatible data types",
      "They must both use GROUP BY",
      "They must both include an ORDER BY clause",
    ],
    answer: 1,
    explain: "Set operators require column-count, column-order, and data-type compatibility between the combined queries' result sets.",
  },
  {
    q: "What is the practical difference between UNION and UNION ALL?",
    options: [
      "UNION ALL requires fewer columns than UNION",
      "UNION removes duplicate rows from the combined result; UNION ALL keeps every row, including duplicates",
      "UNION can only combine two queries; UNION ALL can combine any number",
      "There is no difference — they are aliases for the same operator",
    ],
    answer: 1,
    explain: "UNION performs a deduplication pass across the combined results; UNION ALL skips that pass, keeping duplicates and running faster.",
  },
  {
    q: "Which set operator returns only rows that appear in both of two result sets?",
    options: ["UNION", "UNION ALL", "INTERSECT", "EXCEPT"],
    answer: 2,
    explain: "INTERSECT returns only the rows common to both queries — equivalent to a logical AND between the two sets.",
  },
  {
    q: "Which set operator returns rows from the first query that do NOT appear in the second?",
    options: ["INTERSECT", "EXCEPT", "UNION", "CROSS JOIN"],
    answer: 1,
    explain: "EXCEPT (MINUS in Oracle) returns the rows present in the first query's result but absent from the second — a set difference.",
  },
  {
    q: "Which version of MySQL first added support for the INTERSECT and EXCEPT set operators?",
    options: ["MySQL 5.7", "MySQL 8.0.0", "MySQL 8.0.31", "MySQL has never supported them"],
    answer: 2,
    explain: "MySQL did not support INTERSECT or EXCEPT until version 8.0.31 (released October 2022) — earlier versions required workarounds using JOIN/EXISTS/NOT EXISTS.",
  },
  {
    q: "What keyword does Oracle use in place of the standard EXCEPT operator?",
    options: ["MINUS", "DIFF", "SUBTRACT", "NOT UNION"],
    answer: 0,
    explain: "Oracle uses MINUS for set difference; the logic is identical to the standard EXCEPT operator used by PostgreSQL and SQL Server.",
  },
  {
    q: "A window function's OVER (PARTITION BY ... ORDER BY ...) clause is most similar to which other SQL clause, except that it doesn't collapse rows into one per group?",
    options: ["WHERE", "GROUP BY", "HAVING", "ORDER BY alone"],
    answer: 1,
    explain: "PARTITION BY defines groups the same way GROUP BY does, but every row of the input remains in the output instead of being collapsed into one row per group.",
  },
  {
    q: "Given three employees tied for the highest hours in a department, how do RANK() and DENSE_RANK() differ in the rank assigned to the row that comes after the tie?",
    options: [
      "They always behave identically",
      "RANK() skips ranks after a tie (e.g., 1, 1, 1, 4); DENSE_RANK() does not skip (e.g., 1, 1, 1, 2)",
      "DENSE_RANK() skips ranks; RANK() never does",
      "Both assign a unique, arbitrary number to every row regardless of ties",
    ],
    answer: 1,
    explain: "RANK() leaves gaps in the ranking sequence after ties (matching the count of tied rows); DENSE_RANK() assigns the next consecutive rank with no gap.",
  },
  {
    q: "Which window function looks backward to a previous row within the same ordered partition?",
    options: ["LEAD()", "LAG()", "RANK()", "ROW_NUMBER()"],
    answer: 1,
    explain: "LAG() retrieves a value from an earlier row in the window (e.g., the prior period), while LEAD() retrieves a value from a later row.",
  },
  {
    q: "How is a running total typically built with a window function?",
    options: [
      "SUM() OVER (ORDER BY date_column) with no PARTITION BY narrowing the window, so each row's window is 'everything up to and including this row'",
      "COUNT(*) OVER (PARTITION BY date_column)",
      "AVG() with a HAVING clause",
      "Running totals cannot be computed with window functions",
    ],
    answer: 0,
    explain: "Ordering without a narrowing PARTITION BY makes each row's frame include all prior rows plus itself, producing a cumulative/running total.",
  },
  {
    q: "In MySQL, why must a stored function's body be wrapped with a temporary DELIMITER change (e.g., DELIMITER $$)?",
    options: [
      "MySQL requires all functions to be written in Java",
      "MySQL's default statement terminator (;) would otherwise end the function body before it's complete",
      "DELIMITER is required only for views, not functions",
      "It has no real purpose and is purely stylistic",
    ],
    answer: 1,
    explain: "Because a function body itself contains semicolons ending its internal statements, MySQL requires temporarily switching the statement delimiter so the CREATE FUNCTION statement isn't cut off early.",
  },
];
