// ── Module 05 — Database Design & Normalization (35) ────────────────────────
QUESTIONS["05"] = [
  {
    q: "In a 1:N relationship between DEPARTMENT and EMPLOYEE, which table receives the foreign key?",
    options: [
      "DEPARTMENT, referencing EMPLOYEE",
      "EMPLOYEE, referencing DEPARTMENT",
      "Both tables reference each other",
      "Neither — an intersection table is required",
    ],
    answer: 1,
    explain: "In a 1:N relationship the foreign key always goes on the 'many' side. EMPLOYEE (the child/many side) gets a department_id column referencing DEPARTMENT (the parent/one side).",
  },
  {
    q: "What is required to properly represent an N:M relationship between PROJECT and EMPLOYEE?",
    options: [
      "A foreign key in PROJECT only",
      "A foreign key in EMPLOYEE only",
      "A new intersection table with a composite primary key from both parents",
      "Merging PROJECT and EMPLOYEE into one table",
    ],
    answer: 2,
    explain: "N:M relationships cannot be represented with a single foreign key in either table. A new intersection (associative) table is created, with a composite primary key made of both parents' keys.",
  },
  {
    q: "What is a weak, ID-dependent entity?",
    options: [
      "An entity with no attributes",
      "An entity whose primary key must include its parent's primary key because it has no independent identity",
      "An entity that is never referenced by a foreign key",
      "An entity that only exists in a data warehouse",
    ],
    answer: 1,
    explain: "A weak, ID-dependent entity (like a LOG entry tied to a CHARTER) cannot be uniquely identified without its parent. Its primary key includes the parent's key plus a discriminator unique only within that parent.",
  },
  {
    q: "For a strict 1:1 relationship between CUSTOMER and CONTACT, what constraint (beyond the foreign key) enforces 'at most one contact per customer'?",
    options: [
      "NOT NULL",
      "CHECK",
      "UNIQUE on the foreign key column",
      "A trigger is always required",
    ],
    answer: 2,
    explain: "A plain foreign key alone allows many child rows per parent (a 1:N relationship). Adding UNIQUE to the foreign key column restricts it to at most one child row per parent, making it truly 1:1.",
  },
  {
    q: "A table has columns item1, item2, item3 to store a variable number of order items. What does this violate?",
    options: [
      "2NF (partial dependency)",
      "3NF (transitive dependency)",
      "1NF (repeating groups / non-atomic design)",
      "BCNF (overlapping candidate keys)",
    ],
    answer: 2,
    explain: "Repeating groups crammed into numbered columns (item1, item2, item3...) violate First Normal Form. The fix is a separate table with one row per item.",
  },
  {
    q: "A table SHIPMENT(shipment_id, boat_reg_number, boat_name, ship_date) has composite key (shipment_id, boat_reg_number), and boat_name depends only on boat_reg_number. What is this called?",
    options: [
      "A transitive dependency (3NF violation)",
      "A partial dependency (2NF violation)",
      "A repeating group (1NF violation)",
      "A determinant that is not a candidate key (BCNF violation)",
    ],
    answer: 1,
    explain: "boat_name depends on only part of the composite key (boat_reg_number), not the whole key (shipment_id, boat_reg_number). This partial dependency is a 2NF violation.",
  },
  {
    q: "A table CHARTER(charter_id, customer_id, customer_name) has customer_name depending on customer_id, which itself is not the primary key. What is this called?",
    options: [
      "A partial dependency (2NF violation)",
      "A transitive dependency (3NF violation)",
      "A multivalued dependency",
      "A repeating group (1NF violation)",
    ],
    answer: 1,
    explain: "customer_name depends on customer_id (a non-key column), not directly on the primary key charter_id. A non-key column depending on another non-key column is a transitive dependency — a 3NF violation.",
  },
  {
    q: "What is required for a table to satisfy Boyce-Codd Normal Form (BCNF)?",
    options: [
      "Every column must be nullable",
      "Every determinant in the table must be a candidate key",
      "The table must have at least two candidate keys",
      "Every non-key column must be numeric",
    ],
    answer: 1,
    explain: "BCNF requires that every determinant (a column or set of columns that functionally determines another column) be a candidate key. Most 3NF tables already satisfy this; violations are rare and involve overlapping composite keys.",
  },
  {
    q: "Why might a company deliberately denormalize a reporting table?",
    options: [
      "To eliminate the need for primary keys",
      "To trade some anomaly risk for faster reads by avoiding repeated joins",
      "Because normalized tables cannot be queried with SELECT",
      "To make the schema harder to understand on purpose",
    ],
    answer: 1,
    explain: "Denormalization duplicates or merges data to reduce the number of joins a query needs, improving read performance — a deliberate trade of some anomaly risk for speed, typically only done in copies that are not the sole system of record.",
  },
  {
    q: "In a recursive (unary) 1:N relationship like EMPLOYEE 'supervises' EMPLOYEE, where does the foreign key point?",
    options: [
      "To a separate SUPERVISOR table",
      "Back to the same EMPLOYEE table's own primary key",
      "It cannot be represented with a foreign key at all",
      "To the DEPARTMENT table",
    ],
    answer: 1,
    explain: "A recursive relationship connects instances of the same entity to each other. The foreign key (e.g., supervisor_id) references the table's own primary key (employee_number), not a different table.",
  },
  {
    q: "Why must a query listing every employee alongside their supervisor's name use a LEFT JOIN rather than an inner join?",
    options: [
      "LEFT JOIN is always faster",
      "Inner joins do not support table aliases",
      "An employee with no supervisor (NULL) would be dropped by an inner join",
      "LEFT JOIN is required whenever a self-join is used, regardless of nulls",
    ],
    answer: 2,
    explain: "The top-level employee (e.g., the president) has supervisor_id = NULL. An inner join has nothing to match on the right side for that row and would silently exclude it. LEFT JOIN preserves it with NULL supervisor columns.",
  },
  {
    q: "What SQL alias pattern is used to self-join a table like EMPLOYEE to itself?",
    options: [
      "You cannot join a table to itself in SQL",
      "Two different aliases for the same table, e.g., FROM employee e JOIN employee s ON ...",
      "You must first copy the table into a temp table",
      "Use UNION instead of JOIN",
    ],
    answer: 1,
    explain: "A self-join references the same table twice in the FROM clause with two different aliases (e.g., e and s), letting the query treat 'employee row' and 'supervisor row' as if they were different tables.",
  },
  {
    q: "What does WITH RECURSIVE let you do that a fixed self-join cannot?",
    options: [
      "Join more than two tables at once",
      "Walk a hierarchy of arbitrary depth without knowing how many levels exist ahead of time",
      "Avoid using a WHERE clause",
      "Query multiple databases simultaneously",
    ],
    answer: 1,
    explain: "A self-join walks exactly one level per join, requiring you to know the depth in advance. WITH RECURSIVE repeatedly applies the same join step until no new matching rows are produced, handling any depth automatically.",
  },
  {
    q: "In the anchor/recursive structure of a recursive CTE, what stops the recursion?",
    options: [
      "A LIMIT clause is always required",
      "The recursive step stops producing new matching rows (e.g., reaching a NULL supervisor_id)",
      "PostgreSQL automatically halts after 10 iterations",
      "You must manually call ROLLBACK",
    ],
    answer: 1,
    explain: "The recursive step keeps joining back to find the next level. It naturally terminates when a row's join condition has nothing left to match — e.g., when supervisor_id IS NULL, ending the chain.",
  },
  {
    q: "What ON DELETE action is generally most appropriate for the two foreign keys in an ASSIGNMENT intersection table?",
    options: [
      "RESTRICT on both",
      "SET NULL on both",
      "CASCADE on both, since an assignment row is meaningless without both parents",
      "No ON DELETE action should ever be specified",
    ],
    answer: 2,
    explain: "If a PROJECT or EMPLOYEE row is deleted, the intersection row connecting them no longer represents anything meaningful, so CASCADE deletion is the natural choice for both foreign keys.",
  },
  {
    q: "For a weak entity like LOG(charter_id, entry_number) tied to CHARTER, what ON DELETE behavior on the charter_id foreign key makes the most sense?",
    options: [
      "RESTRICT, to prevent charters from ever being deleted",
      "SET NULL, so log entries survive without a charter",
      "CASCADE, since a log entry cannot exist without its parent charter",
      "SET DEFAULT to a placeholder charter",
    ],
    answer: 2,
    explain: "Weak, ID-dependent entities have no independent existence — a log entry only makes sense in the context of its charter. CASCADE ensures log rows are removed automatically when the parent charter is deleted.",
  },
  {
    q: "Why is using DepartmentName (a text value) as a primary key in DEPARTMENT considered a weaker design than adding a surrogate department_id?",
    options: [
      "Text columns cannot be indexed",
      "Renaming a department would require updating every foreign key referencing the old text value everywhere",
      "PostgreSQL does not allow text primary keys",
      "Text primary keys cannot be used in JOIN clauses",
    ],
    answer: 1,
    explain: "When a natural, changeable value like a name is the primary key, every child table's foreign key stores that same text. Renaming the department means updating it everywhere it's referenced, unlike a stable surrogate integer key.",
  },
  {
    q: "What SQL constraint would you add to an intersection table like employee_collaboration(employee_number, collaborator_number) to prevent an employee from 'collaborating' with themselves?",
    options: [
      "UNIQUE (employee_number)",
      "CHECK (employee_number <> collaborator_number)",
      "NOT NULL on both columns only",
      "FOREIGN KEY referencing a third table",
    ],
    answer: 1,
    explain: "A CHECK constraint comparing the two foreign key columns for inequality prevents a row where an employee references themselves as their own collaborator.",
  },
  {
    q: "PostgreSQL foreign key actions include CASCADE, RESTRICT, SET NULL, and which other option?",
    options: [
      "SET DEFAULT",
      "DELETE ALL",
      "IGNORE",
      "ROLLBACK",
    ],
    answer: 0,
    explain: "PostgreSQL supports CASCADE, RESTRICT, SET NULL, SET DEFAULT, and the implicit NO ACTION as referential actions for ON UPDATE / ON DELETE clauses.",
  },
  {
    q: "Which of the following is true about foreign key enforcement in SQLite?",
    options: [
      "SQLite does not support the FOREIGN KEY syntax at all",
      "Foreign key enforcement must be explicitly turned on per connection with PRAGMA foreign_keys = ON",
      "SQLite enforces foreign keys by default just like PostgreSQL",
      "SQLite only supports foreign keys in in-memory databases",
    ],
    answer: 1,
    explain: "SQLite accepts FOREIGN KEY syntax but does not enforce it by default — each connection must run PRAGMA foreign_keys = ON to activate actual enforcement, unlike PostgreSQL, MySQL/InnoDB, and SQL Server.",
  },
  {
    q: "A CHARTER_BOOKING table stores num_days, which is calculated from departure_date and return_date. What normalization concern does this raise?",
    options: [
      "It is a repeating group and violates 1NF",
      "It is a derived/computed value that could disagree with the dates it summarizes",
      "It requires a composite primary key",
      "It cannot be represented as an INTEGER column",
    ],
    answer: 1,
    explain: "Storing a value that can be derived from other columns (num_days from departure/return dates) risks the two disagreeing after an update to one but not the other — a design smell normalization theory flags even outside a strict normal-form violation.",
  },
  {
    q: "Which of these column sets, if functionally dependent as boat_type -> skipper_name where boat_type is not a candidate key, would violate BCNF even in an otherwise-3NF table?",
    options: [
      "boat_reg_number -> boat_name",
      "boat_type -> skipper_name, when boat_reg_number (not boat_type) is the real candidate key",
      "customer_id -> customer_name",
      "charter_id -> departure_date",
    ],
    answer: 1,
    explain: "If boat_type determines skipper_name but boat_type itself isn't a candidate key of the table, that's a determinant that isn't a candidate key — the defining BCNF violation, even when the table already satisfies 3NF.",
  },
  {
    q: "What is the correct relational transformation for a 1:1 relationship where either side could reasonably hold the foreign key?",
    options: [
      "It must always go on the entity created first",
      "It is a design choice — pick whichever side is more natural for queries, or merge the tables",
      "1:1 relationships cannot be represented relationally",
      "Both tables must hold a copy of the same primary key value redundantly",
    ],
    answer: 1,
    explain: "Unlike 1:N (where the many side is forced), a 1:1 relationship's foreign key placement is a judgment call based on query patterns, or the two entities can be merged into a single table entirely.",
  },
  {
    q: "In the WP-style schema, why must the WHERE clause read DEPARTMENT.DepartmentName = EMPLOYEE.DepartmentName instead of just DepartmentName = DepartmentName when joining two tables that share a column name?",
    options: [
      "SQL requires all comparisons to use functions",
      "The column name alone is ambiguous when it exists in both tables being joined",
      "PostgreSQL does not allow WHERE clauses in multi-table queries",
      "DepartmentName must always be cast to text first",
    ],
    answer: 1,
    explain: "When both tables in a FROM clause have a column of the same name, the DBMS cannot tell which one you mean; qualifying with the table name (or alias) resolves the ambiguity.",
  },
  {
    q: "Which of the following is the best test for whether a foreign key belongs on the 'many' side of a 1:N relationship?",
    options: [
      "Whichever table has more total rows",
      "Whichever table has a shorter name",
      "Ask: can this entity have more than one of the other entity? The 'yes' side is the many/child side",
      "Whichever table was created first in the CREATE TABLE script",
    ],
    answer: 2,
    explain: "The heuristic is about business meaning, not row counts or naming: an employee belongs to exactly one department, but a department has many employees, so employee is the many/child side that holds the foreign key.",
  },
  {
    q: "What happens to a row's normal form classification if it has a NULL foreign key value (e.g., a project with no sponsoring department)?",
    options: [
      "It automatically violates 1NF",
      "Normal form is about functional dependencies among columns, not about NULLs in foreign keys — nullable FKs are a separate design decision",
      "The table must be split further to accommodate NULLs",
      "NULL foreign keys are illegal in PostgreSQL",
    ],
    answer: 1,
    explain: "Normalization addresses functional dependency structure among columns, independent of whether an optional foreign key is NULL. A nullable department_id on PROJECT is a valid, separate design choice (often paired with ON DELETE SET NULL).",
  },
  {
    q: "Why is it a bad idea to name a foreign key column identically to a candidate primary key name across differently-purposed tables, even though SQL permits it?",
    options: [
      "SQL does not permit it at all",
      "It works, but in large schemas with many tables it becomes hard to tell at a glance which occurrences are the PK and which are FKs",
      "It causes an automatic CASCADE on every DELETE",
      "It prevents the column from being indexed",
    ],
    answer: 1,
    explain: "As shown in the WP database discussion, using the same column name for both a table's own primary key and as a foreign key elsewhere works technically, but at scale (hundreds of tables) it becomes difficult to track which occurrence is authoritative.",
  },
  {
    q: "A SCHEDULED_MAINTENANCE table references BOAT via CoastGuardRegNumber, and should never allow a boat with scheduled maintenance to be deleted. What ON DELETE action fits?",
    options: [
      "CASCADE",
      "SET NULL",
      "RESTRICT",
      "SET DEFAULT",
    ],
    answer: 2,
    explain: "RESTRICT blocks the DELETE on the parent (BOAT) entirely while dependent SCHEDULED_MAINTENANCE rows exist, forcing the maintenance records to be resolved (completed or reassigned) first rather than silently vanishing or orphaning.",
  },
  {
    q: "In a database design document, what does 'referential integrity constraint enforcement' typically document for each parent-child relationship?",
    options: [
      "Only the column data types",
      "The parent/child tables, the constraint itself, and the ON UPDATE / ON DELETE cascading behavior",
      "The number of rows in each table",
      "The index type used"
    ],
    answer: 1,
    explain: "A referential integrity enforcement table (as in Kroenke's Figure 6.19-style documentation) lists each parent-child pair, the constraint (which FK must exist in which PK), and the specific cascading behavior chosen for updates and deletes.",
  },
  {
    q: "Which of these is the correct order of increasing strictness for normal forms discussed in this module?",
    options: [
      "3NF -> 2NF -> 1NF -> BCNF",
      "1NF -> 2NF -> 3NF -> BCNF",
      "BCNF -> 3NF -> 2NF -> 1NF",
      "2NF -> 1NF -> BCNF -> 3NF",
    ],
    answer: 1,
    explain: "Each normal form builds on and is stricter than the previous: 1NF (atomic values) -> 2NF (no partial dependencies) -> 3NF (no transitive dependencies) -> BCNF (every determinant is a candidate key).",
  },
  {
    q: "Why is denormalization generally acceptable in a data warehouse's fact/dimension tables but risky in an OLTP system-of-record table?",
    options: [
      "Data warehouses are never updated after nightly loads, so anomaly risk from duplication is far lower there",
      "Data warehouses do not support SQL",
      "OLTP systems cannot store duplicate data at all",
      "Warehouses use a completely different data type system",
    ],
    answer: 0,
    explain: "Warehouse tables are typically rebuilt/refreshed on a schedule from a normalized source rather than directly hand-edited, so the update/insert/delete anomalies normalization guards against rarely get a chance to occur.",
  },
  {
    q: "What is the intersection table's composite primary key's job in an N:M relationship?",
    options: [
      "To allow duplicate relationship rows for auditing",
      "To guarantee a given pair (e.g., one project + one employee) can't be recorded more than once",
      "To automatically generate reports",
      "To replace the need for foreign keys entirely",
    ],
    answer: 1,
    explain: "The composite primary key (e.g., (project_id, employee_number)) enforces uniqueness of each pairing, preventing the same employee from being assigned to the same project twice as separate rows.",
  },
  {
    q: "A table has columns (boat_reg_number, boat_type) as its only two attributes with boat_reg_number as PK and boat_type functionally dependent on it. Is this in 3NF?",
    options: [
      "No, because there are only two columns",
      "Yes — every non-key column (boat_type) depends directly on the whole primary key, with no partial or transitive dependency",
      "No, it violates 1NF because boat_type is text",
      "It cannot be determined without more columns",
    ],
    answer: 1,
    explain: "With a single-column primary key and one dependent attribute directly determined by it, there's no possibility of a partial dependency (no composite key) or transitive dependency (no other non-key column to depend on) — it satisfies 3NF trivially.",
  },
  {
    q: "What is the main risk of skipping normalization entirely and shipping a single wide table straight from an E-R diagram?",
    options: [
      "The database will refuse to start",
      "Update, insertion, and deletion anomalies resurface because multiple themes are mixed on one row",
      "SQL SELECT statements become illegal",
      "Primary keys become optional",
    ],
    answer: 1,
    explain: "Skipping normalization reproduces the exact anomalies (update, insertion, deletion) that motivated splitting data into themed tables in the first place — the same problems seen with flat spreadsheet-style lists.",
  },
];
