// ── Module 07 — Data Warehousing, BI & Big Data (32) ────────────────────────
QUESTIONS["07"] = [
  {
    q: "What is the primary purpose of a data warehouse?",
    options: [
      "To process day-to-day transactions faster than an OLTP system",
      "To store and prepare data, over time, specifically for business intelligence and analysis",
      "To replace the need for any operational database",
      "To act as a network firewall for sensitive data",
    ],
    answer: 1,
    explain: "A data warehouse is a database (plus the programs and people around it) dedicated to preparing data for BI processing — not for running day-to-day operational transactions.",
  },
  {
    q: "What distinguishes a data mart from a data warehouse?",
    options: [
      "A data mart only stores unstructured files",
      "A data mart is a smaller collection of data scoped to one department or subject area",
      "A data mart cannot be queried with SQL",
      "A data mart always precedes the warehouse in the ETL pipeline",
    ],
    answer: 1,
    explain: "A data mart addresses a specific component/department, smaller in scope than the full enterprise data warehouse.",
  },
  {
    q: "A repository that stores all of a business's data — including raw files like photos and documents — in their original form is called a...",
    options: ["Data mart", "Data lake", "Star schema", "Fact table"],
    answer: 1,
    explain: "A data lake stores everything relevant to a business, including unstructured files, generally without the cleaning/structuring a warehouse applies before storage.",
  },
  {
    q: "In the ETL process, what happens during the 'Transform' step?",
    options: [
      "Data is pulled out of the source system",
      "Data is written into the warehouse's tables",
      "Data is cleaned, standardized, and reshaped (e.g., 'US' becomes 'United States')",
      "Data is permanently deleted from the source system",
    ],
    answer: 2,
    explain: "Transform cleans and standardizes extracted data — fixing formats, resolving codes, and reshaping values — before it's loaded into the warehouse.",
  },
  {
    q: "What is the key difference between ETL and ELT?",
    options: [
      "ELT skips the transform step entirely",
      "ELT loads raw data into the warehouse first, then transforms it there using the warehouse's own compute power",
      "ETL is only used with NoSQL databases",
      "There is no meaningful difference",
    ],
    answer: 1,
    explain: "ELT (Extract, Load, Transform) loads first and transforms afterward, taking advantage of cheap, scalable cloud warehouse compute — practical for very large raw datasets.",
  },
  {
    q: "In a star schema, what sits at the center, surrounded by dimension tables?",
    options: ["A dimension table", "A fact table", "A view", "An index"],
    answer: 1,
    explain: "The fact table sits at the center of a star schema, holding foreign keys to each dimension plus numeric measures.",
  },
  {
    q: "In a star schema, which table typically holds numeric 'measures' like quantity sold or revenue?",
    options: ["The fact table", "A dimension table", "The date dimension only", "None — measures are computed at query time, never stored"],
    answer: 0,
    explain: "The fact table holds the measures (quantities, amounts) alongside foreign keys pointing to each surrounding dimension.",
  },
  {
    q: "Compared to the fact table, dimension tables in a star schema are typically...",
    options: [
      "Fully normalized, just like OLTP tables",
      "Denormalized, often with repeated text, to keep joins simple and fast",
      "Empty until queried",
      "Stored only as views, never as real tables",
    ],
    answer: 1,
    explain: "Dimension tables are often deliberately denormalized because the priority is simple, fast joins for analysis, not preventing update anomalies.",
  },
  {
    q: "Why is a 'date dimension' table (dim_date) commonly built in a warehouse instead of computing quarter/month from a raw DATE column at query time?",
    options: [
      "PostgreSQL cannot extract a quarter from a DATE column",
      "It precomputes calendar attributes once so every report can GROUP BY them via a simple join",
      "It is required by the SQL standard",
      "It removes the need for a fact table entirely",
    ],
    answer: 1,
    explain: "Precomputing attributes like quarter, month_name, and day_of_week in dim_date avoids repeating date-math logic in every analytical query.",
  },
  {
    q: "Which of the following is a defining trait of OLTP workloads?",
    options: [
      "Few large queries scanning millions of rows",
      "Many small, fast transactions touching a handful of rows at a time",
      "Read-only historical analysis",
      "Denormalized star-schema tables",
    ],
    answer: 1,
    explain: "OLTP describes the day-to-day operational workload — lots of small, fast transactions against current data.",
  },
  {
    q: "Which of the following is a defining trait of OLAP workloads?",
    options: [
      "Point lookups by primary key",
      "Heavy write concurrency from end users",
      "Fewer, heavier read queries aggregating large historical datasets",
      "Strict normalization to prevent update anomalies",
    ],
    answer: 2,
    explain: "OLAP describes the analytical workload run against a warehouse — read-mostly, large-scale aggregation over historical data.",
  },
  {
    q: "Business intelligence (BI) systems are best described as systems that...",
    options: [
      "Record and process day-to-day orders",
      "Support management assessment, analysis, planning, and control — not day-to-day operations",
      "Only run on distributed NoSQL clusters",
      "Replace the need for a data warehouse",
    ],
    answer: 1,
    explain: "BI systems assist managers in analyzing current and past activity and predicting future events; they do not support operational activities like recording orders.",
  },
  {
    q: "What are the two broad categories BI systems generally fall into?",
    options: [
      "Reporting systems and data mining applications",
      "OLTP systems and NoSQL systems",
      "IaaS systems and PaaS systems",
      "Fact tables and dimension tables",
    ],
    answer: 0,
    explain: "Reporting systems sort/filter/group operational-derived data; data mining applications apply more sophisticated statistical/mathematical analysis.",
  },
  {
    q: "In OLAP terminology, what is a 'measure'?",
    options: [
      "An input used to slice a report, like region or year",
      "A calculated output, such as a sum or average, produced by an OLAP report",
      "A type of NoSQL database",
      "A synonym for a dimension table",
    ],
    answer: 1,
    explain: "An OLAP report takes dimensions as inputs and calculates measures (like SUM or AVG) as outputs.",
  },
  {
    q: "In PostgreSQL, `GROUP BY ROLLUP (product_name, quarter)` produces which set of rows?",
    options: [
      "Only the grand total row",
      "Detail rows per combination, then subtotals per product_name, then one grand total",
      "Every possible combination of subtotals, not just the hierarchical path",
      "The same result as a plain GROUP BY with no subtotals",
    ],
    answer: 1,
    explain: "ROLLUP produces a hierarchical set of subtotals following the order of the columns listed, ending in one grand-total row.",
  },
  {
    q: "How does `GROUP BY CUBE (a, b)` differ from `GROUP BY ROLLUP (a, b)`?",
    options: [
      "CUBE produces fewer rows than ROLLUP",
      "CUBE produces subtotals for every possible combination of the grouped columns, not just the hierarchical path",
      "CUBE is a MySQL-only extension",
      "CUBE cannot be combined with SUM()",
    ],
    answer: 1,
    explain: "CUBE generalizes ROLLUP by computing subtotals for every combination of grouping columns, useful when there's no natural hierarchy among them.",
  },
  {
    q: "What does the SQL function GROUPING(column) return on a subtotal row generated by ROLLUP or CUBE?",
    options: ["0", "1", "NULL", "The column's actual value"],
    answer: 1,
    explain: "GROUPING(column) returns 1 on rows that are subtotal/grand-total rows for that column, and 0 on genuine detail rows — useful for labeling subtotals.",
  },
  {
    q: "Which MySQL syntax approximates ROLLUP-style subtotals?",
    options: [
      "GROUP BY ... WITH ROLLUP",
      "GROUP BY CUBE(...)",
      "PARTITION BY ROLLUP",
      "MySQL has never supported any form of rollup",
    ],
    answer: 0,
    explain: "MySQL supports WITH ROLLUP appended after GROUP BY, but has never implemented the CUBE extension.",
  },
  {
    q: "Virtualization is best defined as...",
    options: [
      "Using software to encrypt data at rest",
      "Using hardware and software to simulate another hardware resource, such as a virtual machine",
      "A synonym for cloud computing",
      "A technique exclusive to NoSQL databases",
    ],
    answer: 1,
    explain: "Virtualization lets one physical computer host one or more simulated virtual machines, managed by a hypervisor.",
  },
  {
    q: "What is the key architectural difference between a Type 1 ('bare metal') hypervisor and a Type 2 ('hosted') hypervisor?",
    options: [
      "Type 1 runs directly on hardware with no host OS underneath; Type 2 runs as an application on top of a host OS",
      "Type 2 is used exclusively in large data centers",
      "Type 1 cannot run more than one virtual machine",
      "There is no real difference between them",
    ],
    answer: 0,
    explain: "Type 1 hypervisors run directly on hardware (common in data centers); Type 2 hypervisors run as an application within a host operating system (common on personal machines).",
  },
  {
    q: "How does a container (e.g., Docker) differ from a full virtual machine?",
    options: [
      "A container virtualizes an entire computer including its own kernel",
      "A container shares the host machine's kernel and only packages the app plus its dependencies, making it much lighter than a VM",
      "A container always requires a Type 1 hypervisor",
      "Containers cannot run a database engine",
    ],
    answer: 1,
    explain: "Containers share the host kernel and package only the application and its dependencies, starting far faster and using fewer resources than a full VM.",
  },
  {
    q: "Which cloud service model gives the customer the least control but requires the least management effort?",
    options: ["IaaS", "PaaS", "SaaS", "None — all three require equal management effort"],
    answer: 2,
    explain: "SaaS (Software as a Service) hands over a fully built application — the customer manages nothing beyond using it, e.g., Salesforce.com.",
  },
  {
    q: "Amazon RDS, Google Cloud SQL, and Azure SQL Database are all examples of...",
    options: [
      "IaaS-only offerings with no managed database features",
      "Managed database services, where the provider handles patching, backups, and often high availability",
      "NoSQL-only database products",
      "On-premises database appliances",
    ],
    answer: 1,
    explain: "These are managed relational database services — PaaS-style offerings where the provider runs and maintains the DBMS for the customer.",
  },
  {
    q: "A hybrid cloud deployment model means...",
    options: [
      "Infrastructure shared publicly among many unrelated customers only",
      "A mix of on-premises/private cloud and public cloud systems, connected together",
      "A database that mixes SQL and NoSQL storage engines",
      "A synonym for a data lake",
    ],
    answer: 1,
    explain: "Hybrid cloud combines private/on-premises infrastructure with public cloud resources, often to keep sensitive data on-prem while bursting other workloads to the public cloud.",
  },
  {
    q: "Which of the 'Three V's' of Big Data refers to the mix of structured, semi-structured, and unstructured data?",
    options: ["Volume", "Velocity", "Variety", "Validity"],
    answer: 2,
    explain: "Variety describes the mixture of data types — tables, JSON/logs, images, video — that Big Data systems often need to store together.",
  },
  {
    q: "MapReduce processes an extremely large dataset by...",
    options: [
      "Running the entire job on a single, very powerful server",
      "Splitting the job across a cluster of machines (map), then combining partial results (reduce)",
      "Storing all data exclusively in a relational fact table",
      "Encrypting data before every query",
    ],
    answer: 1,
    explain: "MapReduce breaks a task into independent pieces distributed across a cluster, then combines (reduces) the partial results into a final output.",
  },
  {
    q: "What role does the Hadoop Distributed File System (HDFS) typically play?",
    options: [
      "It is a relational DBMS competing with PostgreSQL",
      "It provides a distributed, replicated file system across clustered servers to support large-scale MapReduce processing",
      "It is a BI reporting tool like Excel PivotTables",
      "It is a cloud deployment model alongside IaaS/PaaS/SaaS",
    ],
    answer: 1,
    explain: "HDFS gives a cluster of servers standard file services that function as one distributed, replicated file system, which MapReduce jobs read from and write to.",
  },
  {
    q: "According to the CAP theorem, which property is usually treated as effectively non-negotiable in a real distributed database?",
    options: [
      "Consistency",
      "Availability",
      "Partition tolerance",
      "None of the three can ever be guaranteed",
    ],
    answer: 2,
    explain: "Network partitions will eventually occur in any real distributed system, so partition tolerance is generally non-negotiable — the practical tradeoff is usually consistency vs. availability during a partition.",
  },
  {
    q: "Which category of NoSQL database is best suited to storing highly connected data and traversing relationships, such as social network friend-of-a-friend queries?",
    options: ["Key-value store", "Document store", "Column-family store", "Graph database"],
    answer: 3,
    explain: "Graph databases (e.g., Neo4j) store nodes and the relationships (edges) between them, optimized for relationship traversal rather than tabular queries.",
  },
  {
    q: "Redis, DynamoDB, and Memcached are examples of which NoSQL category?",
    options: ["Key-value stores", "Document stores", "Column-family stores", "Graph databases"],
    answer: 0,
    explain: "Key-value stores look up an opaque value by a single key — Redis, DynamoDB, and Memcached are all key-value NoSQL products.",
  },
  {
    q: "What advantage does PostgreSQL's JSONB type offer over a plain relational column for semi-structured data?",
    options: [
      "It stores JSON in a binary, indexable format directly inside a normal relational table, without leaving SQL or giving up joins/transactions",
      "It automatically converts all JSON data into fully normalized tables",
      "It is only usable inside NoSQL databases, not PostgreSQL itself",
      "It removes the need for a schema entirely",
    ],
    answer: 0,
    explain: "JSONB lets flexible, semi-structured data live alongside strictly typed relational columns in the same table, queryable with operators like ->> and @>, and indexable with GIN.",
  },
  {
    q: "How does SQL Server typically store and query JSON data, in contrast to PostgreSQL's dedicated JSONB type?",
    options: [
      "SQL Server has an identical JSONB type with binary storage",
      "SQL Server stores JSON as plain NVARCHAR text and provides JSON functions like JSON_VALUE and JSON_QUERY to work with it",
      "SQL Server cannot store JSON data at all",
      "SQL Server requires a separate NoSQL extension to store any JSON",
    ],
    answer: 1,
    explain: "Unlike Postgres's dedicated JSONB type, SQL Server stores JSON as text (NVARCHAR) and exposes dedicated functions to query into it.",
  },
];
