// ── Module 02 — The Relational Model (75) ────────────────────────────────
QUESTIONS["02"] = [
  {
    q: "In formal relational terminology, what is the equivalent of a 'table'?",
    options: ["Tuple", "Relation", "Domain", "Schema"],
    answer: 1,
    explain: "A relation is the formal term for what is casually called a table.",
  },
  {
    q: "In formal relational terminology, what is the equivalent of a 'row'?",
    options: ["Attribute", "Domain", "Tuple", "Relation"],
    answer: 2,
    explain: "A tuple is the formal term for a row, representing one occurrence of the relation's theme.",
  },
  {
    q: "In formal relational terminology, what is the equivalent of a 'column'?",
    options: ["Tuple", "Attribute", "Relation", "Key"],
    answer: 1,
    explain: "An attribute is the formal term for a column — a named characteristic shared by every tuple.",
  },
  {
    q: "What is the 'domain' of an attribute?",
    options: [
      "The website hosting the database",
      "The set of legal values the attribute can hold",
      "The primary key of the table",
      "The number of rows in the table",
    ],
    answer: 1,
    explain: "A domain is the set of allowable values for an attribute, similar to (but conceptually broader than) a SQL data type.",
  },
  {
    q: "Is every SQL 'table' guaranteed to be a formally valid 'relation'?",
    options: [
      "Yes, always, by definition",
      "Not necessarily — a table can violate relational rules (e.g., store non-atomic values) while SQL still calls it a table",
      "No, SQL tables are never relations",
      "Only if it has a foreign key",
    ],
    answer: 1,
    explain: "SQL and everyday usage apply the word 'table' loosely, even to structures that break formal relation rules like atomicity.",
  },
  {
    q: "Which of the following is NOT one of the four defining characteristics of a relation covered in this module?",
    options: [
      "No duplicate rows",
      "Row order doesn't matter",
      "Every cell must contain a numeric value",
      "Every cell holds a single atomic value",
    ],
    answer: 2,
    explain: "Relations don't require numeric-only cells — they require atomic (single) values, which can be of any data type.",
  },
  {
    q: "Why must a relation have no duplicate rows?",
    options: [
      "Because SQL cannot store duplicate data physically",
      "Because if two rows were fully identical there would be no way to reliably distinguish or refer to one over the other",
      "Because duplicate rows slow down queries",
      "Because primary keys are optional",
    ],
    answer: 1,
    explain: "Without uniqueness, there would be no reliable way to identify a specific row — which is exactly the problem keys are designed to solve.",
  },
  {
    q: "A table lists rows sorted by LastName in one query and by EmployeeNumber in another. Does this change which relation it represents?",
    options: [
      "Yes, they are now two different relations",
      "No — row order is not part of a relation's definition; ORDER BY only affects display",
      "Only if the primary key changes",
      "Only in MySQL",
    ],
    answer: 1,
    explain: "A relation is a set of rows; row order carries no meaning. ORDER BY is a display/query concern, not a structural one.",
  },
  {
    q: "A column stores 'SQL, Excel, Salesforce' as a single value for one employee. Which relational rule does this violate?",
    options: [
      "No duplicate rows",
      "Row order doesn't matter",
      "Atomic (single) value per cell",
      "Column order doesn't matter",
    ],
    answer: 2,
    explain: "Packing multiple values into one cell violates the atomicity rule — each cell must hold exactly one value.",
  },
  {
    q: "What is a key, in relational terms?",
    options: [
      "Any column that stores text",
      "One or more columns used to uniquely identify a row in a relation",
      "A column with a NULL default",
      "A column that only appears once in the schema",
    ],
    answer: 1,
    explain: "A key is one or more columns whose value(s) uniquely identify a specific row.",
  },
  {
    q: "What is a candidate key?",
    options: [
      "Any column that could uniquely identify each row, whether or not it was chosen as the primary key",
      "A key that has not yet been created",
      "Only a key made of two or more columns",
      "A foreign key that references itself",
    ],
    answer: 0,
    explain: "A candidate key is any column or column-set capable of uniquely identifying rows; the primary key is the one candidate key actually chosen.",
  },
  {
    q: "In the WP EMPLOYEE table, both EmployeeNumber and EmailAddress could each uniquely identify a row. If EmployeeNumber is chosen as the primary key, what is EmailAddress called?",
    options: ["A surrogate key", "An alternate key", "A composite key", "A transitive key"],
    answer: 1,
    explain: "A candidate key that exists but was not chosen as the primary key is called an alternate key.",
  },
  {
    q: "What is a composite key?",
    options: [
      "A key that changes value over time",
      "A key made of two or more columns together, where no single column alone is unique",
      "A key generated automatically by the DBMS",
      "A foreign key with a default value",
    ],
    answer: 1,
    explain: "A composite key requires the combination of two or more columns to guarantee uniqueness; the WP ASSIGNMENT table's (ProjectID, EmployeeNumber) is a classic example.",
  },
  {
    q: "In the WP ASSIGNMENT table (ProjectID, EmployeeNumber, HoursWorked), why is neither ProjectID nor EmployeeNumber alone a valid primary key?",
    options: [
      "Because HoursWorked is always NULL",
      "Because one project has many employees, and one employee works on many projects — only the pair is unique",
      "Because ASSIGNMENT has no primary key at all",
      "Because ProjectID is a foreign key and cannot be part of any key",
    ],
    answer: 1,
    explain: "Neither column alone is unique in ASSIGNMENT; only the combination (ProjectID, EmployeeNumber) uniquely identifies a row, making it a composite key.",
  },
  {
    q: "What is a surrogate key?",
    options: [
      "A real-world identifier like an email address or SSN used as a key",
      "An artificial, DBMS-generated identifier (often a plain integer) added purely to serve as the primary key",
      "A key that references another table",
      "A key that can hold duplicate values",
    ],
    answer: 1,
    explain: "A surrogate key is an artificial identifier with no business meaning, added specifically to serve as a stable primary key.",
  },
  {
    q: "What is a natural key?",
    options: [
      "A key made only of numbers",
      "A candidate key composed of data that has inherent real-world meaning, such as an email address or department name",
      "A key that is never unique",
      "A key added automatically by PostgreSQL",
    ],
    answer: 1,
    explain: "A natural key uses real business data (rather than an artificial identifier) as the unique identifier for a row.",
  },
  {
    q: "Why is DepartmentName a risky primary key choice for WP's DEPARTMENT table?",
    options: [
      "Text columns cannot be primary keys in SQL",
      "If the department is ever renamed, every referencing foreign key value elsewhere must also be updated to match",
      "DepartmentName is always NULL",
      "PostgreSQL forbids VARCHAR primary keys",
    ],
    answer: 1,
    explain: "A natural key that can change value (like a name) risks costly, error-prone cascading updates across every table that references it. A surrogate DepartmentID avoids this.",
  },
  {
    q: "What are the qualities of an ideal surrogate key?",
    options: ["Long, alphabetic, and frequently changing", "Short, numeric, and never changes", "Always a composite of 3+ columns", "Human-readable and meaningful"],
    answer: 1,
    explain: "A good surrogate key is short, numeric, and stable — it never changes once assigned to a row.",
  },
  {
    q: "What is a foreign key?",
    options: [
      "A primary key of one relation placed as a column in another relation, to represent a relationship",
      "A key that always has a NULL value",
      "A column that stores foreign currency amounts",
      "A duplicate copy of the primary key within the same table",
    ],
    answer: 0,
    explain: "A foreign key is a column (or columns) in one table holding the primary key value of a row in another (or the same) table, representing a relationship.",
  },
  {
    q: "In the WP schema, EMPLOYEE.Department is a foreign key referencing which table's primary key?",
    options: ["PROJECT", "ASSIGNMENT", "DEPARTMENT", "EMPLOYEE itself"],
    answer: 2,
    explain: "EMPLOYEE.Department is a foreign key referencing DEPARTMENT's primary key, linking each employee to their department.",
  },
  {
    q: "What does a self-referencing foreign key, like EMPLOYEE.Supervisor referencing EMPLOYEE.EmployeeNumber, typically represent?",
    options: [
      "A data entry error",
      "A hierarchical relationship, such as an org chart where each employee's supervisor is also an employee",
      "A many-to-many relationship requiring a linking table",
      "An invalid schema that PostgreSQL will reject",
    ],
    answer: 1,
    explain: "A self-referencing foreign key is a common way to model hierarchies (like org charts) within a single table.",
  },
  {
    q: "In PostgreSQL, which clause enforces that a column's value must exist as a primary key value in another table?",
    options: ["CHECK", "REFERENCES", "DEFAULT", "UNIQUE"],
    answer: 1,
    explain: "REFERENCES table(column) declares a foreign key constraint, enforcing referential integrity.",
  },
  {
    q: "Which auto-increment syntax matches SQL Server?",
    options: ["SERIAL", "AUTO_INCREMENT", "IDENTITY(1,1)", "GENERATED ALWAYS AS IDENTITY (Oracle style)"],
    answer: 2,
    explain: "SQL Server uses IDENTITY(1,1) for auto-incrementing columns; PostgreSQL uses SERIAL, MySQL uses AUTO_INCREMENT.",
  },
  {
    q: "A functional dependency X → Y means...",
    options: [
      "X and Y are always equal",
      "Knowing the value of X tells you, with certainty, the value of Y",
      "Y must be a foreign key",
      "X is always the primary key",
    ],
    answer: 1,
    explain: "X → Y ('X determines Y') means every value of X corresponds to exactly one value of Y.",
  },
  {
    q: "In a functional dependency X → Y, what is X called?",
    options: ["The dependent", "The determinant", "The surrogate", "The domain"],
    answer: 1,
    explain: "X, the column(s) on the left of the arrow, is called the determinant.",
  },
  {
    q: "Why does the primary key of a relation always functionally determine every other attribute?",
    options: [
      "Because primary keys are always numeric",
      "Because the primary key uniquely identifies each row, so it pins down every other column's value for that row",
      "This is not actually true in general",
      "Because SQL enforces this automatically at the storage level",
    ],
    answer: 1,
    explain: "Since a primary key uniquely identifies a row, knowing its value tells you exactly which row you're looking at — and therefore every other attribute's value in that row.",
  },
  {
    q: "What is a partial dependency?",
    options: [
      "A dependency between two non-key columns",
      "A non-key column that depends on only part of a composite primary key, rather than the whole key",
      "A foreign key that is sometimes NULL",
      "A dependency that only holds true half the time",
    ],
    answer: 1,
    explain: "A partial dependency occurs when a non-key attribute depends on just part of a composite key rather than needing the entire key.",
  },
  {
    q: "ASSIGNMENT's key is (ProjectID, EmployeeNumber). A column EmployeeDepartment is added, and it only depends on EmployeeNumber. What is this called?",
    options: ["A full functional dependency", "A partial dependency", "A candidate key", "A surrogate key"],
    answer: 1,
    explain: "EmployeeDepartment depends on only part of the composite key (EmployeeNumber), making this a partial dependency — and a design smell.",
  },
  {
    q: "What is a transitive dependency?",
    options: [
      "A dependency where a non-key column depends on another non-key column, rather than directly on the key",
      "A dependency that changes over time",
      "A dependency involving three or more tables",
      "Any dependency involving a foreign key",
    ],
    answer: 0,
    explain: "A transitive dependency exists when a non-key column's value depends on another non-key column, which in turn depends on the key — 'key → non-key → non-key'.",
  },
  {
    q: "EMPLOYEE stores Department and DepartmentPhone, where DepartmentPhone depends on Department, not directly on EmployeeNumber. What kind of dependency is EmployeeNumber → DepartmentPhone?",
    options: ["A full functional dependency", "A partial dependency", "A transitive dependency", "Not a dependency at all"],
    answer: 2,
    explain: "EmployeeNumber → DepartmentPhone only holds transitively, through Department (EmployeeNumber → Department → DepartmentPhone) — a transitive dependency.",
  },
  {
    q: "What kind of dependency is HoursWorked on in ASSIGNMENT (ProjectID, EmployeeNumber, HoursWorked)?",
    options: [
      "A partial dependency on EmployeeNumber only",
      "A full functional dependency on the entire composite key (ProjectID, EmployeeNumber)",
      "A transitive dependency through ProjectID",
      "No dependency — HoursWorked is independent",
    ],
    answer: 1,
    explain: "HoursWorked genuinely requires both ProjectID and EmployeeNumber to be determined — it's specific to one employee working on one project — making it a full functional dependency.",
  },
  {
    q: "Why does this course introduce full, partial, and transitive dependencies before teaching normal forms?",
    options: [
      "Normal forms are unrelated to functional dependencies",
      "Because normalization (taught in Module 05) is built directly on this dependency vocabulary — it's the groundwork needed first",
      "Because PostgreSQL requires dependencies to be declared before tables are created",
      "Because normal forms were deprecated in modern SQL",
    ],
    answer: 1,
    explain: "Functional dependency vocabulary (full, partial, transitive) is the foundation the normalization process in Module 05 is built on.",
  },
  {
    q: "In formal relational terminology, what is the equivalent of a SQL 'data type' for a column?",
    options: ["Tuple", "Relation", "Domain", "Attribute"],
    answer: 2,
    explain: "A domain is the set of legal values an attribute can hold — conceptually broader than, but closely related to, a SQL data type.",
  },
  {
    q: "What is an 'entity' in relational database design?",
    options: [
      "A synonym for 'foreign key'",
      "The real-world thing of interest a relation represents, such as a customer or an employee",
      "A row that has been deleted",
      "A column with a UNIQUE constraint",
    ],
    answer: 1,
    explain: "An entity is the real-world thing (customer, employee, project) that a table is meant to represent; ideally each entity maps to exactly one table.",
  },
  {
    q: "Which formal shorthand correctly represents the relation EMPLOYEE with attributes EmployeeNumber, FirstName, LastName, Department, EmailAddress?",
    options: [
      "EMPLOYEE {EmployeeNumber; FirstName; LastName; Department; EmailAddress}",
      "EMPLOYEE(EmployeeNumber, FirstName, LastName, Department, EmailAddress)",
      "employee.EmployeeNumber, employee.FirstName, ...",
      "[EMPLOYEE] -> (EmployeeNumber, FirstName)",
    ],
    answer: 1,
    explain: "The formal shorthand lists the relation name in caps followed by its attributes in parentheses, e.g. EMPLOYEE(EmployeeNumber, FirstName, LastName, Department, EmailAddress).",
  },
  {
    q: "What is a 'database schema'?",
    options: [
      "The current rows stored in every table",
      "The overall design — the full set of table/relation definitions, attributes, and relationships a database is built on",
      "A backup file of the database",
      "A single SQL SELECT statement",
    ],
    answer: 1,
    explain: "The schema is the blueprint of tables, attributes, and relationships — 'the noun' — distinct from the data currently sitting inside it — 'the verb'.",
  },
  {
    q: "Which of these statements about schema vs. data is correct?",
    options: [
      "Changing the data always requires redefining the schema",
      "You can change the data all day without touching the schema, but changing the schema is a separate, more careful operation",
      "The schema and the data are the same thing",
      "Only the DBMS vendor can view the schema",
    ],
    answer: 1,
    explain: "Data (rows) can change freely without altering the schema; changing the schema itself (e.g., adding a column) is a distinct, more deliberate operation.",
  },
  {
    q: "Which PostgreSQL command/query is used to inspect part of a table's schema?",
    options: [
      "SELECT * FROM employee;",
      "\\d employee (or querying information_schema.columns)",
      "DELETE FROM employee;",
      "VACUUM employee;",
    ],
    answer: 1,
    explain: "\\d employee (in psql) or querying information_schema.columns reveals the schema — column names, types, constraints — not the data itself.",
  },
  {
    q: "Is 'table' in everyday SQL usage always a perfectly valid 'relation' in the formal sense?",
    options: [
      "Yes, SQL enforces all relational rules automatically for every table",
      "Not necessarily — a SQL table can currently violate a rule like atomicity and still be called a 'table'",
      "No, SQL tables and relations are entirely unrelated concepts",
      "Only temporary tables can violate relational rules",
    ],
    answer: 1,
    explain: "SQL and everyday language use 'table' loosely, even for structures that don't fully satisfy the strict formal rules of a relation.",
  },
  {
    q: "Which of the following would violate Rule 1 (no duplicate rows) if inserted into a proper relation?",
    options: [
      "A new row with a different EmployeeNumber but the same LastName as an existing row",
      "A row that is completely identical, in every column, to a row that already exists",
      "A row with a NULL in a nullable column",
      "A row inserted out of employee-number order",
    ],
    answer: 1,
    explain: "Only a row that is fully identical to an existing row in every column violates the no-duplicate-rows rule; sharing just one column's value (like LastName) is fine.",
  },
  {
    q: "Two queries return the EMPLOYEE table sorted differently: one by EmployeeNumber, one by LastName. Per Rule 2, are these two different relations?",
    options: [
      "Yes, sorting creates two logically distinct relations",
      "No — a relation is a set of rows; row order carries no meaning, and ORDER BY is purely a display concern",
      "Only if LastName is the primary key",
      "Only in NoSQL databases",
    ],
    answer: 1,
    explain: "A relation is a set, not a sequence — different ORDER BY clauses just change display order, not the underlying relation itself.",
  },
  {
    q: "Does writing EMPLOYEE(LastName, FirstName, EmployeeNumber) describe a different relation than EMPLOYEE(EmployeeNumber, FirstName, LastName)?",
    options: [
      "Yes, column order changes the relation's identity",
      "No — the same set of attributes describes the same relation regardless of the order they're listed in",
      "Only if a composite key is involved",
      "Yes, but only in PostgreSQL",
    ],
    answer: 1,
    explain: "Per Rule 3, column order doesn't matter to a relation's definition — SELECT * happens to follow table-definition order, but that's a display convenience.",
  },
  {
    q: "A table stores a 'Projects' column holding the value 'P1, P3' for one employee. Which rule does this violate, and what's the fix?",
    options: [
      "Rule 2 (row order) — fix by adding an ORDER BY",
      "Rule 4 (atomicity) — fix by moving each project into its own row in a separate EMPLOYEE_PROJECT table",
      "Rule 1 (no duplicate rows) — fix by deleting the row",
      "No rule is violated; comma-separated lists are valid SQL values",
    ],
    answer: 1,
    explain: "A cell holding more than one value violates the atomic-value rule; the fix is a separate linking table with one row per (employee, project) pair.",
  },
  {
    q: "A messy imported table has two fully identical rows for EmpNo 3, and a 'Projects' column storing 'P1, P3' as one value. How many distinct relational rules does this table violate?",
    options: ["Zero", "One", "Two — duplicate rows and non-atomic values", "Four"],
    answer: 2,
    explain: "This table violates both Rule 1 (no duplicate rows — the two EmpNo 3 rows are identical) and Rule 4 (atomicity — 'Projects' holds multiple values in one cell).",
  },
  {
    q: "Which of the following is NOT one of the four defining rules of a relation?",
    options: [
      "Column order doesn't matter",
      "Every foreign key must reference a different table than the primary key",
      "No duplicate rows",
      "Every cell holds a single atomic value",
    ],
    answer: 1,
    explain: "The four rules are: no duplicate rows, row order doesn't matter, column order doesn't matter, and atomic values per cell. Foreign keys referencing a 'different table' is not one of them — self-referencing foreign keys are perfectly valid.",
  },
  {
    q: "Why do keys exist, according to this module?",
    options: [
      "To make queries run faster in every case",
      "To satisfy the no-duplicate-rows rule and let other tables reliably refer back to a specific row",
      "To store metadata about column data types",
      "To enforce that row order matches insertion order",
    ],
    answer: 1,
    explain: "Keys guarantee uniqueness (satisfying Rule 1) and give other tables a reliable way to reference a specific row via a foreign key.",
  },
  {
    q: "In the WP schema, which relation's primary key is a single, non-composite column named ProjectID?",
    options: ["DEPARTMENT", "PROJECT", "ASSIGNMENT", "EMPLOYEE"],
    answer: 1,
    explain: "PROJECT (ProjectID, ProjectName, Department, MaxHours, StartDate, EndDate) uses the single-column primary key ProjectID.",
  },
  {
    q: "Can a relation have more than one candidate key?",
    options: [
      "No, a relation can only ever have exactly one candidate key",
      "Yes — for example, EMPLOYEE might have both EmployeeNumber and EmailAddress as candidate keys",
      "Only if the relation has no primary key at all",
      "Only composite keys can be candidate keys",
    ],
    answer: 1,
    explain: "A relation can have multiple candidate keys; whichever one is chosen becomes the primary key, and the rest become alternate keys.",
  },
  {
    q: "Once EmployeeNumber is chosen as EMPLOYEE's primary key, what do we call EmailAddress, which could also have uniquely identified each row?",
    options: ["A foreign key", "An alternate key", "A partial key", "A transitive key"],
    answer: 1,
    explain: "A candidate key not chosen as the primary key is called an alternate key — it's often still enforced UNIQUE in the DDL.",
  },
  {
    q: "Why is neither ProjectID alone nor EmployeeNumber alone unique in the ASSIGNMENT table?",
    options: [
      "Because ASSIGNMENT allows duplicate rows",
      "Because one project has many employees assigned, and one employee is assigned to many projects",
      "Because HoursWorked is the true primary key",
      "Because ProjectID and EmployeeNumber are both nullable",
    ],
    answer: 1,
    explain: "Since employees and projects are both many-to-many with each other through ASSIGNMENT, only the pair (ProjectID, EmployeeNumber) is guaranteed unique.",
  },
  {
    q: "Which SQL snippet correctly declares ASSIGNMENT's composite primary key?",
    options: [
      "PRIMARY KEY (project_id) REFERENCES (employee_number)",
      "PRIMARY KEY (project_id, employee_number)",
      "UNIQUE (project_id) AND UNIQUE (employee_number)",
      "FOREIGN KEY (project_id, employee_number)",
    ],
    answer: 1,
    explain: "PRIMARY KEY (project_id, employee_number) declares the two columns together as the composite primary key, matching how ASSIGNMENT is keyed in the WP schema.",
  },
  {
    q: "What is the main practical advantage of a surrogate key over a natural key like DepartmentName?",
    options: [
      "Surrogate keys are always text, which sorts more predictably",
      "A surrogate key never changes, so it avoids cascading updates if the natural data (like a name) is edited later",
      "Surrogate keys don't need to be unique",
      "Surrogate keys can be duplicated across rows",
    ],
    answer: 1,
    explain: "Because a surrogate key (like DepartmentID) is stable and meaningless, renaming the department never requires updating any foreign keys that reference it.",
  },
  {
    q: "Which of these is the best example of a natural key?",
    options: [
      "An auto-incrementing DepartmentID column",
      "A UUID generated by the application",
      "An employee's Social Security number",
      "A SERIAL PRIMARY KEY column with no other meaning",
    ],
    answer: 2,
    explain: "A Social Security number is real-world data with inherent meaning outside the database — a classic natural key, in contrast to an artificial surrogate like a SERIAL id.",
  },
  {
    q: "In the recommended WP DEPARTMENT design, what enforces that DepartmentName remains unique even though it's no longer the primary key?",
    options: [
      "Nothing — uniqueness is no longer guaranteed",
      "A UNIQUE constraint alongside the surrogate DepartmentID primary key",
      "A CHECK constraint that disallows NULLs",
      "The NOT NULL constraint alone",
    ],
    answer: 1,
    explain: "In the surrogate-key design, department_name VARCHAR(50) NOT NULL UNIQUE still enforces uniqueness on the name, even though department_id is the primary key.",
  },
  {
    q: "What best describes a foreign key?",
    options: [
      "Any column storing a numeric value",
      "A primary key value from one relation, placed as a column in another (or the same) relation to represent a relationship",
      "A column that must always allow NULL",
      "A column with a CHECK constraint attached",
    ],
    answer: 1,
    explain: "A foreign key holds a value that matches the primary key of another (or the same) relation, representing a relationship between rows.",
  },
  {
    q: "In formal relation notation, how is a foreign key attribute typically distinguished from other attributes?",
    options: [
      "It's written in ALL_CAPS",
      "It's written in italics",
      "It's given a trailing underscore",
      "It's always listed last",
    ],
    answer: 1,
    explain: "The notes state that in formal relation notation, a foreign key attribute is written in italics (while the primary key is underlined/bolded).",
  },
  {
    q: "In the WP schema, PROJECT.Department is a foreign key referencing which table?",
    options: ["ASSIGNMENT", "EMPLOYEE", "DEPARTMENT", "PROJECT itself"],
    answer: 2,
    explain: "PROJECT.Department (or department_id in the surrogate-key version) is a foreign key linking each project to the department that owns it.",
  },
  {
    q: "What does the referential integrity constraint guarantee about a foreign key value?",
    options: [
      "It must always be NULL",
      "It must match an existing value of the primary key it references, or be NULL if the relationship is optional",
      "It must be numeric",
      "It must be different from every value in the referenced table",
    ],
    answer: 1,
    explain: "Referential integrity requires every non-NULL foreign key value to correspond to an existing primary key value in the referenced table.",
  },
  {
    q: "Given: CREATE TABLE assignment (project_id VARCHAR(10) REFERENCES project(project_id), employee_number INT REFERENCES employee(employee_number), hours_worked NUMERIC(6,2), PRIMARY KEY (project_id, employee_number)); — what would happen if you tried to insert an assignment row with an employee_number that doesn't exist in employee?",
    options: [
      "It inserts successfully, employee_number is set to NULL",
      "It fails with a foreign key constraint violation",
      "It silently creates a new employee row",
      "It succeeds only if hours_worked is 0",
    ],
    answer: 1,
    explain: "The REFERENCES clause enforces referential integrity — inserting an employee_number with no matching row in employee raises a foreign key violation error.",
  },
  {
    q: "What relationship does EMPLOYEE.Supervisor, referencing EMPLOYEE.EmployeeNumber, model?",
    options: [
      "A many-to-many relationship needing a linking table",
      "A self-referencing hierarchy, such as an org chart where a supervisor is also an employee",
      "An invalid schema PostgreSQL will refuse to create",
      "A composite key relationship",
    ],
    answer: 1,
    explain: "A self-referencing foreign key like Supervisor -> EmployeeNumber is the standard way to model a hierarchy within one table.",
  },
  {
    q: "Why does the course recommend naming a foreign key column after the primary key it references (e.g., department_id) rather than after the table itself (e.g., Department)?",
    options: [
      "PostgreSQL requires it syntactically",
      "It makes it obvious at a glance which column is a PK and which is an FK, even across a schema with hundreds of tables",
      "It prevents the column from ever being NULL",
      "It automatically creates an index",
    ],
    answer: 1,
    explain: "Naming the FK column after the PK it points to (department_id) avoids ambiguity between 'this names the table' and 'this holds the table's key value', which matters at scale.",
  },
  {
    q: "Which dialect uses `id INTEGER PRIMARY KEY` (which autoincrements by default) for its auto-incrementing key syntax?",
    options: ["Oracle", "SQL Server", "SQLite", "MySQL"],
    answer: 2,
    explain: "SQLite uses id INTEGER PRIMARY KEY, which autoincrements by default without a separate keyword like SERIAL or AUTO_INCREMENT.",
  },
  {
    q: "Which dialect's auto-incrementing syntax is `id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY`?",
    options: ["Oracle", "PostgreSQL", "MySQL/MariaDB", "SQLite"],
    answer: 0,
    explain: "Oracle uses NUMBER GENERATED ALWAYS AS IDENTITY for auto-incrementing primary keys, distinct from PostgreSQL's SERIAL or MySQL's AUTO_INCREMENT.",
  },
  {
    q: "Is REFERENCES table(column) syntax for declaring foreign keys portable across PostgreSQL, MySQL, SQL Server, SQLite, and Oracle?",
    options: [
      "No, all five engines use completely different foreign key syntax",
      "Yes — it's described as essentially identical across all five engines, one of the more portable corners of SQL",
      "Only PostgreSQL and MySQL share this syntax",
      "Only Oracle supports foreign keys",
    ],
    answer: 1,
    explain: "Unlike auto-incrementing key syntax, REFERENCES table(column) is essentially the same across all five surveyed engines.",
  },
  {
    q: "What is the determinant in the functional dependency EmployeeNumber → Department?",
    options: ["Department", "EmployeeNumber", "Both, equally", "Neither — there is no determinant"],
    answer: 1,
    explain: "In X → Y, X is called the determinant. Here EmployeeNumber is X, so it's the determinant of Department.",
  },
  {
    q: "Which statement about EmployeeNumber → (FirstName, LastName, Department, OfficePhone) is correct?",
    options: [
      "It's unusual and signals a design flaw",
      "It's expected and unremarkable, since the primary key always determines every other attribute in its relation",
      "It's an example of a transitive dependency",
      "It's an example of a partial dependency",
    ],
    answer: 1,
    explain: "Since EmployeeNumber is the primary key, it uniquely identifies a row, so it determines every other column by definition — this is expected, not a design flaw.",
  },
  {
    q: "ASSIGNMENT's composite key is (ProjectID, EmployeeNumber). A poorly-designed version adds EmployeeDepartment, which depends only on EmployeeNumber. What problem does this create if an employee changes departments?",
    options: [
      "Nothing — EmployeeDepartment updates automatically everywhere",
      "Every ASSIGNMENT row for that employee must be updated, or the department value becomes inconsistent across rows",
      "The composite key becomes invalid",
      "PostgreSQL rejects the column entirely",
    ],
    answer: 1,
    explain: "Because EmployeeDepartment is repeated on every project row for that employee (a partial dependency), a department change requires updating every one of those rows to avoid inconsistency.",
  },
  {
    q: "In a poorly-designed EMPLOYEE table storing Department and DepartmentPhone, why do Fred Jones and Homer Wells (both in Marketing) show the identical phone number on their rows?",
    options: [
      "Coincidence — the values happen to match by chance",
      "DepartmentPhone is transitively dependent on Department, so it's copied redundantly onto every employee in that department",
      "OfficePhone and DepartmentPhone are the same column",
      "PostgreSQL automatically synchronizes duplicate values",
    ],
    answer: 1,
    explain: "DepartmentPhone really depends on Department (a non-key column), not on EmployeeNumber directly — a transitive dependency that causes the same phone number to be redundantly duplicated across every employee in that department.",
  },
  {
    q: "Which best describes the difference between a partial dependency and a transitive dependency?",
    options: [
      "They are the same thing with different names",
      "A partial dependency involves only part of a composite key; a transitive dependency involves a non-key column depending on another non-key column",
      "A partial dependency only occurs in single-column-key tables",
      "A transitive dependency can only occur across three or more tables",
    ],
    answer: 1,
    explain: "Partial dependency: non-key column depends on only part of a composite key. Transitive dependency: non-key column depends on another non-key column rather than directly on the key.",
  },
  {
    q: "According to the self-check tip in the functional dependencies note, what question should you ask about a non-key column to spot a partial or transitive dependency?",
    options: [
      "\"Is this column nullable?\"",
      "\"What does this value actually describe?\" — if the honest answer names something other than the primary key, it's a warning sign",
      "\"Is this column indexed?\"",
      "\"Does this column appear in a WHERE clause?\"",
    ],
    answer: 1,
    explain: "The tip suggests asking what a column's value actually describes — if it describes a department, a city, or some other theme instead of the row's own key, it likely belongs in a separate table.",
  },
  {
    q: "In ASSIGNMENT (ProjectID, EmployeeNumber, HoursWorked), which functional dependency correctly describes HoursWorked?",
    options: [
      "EmployeeNumber → HoursWorked",
      "ProjectID → HoursWorked",
      "(ProjectID, EmployeeNumber) → HoursWorked",
      "HoursWorked → (ProjectID, EmployeeNumber)",
    ],
    answer: 2,
    explain: "HoursWorked is specific to one employee working on one project, so it requires the entire composite key (ProjectID, EmployeeNumber) to determine it — a full functional dependency.",
  },
  {
    q: "A STUDENT table has StudentID as primary key and Email as a unique alternate key. Which of these is a valid functional dependency?",
    options: [
      "Major → StudentID",
      "StudentID → Email",
      "Email → Major, but not StudentID → Email",
      "There are no valid functional dependencies in this table",
    ],
    answer: 1,
    explain: "Since StudentID is the primary key, it determines every other attribute, including Email: StudentID → Email always holds.",
  },
  {
    q: "Why does this course teach full, partial, and transitive dependency vocabulary before covering normal forms?",
    options: [
      "Because normal forms are unrelated to functional dependencies",
      "Because Module 05's normalization process is built directly on this dependency vocabulary as groundwork",
      "Because PostgreSQL enforces dependencies before allowing CREATE TABLE",
      "Because this vocabulary is only tested, never applied practically",
    ],
    answer: 1,
    explain: "The functional dependency vocabulary (full, partial, transitive) is exactly the toolkit that Module 05's normalization process formalizes into concrete steps.",
  },
  {
    q: "A COURSE table has CourseID as its key, plus a Department column and a DepartmentOffice column, where DepartmentOffice really depends on Department, not CourseID. What is CourseID → DepartmentOffice an example of?",
    options: [
      "A full functional dependency directly on the key",
      "A transitive dependency, since it only holds via Department",
      "A partial dependency on part of a composite key",
      "Not a valid functional dependency at all",
    ],
    answer: 1,
    explain: "CourseID → Department → DepartmentOffice means CourseID → DepartmentOffice only holds transitively, through the non-key column Department.",
  },
  {
    q: "An ENROLLMENT table has composite key (StudentID, CourseID) and adds a StudentMajor column that depends only on StudentID. What kind of dependency is this, and what design problem does it create?",
    options: [
      "A full functional dependency; no problem at all",
      "A partial dependency; the student's major gets redundantly repeated across every course they're enrolled in",
      "A transitive dependency; CourseID determines StudentMajor",
      "Not a dependency; StudentMajor is unrelated to the key",
    ],
    answer: 1,
    explain: "StudentMajor depends on only part of the composite key (StudentID alone), making it a partial dependency — and it gets duplicated on every enrollment row for that student.",
  },
];
