// ── Module 06 — Database Administration (35) ────────────────────────────────
QUESTIONS["06"] = [
  {
    q: "What is the difference between data administration and database administration?",
    options: [
      "They are the same thing with different names",
      "Data administration is organization-wide policy; database administration is technical work on one specific system",
      "Database administration only applies to NoSQL systems",
      "Data administration is a subset of the DBA's technical tasks",
    ],
    answer: 1,
    explain: "Data administration concerns organization-wide privacy/security policy across all systems. Database administration is the technical, system-specific work of keeping one particular database and its applications running correctly.",
  },
  {
    q: "Which role is primarily responsible for building and maintaining pipelines that move data between systems?",
    options: [
      "Data architect",
      "Database administrator (DBA)",
      "Data engineer",
      "End user",
    ],
    answer: 2,
    explain: "The data engineer builds and maintains ETL/ELT pipelines moving data between source systems and destinations like a data warehouse — distinct from the DBA (operational health of a running database) and the architect (long-term data model design).",
  },
  {
    q: "Two clerks read the same 'berths_available' value, both compute a decrement, and the second write overwrites the first with no error. What is this called?",
    options: [
      "Dirty read",
      "Lost update problem",
      "Phantom read",
      "Deadlock",
    ],
    answer: 1,
    explain: "The lost update problem occurs when two transactions read the same stale value and one transaction's write silently overwrites the other's, losing one of the updates entirely.",
  },
  {
    q: "What is the difference between a shared lock and an exclusive lock?",
    options: [
      "A shared lock allows other transactions to read but not write; an exclusive lock allows neither",
      "A shared lock allows writing only; an exclusive lock allows reading only",
      "They are identical in behavior",
      "A shared lock is only used in single-user systems",
    ],
    answer: 0,
    explain: "A shared lock permits other transactions to read the locked data but not change it. An exclusive lock blocks both reading and writing by any other transaction.",
  },
  {
    q: "What is the finest (most granular) level of locking commonly supported by modern DBMSs?",
    options: [
      "Table-level",
      "Database-level",
      "Row-level",
      "Column-level",
    ],
    answer: 2,
    explain: "Row-level locking locks only the specific rows being changed, maximizing concurrency for unrelated rows. PostgreSQL defaults to row-level locking for ordinary UPDATE/DELETE statements.",
  },
  {
    q: "Which concurrency control approach locks data before doing any work and holds the lock through the transaction?",
    options: [
      "Optimistic concurrency control",
      "Pessimistic concurrency control",
      "Deferred concurrency control",
      "Stateless concurrency control",
    ],
    answer: 1,
    explain: "Pessimistic concurrency control assumes conflicts will happen, so it locks data up front (e.g., via SELECT ... FOR UPDATE) and holds the lock until the transaction commits or rolls back.",
  },
  {
    q: "Optimistic concurrency control typically detects a conflict by...",
    options: [
      "Locking every table in the database",
      "Comparing a version number or timestamp at write time against what was originally read",
      "Never checking for conflicts at all",
      "Requiring a DBA to manually approve each write",
    ],
    answer: 1,
    explain: "Optimistic control reads data without locking, then at write time checks whether a version/timestamp column still matches what was originally read; if not, the transaction retries with fresh data.",
  },
  {
    q: "What does the SQL clause SELECT ... FOR UPDATE do?",
    options: [
      "Marks rows for deletion",
      "Takes an exclusive row lock on the selected rows immediately, blocking other transactions from locking them until commit or rollback",
      "Creates a backup of the selected rows",
      "Runs the query without any transaction context",
    ],
    answer: 1,
    explain: "SELECT ... FOR UPDATE is a pessimistic locking mechanism: it immediately takes an exclusive lock on the returned rows so no other transaction can lock or update them until the current transaction finishes.",
  },
  {
    q: "What is two-phase locking (2PL)?",
    options: [
      "A technique where a transaction only acquires locks in a growing phase, then only releases them in a shrinking phase, guaranteeing serializability",
      "A method for encrypting locked rows twice",
      "A backup strategy involving two copies of the database",
      "A way to avoid using any locks at all",
    ],
    answer: 0,
    explain: "2PL splits a transaction's lock activity into a growing phase (only acquiring new locks) followed by a shrinking phase (only releasing locks), which is sufficient to guarantee serializable schedules.",
  },
  {
    q: "Transaction A holds a lock on row X and waits for row Y; Transaction B holds a lock on row Y and waits for row X. What is this called?",
    options: [
      "A phantom read",
      "A deadlock (deadly embrace)",
      "A non-repeatable read",
      "A rollforward",
    ],
    answer: 1,
    explain: "This circular wait, where neither transaction can proceed because each needs a resource the other holds, is a deadlock, also called the deadly embrace.",
  },
  {
    q: "How does PostgreSQL typically resolve a detected deadlock?",
    options: [
      "It halts the entire server until manually restarted",
      "It automatically picks one transaction as a victim, aborts it with an error, and lets the other proceed",
      "It silently merges both transactions into one",
      "It ignores the deadlock and continues both transactions",
    ],
    answer: 1,
    explain: "PostgreSQL's deadlock detector identifies the circular wait, aborts one transaction (the victim) with a 'deadlock detected' error, and the application is expected to catch this and retry.",
  },
  {
    q: "What SQL statements make up the transaction control language (TCL) covered in this module?",
    options: [
      "SELECT, INSERT, UPDATE",
      "BEGIN, COMMIT, ROLLBACK",
      "CREATE, ALTER, DROP",
      "GRANT, REVOKE, DENY",
    ],
    answer: 1,
    explain: "BEGIN (or START TRANSACTION) marks the start of a transaction, COMMIT makes its changes permanent, and ROLLBACK undoes everything since BEGIN — the core transaction control statements.",
  },
  {
    q: "What does the 'Atomic' property of an ACID transaction guarantee?",
    options: [
      "All the transaction's steps happen, or none of them do",
      "The transaction runs faster than non-atomic ones",
      "Only one user can access the database at a time",
      "Data is automatically backed up after every transaction",
    ],
    answer: 0,
    explain: "Atomicity means a transaction's series of steps are all-or-nothing — if any step fails, every prior step in that transaction is undone, leaving no partial changes.",
  },
  {
    q: "What does the 'Durable' property of an ACID transaction guarantee?",
    options: [
      "The transaction can be paused and resumed later",
      "Once committed, the transaction's changes survive even a crash immediately afterward",
      "The transaction uses the least possible disk space",
      "The transaction can never be rolled back",
    ],
    answer: 1,
    explain: "Durability guarantees that once a COMMIT succeeds, the changes are permanent, surviving crashes or power loss — implemented in PostgreSQL via write-ahead logging (WAL).",
  },
  {
    q: "Which mechanism does PostgreSQL use to guarantee durability of committed transactions?",
    options: [
      "Write-ahead logging (WAL)",
      "In-memory caching only",
      "Manual nightly snapshots",
      "Replicating to a second server is the only method",
    ],
    answer: 0,
    explain: "PostgreSQL writes every change to the write-ahead log (WAL) before it is applied to the actual data files and before COMMIT is acknowledged, so committed changes can be replayed and recovered after a crash.",
  },
  {
    q: "What is a dirty read?",
    options: [
      "Reading a row that has since been deleted",
      "Reading another transaction's uncommitted change, which might later be rolled back",
      "Reading the same row twice and getting different values both times",
      "A read that returns no rows at all",
    ],
    answer: 1,
    explain: "A dirty read occurs when a transaction reads data written by another transaction that has not yet committed — if that other transaction rolls back, the reader acted on data that never really existed.",
  },
  {
    q: "What is a non-repeatable read?",
    options: [
      "Reading uncommitted data from another transaction",
      "Re-reading the same row twice within one transaction and getting a different value because another transaction committed a change in between",
      "A query that returns rows in random order",
      "Re-running the same filtered query and getting a different set of matching rows",
    ],
    answer: 1,
    explain: "A non-repeatable read happens when a transaction reads a specific row, another transaction commits a change to that same row, and the first transaction re-reads it and sees the new value — inconsistent within its own transaction.",
  },
  {
    q: "What is a phantom read?",
    options: [
      "Reading a row that was never actually inserted",
      "Re-running the same filtered query twice within a transaction and getting a different set of matching rows because rows were inserted/deleted in between",
      "A read operation that never completes",
      "Reading a column that does not exist",
    ],
    answer: 1,
    explain: "A phantom read occurs when a transaction re-executes the same filtering query and finds new rows (or missing rows) because another transaction inserted or deleted matching rows in the interim.",
  },
  {
    q: "Which SQL standard isolation level prevents dirty reads but still allows non-repeatable reads and phantom reads?",
    options: [
      "READ UNCOMMITTED",
      "READ COMMITTED",
      "REPEATABLE READ",
      "SERIALIZABLE",
    ],
    answer: 1,
    explain: "READ COMMITTED guarantees a transaction never sees another transaction's uncommitted data (no dirty reads), but does not protect against non-repeatable reads or phantom reads.",
  },
  {
    q: "Which SQL standard isolation level prevents both dirty reads and non-repeatable reads, but still allows phantom reads?",
    options: [
      "READ UNCOMMITTED",
      "READ COMMITTED",
      "REPEATABLE READ",
      "SERIALIZABLE",
    ],
    answer: 2,
    explain: "REPEATABLE READ ensures that if a transaction reads the same row twice, it sees the same value both times, but new rows matching a filter can still appear (phantom reads) unless SERIALIZABLE is used.",
  },
  {
    q: "Which isolation level prevents dirty reads, non-repeatable reads, and phantom reads all at once?",
    options: [
      "READ UNCOMMITTED",
      "READ COMMITTED",
      "REPEATABLE READ",
      "SERIALIZABLE",
    ],
    answer: 3,
    explain: "SERIALIZABLE is the strictest isolation level, guaranteeing the result is equivalent to running all transactions one at a time in some order, preventing all three classic anomalies.",
  },
  {
    q: "What isolation level does MySQL/InnoDB default to, in contrast to PostgreSQL and Oracle?",
    options: [
      "READ UNCOMMITTED",
      "READ COMMITTED",
      "REPEATABLE READ",
      "SERIALIZABLE",
    ],
    answer: 2,
    explain: "MySQL/InnoDB defaults to REPEATABLE READ, while PostgreSQL and Oracle default to READ COMMITTED — a common surprise for developers moving code between the two without adjusting isolation-level assumptions.",
  },
  {
    q: "Why doesn't PostgreSQL truly implement READ UNCOMMITTED as a distinct behavior?",
    options: [
      "PostgreSQL rejects the syntax entirely",
      "Its MVCC (multiversion concurrency control) storage engine never lets one transaction see another's uncommitted rows, so it silently behaves like READ COMMITTED",
      "READ UNCOMMITTED is only valid in MySQL",
      "PostgreSQL requires a special extension to support any isolation levels",
    ],
    answer: 1,
    explain: "PostgreSQL accepts the READ UNCOMMITTED syntax for standards compliance but treats it identically to READ COMMITTED, because its MVCC architecture inherently prevents dirty reads regardless of the requested level.",
  },
  {
    q: "What is the difference between authentication and authorization?",
    options: [
      "They are synonyms",
      "Authentication proves who you are; authorization determines what you're allowed to do",
      "Authentication only applies to database administrators",
      "Authorization happens before authentication in every system",
    ],
    answer: 1,
    explain: "Authentication verifies identity (username/password, certificate, etc.). Authorization then determines what actions that authenticated identity is permitted to perform.",
  },
  {
    q: "What SQL statement is used to grant a user or role a database privilege?",
    options: [
      "ALLOW",
      "GRANT",
      "PERMIT",
      "ENABLE",
    ],
    answer: 1,
    explain: "GRANT is the standard SQL statement for assigning privileges (SELECT, INSERT, UPDATE, DELETE, etc.) to a user or role, with REVOKE used to take privileges back.",
  },
  {
    q: "What is the principle of least privilege?",
    options: [
      "Every user should have full administrative access by default for convenience",
      "Each user or role should be granted only the access strictly necessary for its job, and nothing more",
      "Privileges should never be granted to roles, only to individuals",
      "All privileges should be revoked at the end of every session",
    ],
    answer: 1,
    explain: "Least privilege means limiting each account's access to exactly what it needs — e.g., an application's database login should not have DROP TABLE rights, limiting the blast radius of a compromised connection.",
  },
  {
    q: "Why is it best practice to grant permissions to roles rather than directly to individual users?",
    options: [
      "Individual grants are technically impossible in SQL",
      "Roles group related permissions so that changing a person's job only requires changing role membership, not re-auditing individual grants",
      "Roles are always faster to execute at query time",
      "Individual user accounts cannot log in if given any GRANT",
    ],
    answer: 1,
    explain: "Granting to roles (e.g., booking_clerk, reporting_readonly) centralizes permission management — when someone changes jobs, you change their role membership rather than tracking down every individual grant they were given.",
  },
  {
    q: "What is a key syntax difference between PostgreSQL and MySQL regarding user/role management?",
    options: [
      "MySQL does not support GRANT at all",
      "PostgreSQL uses CREATE ROLE (a role with LOGIN acts as a user); MySQL uses CREATE USER, and privileges are tied to a user plus the host they connect from",
      "PostgreSQL requires a GUI tool to create users",
      "There is no difference; the syntax is identical",
    ],
    answer: 1,
    explain: "PostgreSQL unifies users and roles (CREATE ROLE ... WITH LOGIN). MySQL uses CREATE USER and grants are commonly scoped as user@host, tying privileges to both the account and the connecting host.",
  },
  {
    q: "What are the three backup strategies discussed, ordered from capturing the most data per backup to the least?",
    options: [
      "Incremental, differential, full",
      "Full, differential, incremental",
      "Differential, full, incremental",
      "Full, incremental, differential",
    ],
    answer: 1,
    explain: "A full backup captures everything. A differential backup captures changes since the last full backup (a growing subset). An incremental backup captures changes only since the last backup of any kind (the smallest subset).",
  },
  {
    q: "What does point-in-time recovery (PITR) allow that a simple full backup restore does not?",
    options: [
      "Restoring the database to any specific timestamp, not just the moment of the last backup",
      "Restoring only table structures without any data",
      "Skipping the need for any backup at all",
      "Restoring data from a different DBMS product entirely",
    ],
    answer: 0,
    explain: "PITR restores the last full backup and then replays the transaction log (WAL in PostgreSQL) up to any specific point in time — e.g., one minute before an accidental mass delete — rather than only to the last backup's moment.",
  },
  {
    q: "In PostgreSQL, what is the role of the write-ahead log (WAL) in point-in-time recovery?",
    options: [
      "It has no role in recovery, only in query optimization",
      "Archived WAL segments, replayed after restoring a base backup, let the database be brought forward to any specific moment in time",
      "WAL only records SELECT statements",
      "WAL is deleted immediately after each COMMIT",
    ],
    answer: 1,
    explain: "Because every committed change is durably recorded in the WAL before being applied to data files, archived WAL segments can be replayed on top of a base backup to reconstruct the database state at any specific timestamp.",
  },
  {
    q: "What is the difference between a before-image and an after-image in a transaction log?",
    options: [
      "A before-image is a screenshot of the database UI; an after-image is not used in recovery",
      "A before-image is a row's value before a change (used for rollback); an after-image is its value after the change (used for rollforward)",
      "They are two names for the same log record",
      "Before-images are only used in NoSQL systems",
    ],
    answer: 1,
    explain: "Before-images let the DBMS undo a transaction by restoring prior values (rollback). After-images let it redo a transaction by reapplying the new values (rollforward), typically used to catch a restored backup up to the present.",
  },
  {
    q: "What is the main downside of recovery via reprocessing (redoing all activity since the last backup from original input records)?",
    options: [
      "It requires no transaction log at all",
      "It can take as long as the original processing took, and a heavily loaded system may never catch up",
      "It only works for read-only databases",
      "It is faster than rollback/rollforward in every case",
    ],
    answer: 1,
    explain: "Reprocessing redoes every transaction from original inputs, taking roughly the same amount of time as it did originally — for a busy system, that reprocessing time may exceed the time available before it's needed, so it never catches up.",
  },
  {
    q: "Why should a DBA periodically test restoring a backup rather than just confirming the backup job 'succeeded'?",
    options: [
      "Testing restores is purely optional and rarely useful",
      "A backup that has never been restored is an untested assumption — corruption or incompleteness may not be discovered until a real incident",
      "Backup files never need to be tested if stored on redundant disks",
      "Restoring backups voids most database licenses",
    ],
    answer: 1,
    explain: "A successful backup job doesn't guarantee a successful restore. Periodically restoring to a scratch environment verifies the backup actually works, rather than discovering a corrupt or incomplete backup during a real outage.",
  },
  {
    q: "Which of the following is a DBA responsibility distinct from a data architect's typical focus?",
    options: [
      "Designing the long-term canonical data model across the whole organization",
      "Day-to-day performance tuning, security administration, and backup/recovery of a specific running database",
      "Deciding which entities should exist company-wide",
      "Defining master data standards across departments",
    ],
    answer: 1,
    explain: "The DBA's focus is operational and system-specific: keeping a particular running database healthy (performance, security, backups). The data architect instead focuses on the long-term, organization-wide canonical data model.",
  },
];
