// ── Module 05 — Database Design & Normalization (75) ────────────────────────
QUESTIONS["05"] = [
  {
    q: "In a 1:N relationship between DEPARTMENT and EMPLOYEE, which table receives the foreign key?",
    options: [
      "DEPARTMENT, referencing EMPLOYEE",
      "EMPLOYEE, referencing DEPARTMENT",
      "Both tables reference each other",
      "Neither — an intersection table is required",
    ],
    answer: 1,
    explain: "In a 1:N relationship the foreign key always goes on the 'many' side. EMPLOYEE (the child/many side) gets a department_id column referencing DEPARTMENT (the parent/one side).",
  },
  {
    q: "What is required to properly represent an N:M relationship between PROJECT and EMPLOYEE?",
    options: [
      "A foreign key in PROJECT only",
      "A foreign key in EMPLOYEE only",
      "A new intersection table with a composite primary key from both parents",
      "Merging PROJECT and EMPLOYEE into one table",
    ],
    answer: 2,
    explain: "N:M relationships cannot be represented with a single foreign key in either table. A new intersection (associative) table is created, with a composite primary key made of both parents' keys.",
  },
  {
    q: "What is a weak, ID-dependent entity?",
    options: [
      "An entity with no attributes",
      "An entity whose primary key must include its parent's primary key because it has no independent identity",
      "An entity that is never referenced by a foreign key",
      "An entity that only exists in a data warehouse",
    ],
    answer: 1,
    explain: "A weak, ID-dependent entity (like a LOG entry tied to a CHARTER) cannot be uniquely identified without its parent. Its primary key includes the parent's key plus a discriminator unique only within that parent.",
  },
  {
    q: "For a strict 1:1 relationship between CUSTOMER and CONTACT, what constraint (beyond the foreign key) enforces 'at most one contact per customer'?",
    options: [
      "NOT NULL",
      "CHECK",
      "UNIQUE on the foreign key column",
      "A trigger is always required",
    ],
    answer: 2,
    explain: "A plain foreign key alone allows many child rows per parent (a 1:N relationship). Adding UNIQUE to the foreign key column restricts it to at most one child row per parent, making it truly 1:1.",
  },
  {
    q: "A table has columns item1, item2, item3 to store a variable number of order items. What does this violate?",
    options: [
      "2NF (partial dependency)",
      "3NF (transitive dependency)",
      "1NF (repeating groups / non-atomic design)",
      "BCNF (overlapping candidate keys)",
    ],
    answer: 2,
    explain: "Repeating groups crammed into numbered columns (item1, item2, item3...) violate First Normal Form. The fix is a separate table with one row per item.",
  },
  {
    q: "A table SHIPMENT(shipment_id, boat_reg_number, boat_name, ship_date) has composite key (shipment_id, boat_reg_number), and boat_name depends only on boat_reg_number. What is this called?",
    options: [
      "A transitive dependency (3NF violation)",
      "A partial dependency (2NF violation)",
      "A repeating group (1NF violation)",
      "A determinant that is not a candidate key (BCNF violation)",
    ],
    answer: 1,
    explain: "boat_name depends on only part of the composite key (boat_reg_number), not the whole key (shipment_id, boat_reg_number). This partial dependency is a 2NF violation.",
  },
  {
    q: "A table CHARTER(charter_id, customer_id, customer_name) has customer_name depending on customer_id, which itself is not the primary key. What is this called?",
    options: [
      "A partial dependency (2NF violation)",
      "A transitive dependency (3NF violation)",
      "A multivalued dependency",
      "A repeating group (1NF violation)",
    ],
    answer: 1,
    explain: "customer_name depends on customer_id (a non-key column), not directly on the primary key charter_id. A non-key column depending on another non-key column is a transitive dependency — a 3NF violation.",
  },
  {
    q: "What is required for a table to satisfy Boyce-Codd Normal Form (BCNF)?",
    options: [
      "Every column must be nullable",
      "Every determinant in the table must be a candidate key",
      "The table must have at least two candidate keys",
      "Every non-key column must be numeric",
    ],
    answer: 1,
    explain: "BCNF requires that every determinant (a column or set of columns that functionally determines another column) be a candidate key. Most 3NF tables already satisfy this; violations are rare and involve overlapping composite keys.",
  },
  {
    q: "Why might a company deliberately denormalize a reporting table?",
    options: [
      "To eliminate the need for primary keys",
      "To trade some anomaly risk for faster reads by avoiding repeated joins",
      "Because normalized tables cannot be queried with SELECT",
      "To make the schema harder to understand on purpose",
    ],
    answer: 1,
    explain: "Denormalization duplicates or merges data to reduce the number of joins a query needs, improving read performance — a deliberate trade of some anomaly risk for speed, typically only done in copies that are not the sole system of record.",
  },
  {
    q: "In a recursive (unary) 1:N relationship like EMPLOYEE 'supervises' EMPLOYEE, where does the foreign key point?",
    options: [
      "To a separate SUPERVISOR table",
      "Back to the same EMPLOYEE table's own primary key",
      "It cannot be represented with a foreign key at all",
      "To the DEPARTMENT table",
    ],
    answer: 1,
    explain: "A recursive relationship connects instances of the same entity to each other. The foreign key (e.g., supervisor_id) references the table's own primary key (employee_number), not a different table.",
  },
  {
    q: "Why must a query listing every employee alongside their supervisor's name use a LEFT JOIN rather than an inner join?",
    options: [
      "LEFT JOIN is always faster",
      "Inner joins do not support table aliases",
      "An employee with no supervisor (NULL) would be dropped by an inner join",
      "LEFT JOIN is required whenever a self-join is used, regardless of nulls",
    ],
    answer: 2,
    explain: "The top-level employee (e.g., the president) has supervisor_id = NULL. An inner join has nothing to match on the right side for that row and would silently exclude it. LEFT JOIN preserves it with NULL supervisor columns.",
  },
  {
    q: "What SQL alias pattern is used to self-join a table like EMPLOYEE to itself?",
    options: [
      "You cannot join a table to itself in SQL",
      "Two different aliases for the same table, e.g., FROM employee e JOIN employee s ON ...",
      "You must first copy the table into a temp table",
      "Use UNION instead of JOIN",
    ],
    answer: 1,
    explain: "A self-join references the same table twice in the FROM clause with two different aliases (e.g., e and s), letting the query treat 'employee row' and 'supervisor row' as if they were different tables.",
  },
  {
    q: "What does WITH RECURSIVE let you do that a fixed self-join cannot?",
    options: [
      "Join more than two tables at once",
      "Walk a hierarchy of arbitrary depth without knowing how many levels exist ahead of time",
      "Avoid using a WHERE clause",
      "Query multiple databases simultaneously",
    ],
    answer: 1,
    explain: "A self-join walks exactly one level per join, requiring you to know the depth in advance. WITH RECURSIVE repeatedly applies the same join step until no new matching rows are produced, handling any depth automatically.",
  },
  {
    q: "In the anchor/recursive structure of a recursive CTE, what stops the recursion?",
    options: [
      "A LIMIT clause is always required",
      "The recursive step stops producing new matching rows (e.g., reaching a NULL supervisor_id)",
      "PostgreSQL automatically halts after 10 iterations",
      "You must manually call ROLLBACK",
    ],
    answer: 1,
    explain: "The recursive step keeps joining back to find the next level. It naturally terminates when a row's join condition has nothing left to match — e.g., when supervisor_id IS NULL, ending the chain.",
  },
  {
    q: "What ON DELETE action is generally most appropriate for the two foreign keys in an ASSIGNMENT intersection table?",
    options: [
      "RESTRICT on both",
      "SET NULL on both",
      "CASCADE on both, since an assignment row is meaningless without both parents",
      "No ON DELETE action should ever be specified",
    ],
    answer: 2,
    explain: "If a PROJECT or EMPLOYEE row is deleted, the intersection row connecting them no longer represents anything meaningful, so CASCADE deletion is the natural choice for both foreign keys.",
  },
  {
    q: "For a weak entity like LOG(charter_id, entry_number) tied to CHARTER, what ON DELETE behavior on the charter_id foreign key makes the most sense?",
    options: [
      "RESTRICT, to prevent charters from ever being deleted",
      "SET NULL, so log entries survive without a charter",
      "CASCADE, since a log entry cannot exist without its parent charter",
      "SET DEFAULT to a placeholder charter",
    ],
    answer: 2,
    explain: "Weak, ID-dependent entities have no independent existence — a log entry only makes sense in the context of its charter. CASCADE ensures log rows are removed automatically when the parent charter is deleted.",
  },
  {
    q: "Why is using DepartmentName (a text value) as a primary key in DEPARTMENT considered a weaker design than adding a surrogate department_id?",
    options: [
      "Text columns cannot be indexed",
      "Renaming a department would require updating every foreign key referencing the old text value everywhere",
      "PostgreSQL does not allow text primary keys",
      "Text primary keys cannot be used in JOIN clauses",
    ],
    answer: 1,
    explain: "When a natural, changeable value like a name is the primary key, every child table's foreign key stores that same text. Renaming the department means updating it everywhere it's referenced, unlike a stable surrogate integer key.",
  },
  {
    q: "What SQL constraint would you add to an intersection table like employee_collaboration(employee_number, collaborator_number) to prevent an employee from 'collaborating' with themselves?",
    options: [
      "UNIQUE (employee_number)",
      "CHECK (employee_number <> collaborator_number)",
      "NOT NULL on both columns only",
      "FOREIGN KEY referencing a third table",
    ],
    answer: 1,
    explain: "A CHECK constraint comparing the two foreign key columns for inequality prevents a row where an employee references themselves as their own collaborator.",
  },
  {
    q: "PostgreSQL foreign key actions include CASCADE, RESTRICT, SET NULL, and which other option?",
    options: [
      "SET DEFAULT",
      "DELETE ALL",
      "IGNORE",
      "ROLLBACK",
    ],
    answer: 0,
    explain: "PostgreSQL supports CASCADE, RESTRICT, SET NULL, SET DEFAULT, and the implicit NO ACTION as referential actions for ON UPDATE / ON DELETE clauses.",
  },
  {
    q: "Which of the following is true about foreign key enforcement in SQLite?",
    options: [
      "SQLite does not support the FOREIGN KEY syntax at all",
      "Foreign key enforcement must be explicitly turned on per connection with PRAGMA foreign_keys = ON",
      "SQLite enforces foreign keys by default just like PostgreSQL",
      "SQLite only supports foreign keys in in-memory databases",
    ],
    answer: 1,
    explain: "SQLite accepts FOREIGN KEY syntax but does not enforce it by default — each connection must run PRAGMA foreign_keys = ON to activate actual enforcement, unlike PostgreSQL, MySQL/InnoDB, and SQL Server.",
  },
  {
    q: "A CHARTER_BOOKING table stores num_days, which is calculated from departure_date and return_date. What normalization concern does this raise?",
    options: [
      "It is a repeating group and violates 1NF",
      "It is a derived/computed value that could disagree with the dates it summarizes",
      "It requires a composite primary key",
      "It cannot be represented as an INTEGER column",
    ],
    answer: 1,
    explain: "Storing a value that can be derived from other columns (num_days from departure/return dates) risks the two disagreeing after an update to one but not the other — a design smell normalization theory flags even outside a strict normal-form violation.",
  },
  {
    q: "Which of these column sets, if functionally dependent as boat_type -> skipper_name where boat_type is not a candidate key, would violate BCNF even in an otherwise-3NF table?",
    options: [
      "boat_reg_number -> boat_name",
      "boat_type -> skipper_name, when boat_reg_number (not boat_type) is the real candidate key",
      "customer_id -> customer_name",
      "charter_id -> departure_date",
    ],
    answer: 1,
    explain: "If boat_type determines skipper_name but boat_type itself isn't a candidate key of the table, that's a determinant that isn't a candidate key — the defining BCNF violation, even when the table already satisfies 3NF.",
  },
  {
    q: "What is the correct relational transformation for a 1:1 relationship where either side could reasonably hold the foreign key?",
    options: [
      "It must always go on the entity created first",
      "It is a design choice — pick whichever side is more natural for queries, or merge the tables",
      "1:1 relationships cannot be represented relationally",
      "Both tables must hold a copy of the same primary key value redundantly",
    ],
    answer: 1,
    explain: "Unlike 1:N (where the many side is forced), a 1:1 relationship's foreign key placement is a judgment call based on query patterns, or the two entities can be merged into a single table entirely.",
  },
  {
    q: "In the WP-style schema, why must the WHERE clause read DEPARTMENT.DepartmentName = EMPLOYEE.DepartmentName instead of just DepartmentName = DepartmentName when joining two tables that share a column name?",
    options: [
      "SQL requires all comparisons to use functions",
      "The column name alone is ambiguous when it exists in both tables being joined",
      "PostgreSQL does not allow WHERE clauses in multi-table queries",
      "DepartmentName must always be cast to text first",
    ],
    answer: 1,
    explain: "When both tables in a FROM clause have a column of the same name, the DBMS cannot tell which one you mean; qualifying with the table name (or alias) resolves the ambiguity.",
  },
  {
    q: "Which of the following is the best test for whether a foreign key belongs on the 'many' side of a 1:N relationship?",
    options: [
      "Whichever table has more total rows",
      "Whichever table has a shorter name",
      "Ask: can this entity have more than one of the other entity? The 'yes' side is the many/child side",
      "Whichever table was created first in the CREATE TABLE script",
    ],
    answer: 2,
    explain: "The heuristic is about business meaning, not row counts or naming: an employee belongs to exactly one department, but a department has many employees, so employee is the many/child side that holds the foreign key.",
  },
  {
    q: "What happens to a row's normal form classification if it has a NULL foreign key value (e.g., a project with no sponsoring department)?",
    options: [
      "It automatically violates 1NF",
      "Normal form is about functional dependencies among columns, not about NULLs in foreign keys — nullable FKs are a separate design decision",
      "The table must be split further to accommodate NULLs",
      "NULL foreign keys are illegal in PostgreSQL",
    ],
    answer: 1,
    explain: "Normalization addresses functional dependency structure among columns, independent of whether an optional foreign key is NULL. A nullable department_id on PROJECT is a valid, separate design choice (often paired with ON DELETE SET NULL).",
  },
  {
    q: "Why is it a bad idea to name a foreign key column identically to a candidate primary key name across differently-purposed tables, even though SQL permits it?",
    options: [
      "SQL does not permit it at all",
      "It works, but in large schemas with many tables it becomes hard to tell at a glance which occurrences are the PK and which are FKs",
      "It causes an automatic CASCADE on every DELETE",
      "It prevents the column from being indexed",
    ],
    answer: 1,
    explain: "As shown in the WP database discussion, using the same column name for both a table's own primary key and as a foreign key elsewhere works technically, but at scale (hundreds of tables) it becomes difficult to track which occurrence is authoritative.",
  },
  {
    q: "A SCHEDULED_MAINTENANCE table references BOAT via CoastGuardRegNumber, and should never allow a boat with scheduled maintenance to be deleted. What ON DELETE action fits?",
    options: [
      "CASCADE",
      "SET NULL",
      "RESTRICT",
      "SET DEFAULT",
    ],
    answer: 2,
    explain: "RESTRICT blocks the DELETE on the parent (BOAT) entirely while dependent SCHEDULED_MAINTENANCE rows exist, forcing the maintenance records to be resolved (completed or reassigned) first rather than silently vanishing or orphaning.",
  },
  {
    q: "In a database design document, what does 'referential integrity constraint enforcement' typically document for each parent-child relationship?",
    options: [
      "Only the column data types",
      "The parent/child tables, the constraint itself, and the ON UPDATE / ON DELETE cascading behavior",
      "The number of rows in each table",
      "The index type used"
    ],
    answer: 1,
    explain: "A referential integrity enforcement table (as in Kroenke's Figure 6.19-style documentation) lists each parent-child pair, the constraint (which FK must exist in which PK), and the specific cascading behavior chosen for updates and deletes.",
  },
  {
    q: "Which of these is the correct order of increasing strictness for normal forms discussed in this module?",
    options: [
      "3NF -> 2NF -> 1NF -> BCNF",
      "1NF -> 2NF -> 3NF -> BCNF",
      "BCNF -> 3NF -> 2NF -> 1NF",
      "2NF -> 1NF -> BCNF -> 3NF",
    ],
    answer: 1,
    explain: "Each normal form builds on and is stricter than the previous: 1NF (atomic values) -> 2NF (no partial dependencies) -> 3NF (no transitive dependencies) -> BCNF (every determinant is a candidate key).",
  },
  {
    q: "Why is denormalization generally acceptable in a data warehouse's fact/dimension tables but risky in an OLTP system-of-record table?",
    options: [
      "Data warehouses are never updated after nightly loads, so anomaly risk from duplication is far lower there",
      "Data warehouses do not support SQL",
      "OLTP systems cannot store duplicate data at all",
      "Warehouses use a completely different data type system",
    ],
    answer: 0,
    explain: "Warehouse tables are typically rebuilt/refreshed on a schedule from a normalized source rather than directly hand-edited, so the update/insert/delete anomalies normalization guards against rarely get a chance to occur.",
  },
  {
    q: "What is the intersection table's composite primary key's job in an N:M relationship?",
    options: [
      "To allow duplicate relationship rows for auditing",
      "To guarantee a given pair (e.g., one project + one employee) can't be recorded more than once",
      "To automatically generate reports",
      "To replace the need for foreign keys entirely",
    ],
    answer: 1,
    explain: "The composite primary key (e.g., (project_id, employee_number)) enforces uniqueness of each pairing, preventing the same employee from being assigned to the same project twice as separate rows.",
  },
  {
    q: "A table has columns (boat_reg_number, boat_type) as its only two attributes with boat_reg_number as PK and boat_type functionally dependent on it. Is this in 3NF?",
    options: [
      "No, because there are only two columns",
      "Yes — every non-key column (boat_type) depends directly on the whole primary key, with no partial or transitive dependency",
      "No, it violates 1NF because boat_type is text",
      "It cannot be determined without more columns",
    ],
    answer: 1,
    explain: "With a single-column primary key and one dependent attribute directly determined by it, there's no possibility of a partial dependency (no composite key) or transitive dependency (no other non-key column to depend on) — it satisfies 3NF trivially.",
  },
  {
    q: "What is the main risk of skipping normalization entirely and shipping a single wide table straight from an E-R diagram?",
    options: [
      "The database will refuse to start",
      "Update, insertion, and deletion anomalies resurface because multiple themes are mixed on one row",
      "SQL SELECT statements become illegal",
      "Primary keys become optional",
    ],
    answer: 1,
    explain: "Skipping normalization reproduces the exact anomalies (update, insertion, deletion) that motivated splitting data into themed tables in the first place — the same problems seen with flat spreadsheet-style lists.",
  },
  {
    q: "According to the transformation rules, what becomes a table's primary key when an entity from an E-R diagram is converted to a relational table?",
    options: [
      "A newly invented column unrelated to the entity",
      "The entity's identifier from the E-R diagram",
      "The first column listed in the CREATE TABLE statement, regardless of meaning",
      "Whichever column has the fewest NULLs",
    ],
    answer: 1,
    explain: "Rule 1 of ER-to-relational transformation says each entity becomes a table and the entity's identifier (the attribute or attributes that uniquely distinguish its instances) becomes that table's primary key.",
  },
  {
    q: "Why did the note on transforming E-R models recommend a surrogate department_id over using DepartmentName as DEPARTMENT's primary key?",
    options: [
      "VARCHAR columns cannot be declared UNIQUE",
      "A text natural key forces every referencing row elsewhere to store that same text, so renaming becomes an update-everywhere problem",
      "SERIAL columns are required by the SQL standard",
      "PostgreSQL disallows primary keys on VARCHAR columns",
    ],
    answer: 1,
    explain: "Using a natural, human-meaningful value like a department name as the primary key means every child table copies that text as its foreign key; changing the name later requires updating it wherever it was copied. A stable surrogate integer key avoids that churn.",
  },
  {
    q: "A weak entity is described as 'ID-dependent.' What exactly does that mean?",
    options: [
      "It has an auto-incrementing ID column only",
      "It cannot be uniquely identified without borrowing (at least part of) its identity from a parent entity",
      "Its ID column must be of type UUID",
      "It has no primary key at all",
    ],
    answer: 1,
    explain: "ID-dependent means the entity's own attributes are not enough to uniquely identify an instance — part of its primary key must come from its parent, because instances only make sense in the context of that parent.",
  },
  {
    q: "If a weak entity requires a parent to exist but does NOT borrow any of the parent's key attributes (it just has a mandatory foreign key), how should it be treated?",
    options: [
      "Exactly like an ID-dependent weak entity, sharing the parent's primary key",
      "Like a strong entity — give it its own surrogate key plus a plain (non-key) foreign key back to the parent",
      "It cannot be represented relationally",
      "Merge it into the parent table always",
    ],
    answer: 1,
    explain: "Not every weak entity is ID-dependent. If it merely requires a parent to exist but has its own independent identifying attribute, it gets a normal surrogate primary key and an ordinary foreign key column, without folding the parent's key into its own.",
  },
  {
    q: "In the WP-style schema, why does 'project' get its own surrogate project_id rather than being identified by project_name alone?",
    options: [
      "project_name cannot be stored as text",
      "A surrogate key avoids the same rename/foreign-key propagation problem discussed for DepartmentName, and guards against two different projects accidentally sharing a name",
      "SQL requires every table to use SERIAL",
      "project_name must always be NULL",
    ],
    answer: 1,
    explain: "Just like the department example, a surrogate key sidesteps issues if the project's display name changes or if two unrelated projects happen to share the same name — the numeric ID stays the stable, unambiguous reference.",
  },
  {
    q: "Which statement about placing the foreign key in a 1:N relationship is correct?",
    options: [
      "It is a coin-flip design choice, exactly like 1:1 relationships",
      "It is forced by the relationship's shape: the 'many' (child) side must hold the FK because only it can hold a single reference back to one parent",
      "The foreign key must be split across both tables",
      "The 'one' side always holds the FK to keep the parent table smaller",
    ],
    answer: 1,
    explain: "Unlike 1:1, a 1:N relationship's FK placement isn't a judgment call — the parent ('one' side) can't hold a list of many children in one column, so the FK must live on the child ('many') side.",
  },
  {
    q: "An ASSIGNMENT intersection table stores hours_worked. Why does that attribute belong in ASSIGNMENT rather than in PROJECT or EMPLOYEE?",
    options: [
      "hours_worked describes the relationship itself (one specific employee's time on one specific project), not either entity alone",
      "Storing attributes in intersection tables is illegal in SQL",
      "It must be duplicated identically into both PROJECT and EMPLOYEE",
      "hours_worked has no natural home and is typically discarded",
    ],
    answer: 0,
    explain: "Attributes that only make sense for a specific pairing of the two parents (this employee, on this project, for this many hours) belong on the intersection table, since they describe the relationship, not a standalone fact about either entity.",
  },
  {
    q: "What SQL keyword pairing enforces that a CUSTOMER can have at most one CONTACT row, making the relationship strictly 1:1 rather than 1:N?",
    options: [
      "PRIMARY KEY plus CHECK",
      "FOREIGN KEY plus UNIQUE on the same column",
      "NOT NULL plus DEFAULT",
      "INDEX plus CASCADE",
    ],
    answer: 1,
    explain: "A foreign key column alone allows many child rows referencing the same parent. Adding UNIQUE on that same foreign key column caps it at one child row per parent, which is what makes a relationship truly 1:1 instead of 1:N.",
  },
  {
    q: "Which of these column names would be a red flag for a 1NF violation if seen in a CREATE TABLE statement?",
    options: [
      "customer_id, customer_name, customer_phone",
      "boat_reg_number, boat_name, boat_daily_rate",
      "equipment_item_1, equipment_item_2, equipment_item_3",
      "charter_id, departure_date, return_date",
    ],
    answer: 2,
    explain: "Numbered columns like equipment_item_1/2/3 are the classic sign of a repeating group crammed into a fixed number of columns instead of separate rows — a 1NF violation. The fix is a child table with one row per item.",
  },
  {
    q: "In the CHARTER_BOOKING running example, which two columns were identified as depending on customer_id rather than on the table's real primary key charter_id?",
    options: [
      "boat_name and boat_daily_rate",
      "customer_name and customer_phone",
      "departure_date and return_date",
      "num_days and boat_reg_number",
    ],
    answer: 1,
    explain: "customer_name and customer_phone both depend on customer_id (a non-key column), not directly on charter_id — the transitive dependency that causes Rosa Alvarez's phone number to repeat across her bookings.",
  },
  {
    q: "Why is num_days (computed from departure_date and return_date) flagged as a normalization smell even if it doesn't strictly violate any numbered normal form?",
    options: [
      "INTEGER columns cannot store day counts",
      "A derived/stored value can drift out of sync with the source columns it summarizes after only one of them is updated",
      "It must always be a NULL column",
      "It requires a composite primary key",
    ],
    answer: 1,
    explain: "Storing a value that's computable from other columns risks the copy disagreeing with its source after an edit to just one side — the note calls this out as a design smell worth avoiding even outside strict normal-form violations.",
  },
  {
    q: "After fully normalizing CHARTER_BOOKING into CUSTOMER, BOAT, and CHARTER tables, what does the CHARTER table itself represent?",
    options: [
      "Every fact about customers and boats duplicated for convenience",
      "Only the fact that one specific customer booked one specific boat for a date range — a single theme",
      "A denormalized reporting snapshot",
      "The union of all three original tables merged back together",
    ],
    answer: 1,
    explain: "After normalization, CHARTER holds only customer_id, boat_reg_number, departure_date, and return_date — describing exactly one theme (the booking event itself) with customer and boat details factored out into their own tables.",
  },
  {
    q: "Which scenario best illustrates a BCNF violation that would NOT already be caught by checking for 3NF?",
    options: [
      "A column storing a comma-separated list of skills",
      "A table where boat_type determines skipper_name, but boat_type itself is not a candidate key of the table (boat_reg_number is)",
      "A column that is nullable",
      "A table with only one column",
    ],
    answer: 1,
    explain: "This is precisely the BCNF example from the notes: boat_type -> skipper_name is a valid functional dependency, but since boat_type isn't a candidate key, it's a determinant that isn't a candidate key — a BCNF violation possible even in an already-3NF table.",
  },
  {
    q: "Per the module's guidance, how much time should you spend memorizing the formal distinction between 3NF and BCNF?",
    options: [
      "It is the single most important concept in the whole module",
      "Relatively little — most real schemas that reach 3NF are already in BCNF, so focus effort on 1NF through 3NF",
      "None at all; BCNF should never be taught",
      "More time than 1NF, since 1NF violations are rare in practice",
    ],
    answer: 1,
    explain: "The note explicitly says most schemas reaching 3NF already satisfy BCNF, and BCNF-but-not-3NF violations are rare (usually involving overlapping composite candidate keys) — so 1NF/2NF/3NF cover the overwhelming majority of real design work.",
  },
  {
    q: "A dashboard denormalizes by storing a redundant customer_name directly on the charter table to skip a JOIN on every page load. What is the explicit trade-off being made?",
    options: [
      "Slower reads in exchange for a smaller schema",
      "Faster reads, at the cost of an UPDATE needing to touch two places and a risk of the two copies disagreeing",
      "No trade-off; denormalization has no downside",
      "The charter table must drop its primary key",
    ],
    answer: 1,
    explain: "Denormalizing trades read performance (avoiding a JOIN) for write complexity and anomaly risk (the same customer_name now needs updating in two tables, or the copies can silently disagree).",
  },
  {
    q: "Which of these is a defensible, commonly cited reason to denormalize, per the module?",
    options: [
      "A reporting table that's rebuilt nightly from a normalized source, so manual-edit anomalies can't occur",
      "Wanting to avoid ever writing a PRIMARY KEY clause",
      "Making the schema intentionally confusing to competitors",
      "Avoiding the need to ever run CREATE TABLE more than once",
    ],
    answer: 0,
    explain: "A regularly rebuilt/refreshed reporting or warehouse table is a defensible denormalization target because it's never hand-edited — the anomalies normalization exists to prevent simply don't get a chance to occur there.",
  },
  {
    q: "In a recursive N:M relationship like 'employee collaborates with employee,' how many foreign keys does the intersection table need, and what do they reference?",
    options: [
      "One foreign key, referencing a separate COLLABORATION table",
      "Two foreign keys, both referencing the same parent table (employee)",
      "Zero foreign keys; recursive N:M relationships use only a CHECK constraint",
      "Three foreign keys, one for each possible collaborator",
    ],
    answer: 1,
    explain: "Just like any N:M relationship, an intersection table is needed, but because it's recursive both foreign keys (employee_number and collaborator_number) reference the very same parent table rather than two different tables.",
  },
  {
    q: "For the 1:1 recursive 'mentor pairs one-to-one with mentee' example, what SQL feature keeps one employee from being the mentee of more than one other employee?",
    options: [
      "A composite primary key across two tables",
      "A UNIQUE constraint on the self-referencing foreign key column (e.g., mentee_of)",
      "A CASCADE delete rule",
      "Declaring the column as SERIAL",
    ],
    answer: 1,
    explain: "Adding UNIQUE to the self-referencing foreign key column (mentee_of) ensures no employee_number value appears more than once in that column, enforcing the 1:1 cardinality of the recursive relationship.",
  },
  {
    q: "In the recursive CTE example that walks the management chain upward from employee_number = 205, what does the 'anchor' member of the UNION ALL represent?",
    options: [
      "The very last row of the entire employee table",
      "The single starting employee row the walk begins from",
      "A row with the highest employee_number in the company",
      "Every employee with no subordinates",
    ],
    answer: 1,
    explain: "The anchor member is the base case: it selects the one starting employee (WHERE employee_number = 205), giving the recursive step its first row to join against.",
  },
  {
    q: "In that same recursive CTE, what does the recursive member's JOIN condition 'ON e.employee_number = mc.supervisor_id' accomplish on each iteration?",
    options: [
      "It finds each row's supervisor and adds that supervisor as a new row in the growing result",
      "It deletes rows that have already been visited",
      "It filters out every employee with a NULL supervisor_id immediately",
      "It sorts the final result by depth",
    ],
    answer: 0,
    explain: "Each iteration joins the running CTE result back to employee, matching each row's stored supervisor_id to find that supervisor's own employee row — effectively climbing one more level up the chain per pass.",
  },
  {
    q: "Per the module's guidance, when should you prefer a plain self-join over a recursive CTE?",
    options: [
      "Whenever the table has more than 100 rows",
      "When you know in advance exactly how many levels deep you need to go (e.g., just each employee's direct supervisor)",
      "Only when the database is SQLite",
      "Self-joins should never be used; always prefer recursive CTEs",
    ],
    answer: 1,
    explain: "The rule of thumb given is: use a self-join for a fixed, known depth (one level, like direct supervisor); reach for WITH RECURSIVE the moment the number of levels could vary or isn't known ahead of time.",
  },
  {
    q: "PostgreSQL supports which four explicit referential actions for ON UPDATE / ON DELETE, according to the notes (plus an implicit default)?",
    options: [
      "CASCADE, RESTRICT, SET NULL, SET DEFAULT",
      "CASCADE, DELETE, INSERT, UPDATE",
      "COMMIT, ROLLBACK, SAVEPOINT, RELEASE",
      "GRANT, REVOKE, DENY, ALLOW",
    ],
    answer: 0,
    explain: "The four explicit actions are CASCADE (propagate), RESTRICT (refuse), SET NULL (null the FK), and SET DEFAULT (reset FK to its default) — with NO ACTION as the implicit default if none is specified.",
  },
  {
    q: "Why does the department-employee relationship favor ON DELETE RESTRICT over ON DELETE CASCADE?",
    options: [
      "RESTRICT is the only option PostgreSQL supports for 1:N relationships",
      "CASCADE-deleting every employee when their department is removed would erase valuable employee history that should instead force a reassignment first",
      "CASCADE is reserved exclusively for weak entities and cannot be used here",
      "RESTRICT is faster to execute than CASCADE in all cases",
    ],
    answer: 1,
    explain: "Deleting a department shouldn't silently wipe out all its employees' historical records. RESTRICT blocks the delete until employees are reassigned or removed deliberately, protecting that history from accidental loss.",
  },
  {
    q: "Why does PROJECT.department_id use ON DELETE SET NULL rather than RESTRICT or CASCADE in the notes' example?",
    options: [
      "A project should be deletable only if its department still exists",
      "A project can legitimately outlive a department reorg, so nulling out the sponsoring department preserves the project while acknowledging it's now unsponsored",
      "SET NULL is required whenever a foreign key column is nullable",
      "CASCADE would be illegal syntax in this context",
    ],
    answer: 1,
    explain: "Because a project's sponsoring department is optional and can change, SET NULL lets the project record survive a department's deletion, simply losing its department association rather than being deleted or blocking the department's removal.",
  },
  {
    q: "What is the recommended ON DELETE behavior for both foreign keys in an ASSIGNMENT intersection table, and why?",
    options: [
      "RESTRICT on both, to prevent any employee or project from ever being deleted",
      "CASCADE on both, since an assignment row connecting a deleted employee or project no longer represents anything meaningful",
      "SET NULL on both, so orphaned assignment rows are kept for auditing",
      "SET DEFAULT on both, pointing orphaned rows at a placeholder row",
    ],
    answer: 1,
    explain: "If either parent (PROJECT or EMPLOYEE) is deleted, the assignment row that only existed to connect them no longer means anything, so CASCADE on both foreign keys is the natural, meaning-preserving choice.",
  },
  {
    q: "For a weak, ID-dependent entity like LOG tied to CHARTER, why does the notes' heuristic point toward CASCADE rather than RESTRICT?",
    options: [
      "Because log entries are never important enough to preserve",
      "Because the child row's data is meaningless without the parent — a log entry only means 'entry #3 of that charter,' so it should disappear when the charter does",
      "Because RESTRICT is not valid syntax for weak entities",
      "Because CASCADE is always faster regardless of relationship type",
    ],
    answer: 1,
    explain: "The heuristic given is: if a child row's data is meaningless without its parent (as with a weak, ID-dependent entity), lean CASCADE. A log entry has no identity or purpose outside the charter it belongs to.",
  },
  {
    q: "Which portability caveat applies specifically to SQLite's handling of foreign keys, per the notes?",
    options: [
      "SQLite rejects the FOREIGN KEY syntax outright",
      "SQLite accepts FOREIGN KEY syntax but does not enforce it unless PRAGMA foreign_keys = ON is set for that connection",
      "SQLite only supports CASCADE, never RESTRICT or SET NULL",
      "SQLite requires foreign keys to be defined in a separate schema file",
    ],
    answer: 1,
    explain: "Unlike PostgreSQL, MySQL/InnoDB, and SQL Server (where CASCADE/RESTRICT/SET NULL work the same way by default), SQLite parses FOREIGN KEY syntax but silently skips enforcement unless each connection explicitly runs PRAGMA foreign_keys = ON.",
  },
  {
    q: "Consider: CREATE TABLE contact (contact_id SERIAL PRIMARY KEY, customer_id INTEGER NOT NULL UNIQUE REFERENCES customer(customer_id) ON DELETE CASCADE, ...). What happens when the referenced customer row is deleted?",
    options: [
      "The DELETE is blocked until the contact row is removed manually",
      "The matching contact row is automatically deleted along with the customer",
      "The contact row's customer_id is set to NULL",
      "Nothing happens to the contact row; only a warning is logged",
    ],
    answer: 1,
    explain: "ON DELETE CASCADE means the DBMS automatically deletes any contact row referencing the deleted customer — appropriate here since a contact has no purpose once its customer is gone.",
  },
  {
    q: "A SCHEDULED_MAINTENANCE table's foreign key to BOAT uses ON DELETE RESTRICT. What is the practical effect of trying to DELETE a boat row that has open maintenance records?",
    options: [
      "The boat row is deleted and the maintenance rows are silently orphaned",
      "The DELETE statement fails with an error until the maintenance rows are resolved or removed first",
      "The maintenance rows' boat reference is automatically set to NULL",
      "PostgreSQL ignores the RESTRICT clause for maintenance-style tables",
    ],
    answer: 1,
    explain: "RESTRICT blocks the parent-row DELETE entirely while any dependent child rows exist, forcing whoever is deleting the boat to first resolve (complete or reassign) its maintenance records.",
  },
  {
    q: "Which of the following would most likely be modeled as a strict 1:1 relationship rather than 1:N?",
    options: [
      "DEPARTMENT and EMPLOYEE",
      "PROJECT and EMPLOYEE (via assignments)",
      "EMPLOYEE and a single mandatory PARKING_PERMIT record unique to that employee",
      "CUSTOMER and every CHARTER they've ever booked",
    ],
    answer: 2,
    explain: "A one-to-one pairing where each employee has exactly one parking permit (and each permit belongs to exactly one employee) is the shape of a strict 1:1 relationship, unlike the other examples which are naturally 1:N or N:M.",
  },
  {
    q: "Why is qualifying a shared column name with its table (e.g., department.department_name) required when two tables in a FROM clause share that column name?",
    options: [
      "SQL requires all column references to include a table name, even when unambiguous",
      "Without qualification, the DBMS cannot tell which of the two identically-named columns you mean",
      "Column qualification improves index performance",
      "It is only a stylistic convention with no functional effect",
    ],
    answer: 1,
    explain: "When both joined tables have a column with the same name, an unqualified reference is genuinely ambiguous to the query parser — qualifying with the table name (or alias) is the only way to resolve which one you mean.",
  },
  {
    q: "A CREATE TABLE for BOAT_TYPE_SKIPPER uses boat_type as its primary key. What normalization problem does splitting this out of BOAT_SKIPPER(boat_reg_number, boat_type, skipper_name) resolve?",
    options: [
      "A 1NF repeating-group violation",
      "A BCNF violation, since boat_type determined skipper_name without being a candidate key of the original table",
      "A missing NOT NULL constraint",
      "An ambiguous column name conflict",
    ],
    answer: 1,
    explain: "By moving the boat_type -> skipper_name fact into its own table keyed by boat_type (which is now genuinely a candidate key of that new table), the BCNF violation in the original combined table is resolved.",
  },
  {
    q: "Which of the following would you recognize as an intersection (associative) table just from its column list, PROJECT_ID INTEGER, EMPLOYEE_NUMBER INTEGER, HOURS_WORKED NUMERIC, PRIMARY KEY (PROJECT_ID, EMPLOYEE_NUMBER)?",
    options: [
      "A weak, ID-dependent entity table",
      "An intersection table resolving an N:M relationship between PROJECT and EMPLOYEE",
      "A 1:1 relationship table",
      "A recursive relationship table",
    ],
    answer: 1,
    explain: "Two foreign keys forming a composite primary key, referencing two different parent tables, plus an attribute describing the pairing (hours_worked) is the signature shape of an N:M intersection table.",
  },
  {
    q: "In a 1:N relationship, what problem would arise if you mistakenly placed the foreign key on the 'one' (parent) side instead of the 'many' (child) side?",
    options: [
      "There would be no problem; either side works identically",
      "The parent row would need to store a reference to potentially many child rows in a single column, which a normal column cannot do",
      "The database would automatically convert it to an intersection table",
      "Primary keys would no longer be enforced",
    ],
    answer: 1,
    explain: "A single scalar foreign key column can hold exactly one reference. If a department has many employees, DEPARTMENT can't hold a foreign key pointing at 'its' employees — only EMPLOYEE (the many side) can hold a single department_id pointing back.",
  },
  {
    q: "What is the relationship between the number of JOINs a typical query needs and the degree of normalization applied to a schema?",
    options: [
      "More normalization generally means more tables and therefore more JOINs needed to reassemble a full picture",
      "Normalization always reduces the number of JOINs required",
      "JOINs and normalization are unrelated concepts",
      "Normalization eliminates the need for JOINs entirely",
    ],
    answer: 0,
    explain: "Each normalization split factors data into its own themed table, so queries that need the full picture across those themes must JOIN them back together — the trade-off that sometimes motivates deliberate denormalization for read-heavy paths.",
  },
  {
    q: "A table PROJECT_STATUS_HISTORY(project_id, status_date, status_code, status_description) has status_description depending only on status_code, and (project_id, status_date) as the real primary key. What's the issue?",
    options: [
      "1NF violation from a repeating group",
      "Transitive dependency: status_description depends on the non-key column status_code rather than on the primary key",
      "No issue; this table is already in 3NF",
      "A BCNF violation requiring a composite candidate key",
    ],
    answer: 1,
    explain: "status_description depends on status_code (itself a non-key column), not on the table's actual primary key (project_id, status_date) — a transitive dependency and a 3NF violation. The fix is a separate STATUS_CODE lookup table.",
  },
  {
    q: "Which best describes the difference between a candidate key and a determinant, in the context of BCNF?",
    options: [
      "They are always the same thing in every table",
      "A determinant is any column (or set of columns) that functionally determines another column; a candidate key is a determinant that could serve as the table's unique identifier — BCNF requires every determinant to be one",
      "A candidate key is always composite, while a determinant is always a single column",
      "Determinants only exist in tables with more than five columns",
    ],
    answer: 1,
    explain: "A determinant is anything that functionally determines other attributes. BCNF's rule is that every determinant in the table must qualify as a candidate key — if some non-candidate-key column determines another column, that's the violation.",
  },
  {
    q: "A CUSTOMER table and a CONTACT table are 1:1, and every customer always has exactly one contact with no exceptions. What alternative to two separate tables does the notes mention as valid?",
    options: [
      "Splitting CONTACT into two further tables",
      "Merging CUSTOMER and CONTACT into a single table entirely",
      "Making customer_id nullable in CONTACT",
      "Removing the primary key from CUSTOMER",
    ],
    answer: 1,
    explain: "For a strict 1:1 relationship where both rows always exist together with no exceptions, merging the two entities into one table is an equally valid design choice, avoiding an unnecessary join altogether.",
  },
  {
    q: "Why can't a repeating-group violation like item1/item2/item3 simply be fixed by adding more numbered columns (item4, item5...) as the business grows?",
    options: [
      "It can be fixed that way, and is the recommended long-term solution",
      "It only delays the problem — there's still a hard cap on items per row, and querying 'find all rows containing a given item' requires checking every numbered column",
      "Numbered columns are forbidden by the SQL standard",
      "PostgreSQL limits tables to a maximum of three columns",
    ],
    answer: 1,
    explain: "Adding more numbered columns just raises the cap without removing it, and makes every query that searches for an item across all slots more complex (checking item1 OR item2 OR item3...). A child table with one row per item removes the cap and simplifies querying entirely.",
  },
  {
    q: "In the referential integrity documentation style described in the notes, what three things does each parent-child relationship entry record?",
    options: [
      "Only the column data types involved",
      "The parent and child tables, the constraint itself, and the specific ON UPDATE / ON DELETE cascading behavior chosen",
      "The number of rows currently in each table",
      "The name of the DBA who created the table",
    ],
    answer: 1,
    explain: "A referential-integrity enforcement document lists, for every parent-child pair: which tables are involved, what the constraint requires (which FK must match which PK), and the specific ON UPDATE/ON DELETE behavior chosen for that relationship.",
  },
  {
    q: "A LOG table has PRIMARY KEY (charter_id, entry_number), where entry_number restarts at 1 for every new charter. Why doesn't this composite key need a third column to guarantee uniqueness across the whole table?",
    options: [
      "It secretly does need a third column; the design is incomplete",
      "Because entry_number only needs to be unique within a given charter_id, the pair (charter_id, entry_number) is already unique across the whole table",
      "PostgreSQL automatically appends a hidden row ID",
      "entry_number is globally unique on its own already",
    ],
    answer: 1,
    explain: "The whole point of an ID-dependent weak entity's composite key is that the discriminator (entry_number) only needs to be unique within its parent's scope; combined with charter_id, the pair is guaranteed unique across every charter in the table.",
  },
];
