// ── Module 04 — Data Modeling & E-R Diagrams (36) ────────────────────────────
QUESTIONS["04"] = [
  {
    q: "What is the difference between 'data' and 'information' as used in data modeling?",
    options: [
      "They are synonyms with no meaningful difference",
      "Data is recorded facts and numbers; information is data given meaning through context or processing",
      "Data only exists in spreadsheets; information only exists in databases",
      "Information always precedes data chronologically",
    ],
    answer: 1,
    explain: "Data is a raw recorded fact (a number, a name, a date). Information is data that has been processed or presented in a meaningful context — summarized, compared, grouped.",
  },
  {
    q: "What are the five stages of the Systems Development Life Cycle (SDLC), in order?",
    options: [
      "Design, Analysis, Definition, Maintenance, Implementation",
      "System definition, Requirements analysis, Component design, Implementation, System maintenance",
      "Planning, Coding, Testing, Deployment, Retirement",
      "Analysis, Design, Coding, Debugging, Documentation",
    ],
    answer: 1,
    explain: "The classic SDLC sequence is: system definition (project plan) → requirements analysis (approved requirements) → component design (system design) → implementation (working system) → maintenance (updates, feeding the next cycle).",
  },
  {
    q: "What is the deliverable of the 'requirements analysis' step of the SDLC?",
    options: [
      "A working, installed system",
      "A set of approved user requirements",
      "The project plan",
      "A maintenance schedule",
    ],
    answer: 1,
    explain: "Requirements analysis takes the project plan as input and produces approved user requirements as its output, gathered via interviews, existing-system review, and identifying needed reports/queries.",
  },
  {
    q: "What are the three main stages of the (narrower) database development process nested inside the SDLC?",
    options: [
      "Coding, Testing, Deployment",
      "Planning, Analysis, Design, Implementation (four stages, with planning as an initial scoping step)",
      "Requirements analysis, Component design, Implementation",
      "Normalization, Denormalization, Indexing",
    ],
    answer: 2,
    explain: "The database development process is commonly described as Requirements analysis (producing the conceptual E-R model), Component design (producing the relational schema), and Implementation (building the actual database).",
  },
  {
    q: "During which phase of database development is the E-R diagram (conceptual data model) typically created?",
    options: ["Implementation", "Analysis", "Maintenance", "Component design only, never analysis"],
    answer: 1,
    explain: "The analysis phase determines specific data requirements and produces the conceptual data model — the E-R diagram — along with documented business rules.",
  },
  {
    q: "What is a business rule?",
    options: [
      "A SQL statement that creates a table",
      "A statement that defines or constrains some aspect of how an organization operates",
      "A rule that only applies to relational databases, never NoSQL",
      "A rule enforced exclusively by the DBMS query optimizer",
    ],
    answer: 1,
    explain: "A business rule is a policy statement — e.g., 'no advisor may have more than 25 advisees' — that shapes what the data model must allow or forbid.",
  },
  {
    q: "Why must business rules be gathered before drawing an E-R diagram, rather than after?",
    options: [
      "Because SQL syntax requires it",
      "Because cardinality and even entity/relationship structure are determined by business rules, not guessed from the data alone",
      "Business rules are actually optional for a correct diagram",
      "Only DBAs are allowed to define business rules",
    ],
    answer: 1,
    explain: "Cardinalities, minimum participation, and even whether two things should be separate entities all trace back to specific business rules. Modeling without them is guessing.",
  },
  {
    q: "In E-R modeling, what is an 'entity'?",
    options: [
      "A single row of data only",
      "Something the business wants to track — a person, place, object, event, or concept",
      "A SQL constraint",
      "Only a table that has a foreign key",
    ],
    answer: 1,
    explain: "An entity is a class of things the organization tracks — EMPLOYEE, DEPARTMENT, PROJECT. An entity instance is one specific occurrence, like employee #14.",
  },
  {
    q: "How should entity class names be written on an E-R diagram, per convention?",
    options: [
      "lowercase and plural, e.g. 'employees'",
      "UPPERCASE and singular, e.g. 'EMPLOYEE'",
      "camelCase, e.g. 'employeeRecord'",
      "Always prefixed with 'tbl_'",
    ],
    answer: 1,
    explain: "Convention writes entity classes in uppercase and singular — EMPLOYEE (the class), not employees or Employee.",
  },
  {
    q: "What is an 'identifier' in E-R terms?",
    options: [
      "Any attribute at all",
      "An attribute (or set of attributes) that uniquely names/identifies entity instances",
      "A relationship between two entities",
      "A foreign key shown on a conceptual diagram",
    ],
    answer: 1,
    explain: "An identifier uniquely distinguishes one entity instance from another — e.g., EmployeeNumber identifies a specific EMPLOYEE instance.",
  },
  {
    q: "Who created the entity-relationship model, and when?",
    options: ["James Martin, 1990", "Peter Chen, 1976", "Edgar Codd, 1970", "IBM, 1985"],
    answer: 1,
    explain: "Peter Chen introduced the entity-relationship model in 1976; it remains the standard conceptual modeling approach, later extended and adapted (e.g., into Crow's Foot notation).",
  },
  {
    q: "What notation style uses 'crow's feet' to depict the many side of a relationship, and is common in tools like draw.io?",
    options: ["Chen notation", "Crow's Foot (Information Engineering) notation", "UML class diagrams only", "IDEF0"],
    answer: 1,
    explain: "Crow's Foot notation (from James Martin's Information Engineering) draws cardinality symbols directly on the relationship line — bars, circles, and the three-pronged crow's foot.",
  },
  {
    q: "In Crow's Foot notation, what does a single straight bar closest to an entity mean?",
    options: ["Zero", "Exactly one (mandatory, maximum = 1)", "Many", "Zero or many"],
    answer: 1,
    explain: "A single bar represents 'exactly one' — both minimum and maximum cardinality of 1 on that end of the relationship.",
  },
  {
    q: "In Crow's Foot notation, what does a circle closest to an entity represent?",
    options: [
      "Maximum cardinality of many",
      "Minimum cardinality of zero (this entity's participation is optional)",
      "The entity is weak",
      "A ternary relationship",
    ],
    answer: 1,
    explain: "A circle denotes an optional minimum cardinality of zero — the entity instance doesn't have to participate in the relationship at all.",
  },
  {
    q: "What does the combination 'circle + crow's foot' (○<) mean at one end of a relationship line?",
    options: [
      "Exactly one, mandatory",
      "Zero or many",
      "Exactly two",
      "One or many",
    ],
    answer: 1,
    explain: "Circle = minimum zero (optional), crow's foot = maximum many. Together: zero or many — the most permissive combination.",
  },
  {
    q: "What does 'bar + crow's foot' (|<) mean at one end of a relationship line?",
    options: ["Zero or one", "Exactly zero", "One or many (at least one required, more allowed)", "Zero or many"],
    answer: 2,
    explain: "Bar = minimum one (mandatory), crow's foot = maximum many. Together: one or many — at least one instance is required, and more are permitted.",
  },
  {
    q: "Why do conceptual E-R diagrams typically NOT show foreign keys inside entity boxes?",
    options: [
      "Foreign keys don't exist until you draw a physical diagram — the conceptual diagram models business meaning, and the relationship line itself represents the connection",
      "Foreign keys are only used in NoSQL databases",
      "It's a formatting limit in most diagramming tools",
      "Conceptual diagrams never show any attributes at all",
    ],
    answer: 0,
    explain: "Foreign keys are a physical/relational implementation detail added later when converting the E-R model into table designs; the conceptual diagram's relationship line already conveys that connection.",
  },
  {
    q: "What is the maximum cardinality of a One-to-One (1:1) relationship?",
    options: [
      "A single instance of each entity relates to at most a single instance of the other",
      "A single instance of one entity relates to many of the other, and vice versa",
      "Many instances of each entity relate to many of the other",
      "1:1 relationships have no maximum cardinality by definition",
    ],
    answer: 0,
    explain: "In a 1:1 relationship, one instance of Entity A pairs with at most one instance of Entity B, and vice versa — e.g., an employee assigned exactly one parking spot.",
  },
  {
    q: "When you discover a strict 1:1 relationship in a data model, what question is it often worth asking?",
    options: [
      "Whether the relationship should instead be N:M",
      "Whether the two entities should simply be merged into a single table",
      "Whether an associative entity is required",
      "Whether the relationship should become unary",
    ],
    answer: 1,
    explain: "1:1 relationships are the rarest cardinality shape; a strict one-to-one pairing often means the 'second' entity is really just optional attributes that belong on the first entity's table.",
  },
  {
    q: "'A DEPARTMENT employs many EMPLOYEEs; each EMPLOYEE works in exactly one DEPARTMENT.' What relationship type is this?",
    options: ["One-to-One (1:1)", "One-to-Many (1:N)", "Many-to-Many (N:M)", "Ternary"],
    answer: 1,
    explain: "One department relates to many employees, but each employee relates to only one department — the classic 1:N shape, the most common in real schemas.",
  },
  {
    q: "'A STUDENT enrolls in many COURSEs; each COURSE has many STUDENTs enrolled.' What relationship type is this?",
    options: ["One-to-One (1:1)", "One-to-Many (1:N)", "Many-to-Many (N:M)", "Unary"],
    answer: 2,
    explain: "Both sides allow many — many students per course, many courses per student — making this a Many-to-Many (N:M) relationship.",
  },
  {
    q: "Why can't a pure N:M relationship line directly hold an attribute like 'EnrollmentDate'?",
    options: [
      "N:M relationships never have any attributes by SQL rule",
      "EnrollmentDate describes the specific pairing (this student, this course), not either entity alone, and a bare relationship line can't store per-pairing facts durably as a table would",
      "Dates can never be attributes in E-R diagrams",
      "It actually can, with no special construct needed",
    ],
    answer: 1,
    explain: "An attribute belonging to a relationship rather than either entity is the signal to convert that relationship into an associative entity, which can hold pairing-specific attributes as its own columns.",
  },
  {
    q: "What is an associative (intersection/linking) entity used for?",
    options: [
      "Storing metadata about the database schema itself",
      "Resolving an N:M relationship into two 1:N relationships, and holding attributes specific to the pairing",
      "Replacing the need for foreign keys entirely",
      "Only used for unary relationships",
    ],
    answer: 1,
    explain: "An associative entity sits between the two original entities, links to both via foreign keys, and holds attributes that belong to the relationship itself — e.g., ASSIGNMENT holding HoursWorked for each EMPLOYEE-PROJECT pairing.",
  },
  {
    q: "In the Wedgewood Pacific schema, what role does the ASSIGNMENT table play?",
    options: [
      "It's a weak entity with no relationship to EMPLOYEE or PROJECT",
      "It's the associative entity resolving the EMPLOYEE-PROJECT many-to-many relationship, holding HoursWorked",
      "It's a lookup table for department names",
      "It replaces the need for a PROJECT table",
    ],
    answer: 1,
    explain: "ASSIGNMENT links EMPLOYEE and PROJECT with a composite key (ProjectID, EmployeeNumber) and stores HoursWorked — a fact specific to that employee/project pairing.",
  },
  {
    q: "What is a weak entity?",
    options: [
      "Any entity with fewer than three attributes",
      "An entity that cannot exist in the database without the existence of another (parent) entity",
      "An entity that has no relationships at all",
      "An entity used only in ternary relationships",
    ],
    answer: 1,
    explain: "A weak entity's existence depends on a parent entity — e.g., a DEPENDENT record only makes sense in relation to the EMPLOYEE it belongs to.",
  },
  {
    q: "What distinguishes an 'ID-dependent' weak entity from a 'non-ID-dependent' weak entity?",
    options: [
      "ID-dependent entities have no identifier of their own and use a composite key including the parent's identifier; non-ID-dependent entities have their own identifier but still depend on the parent for existence",
      "There is no real difference between the two",
      "Non-ID-dependent entities never have foreign keys",
      "ID-dependent entities are always strong entities",
    ],
    answer: 0,
    explain: "ID-dependent weak entities (e.g., DEPENDENT identified by EmployeeID+DependentID) borrow part of their identity from the parent. Non-ID-dependent weak entities (e.g., a VEHICLE with its own VIN) have their own identifier but still can't exist without the parent.",
  },
  {
    q: "What line style represents an identifying relationship between a strong entity and an ID-dependent weak entity?",
    options: ["Dashed line", "Solid line", "Dotted line with an arrow", "No line is drawn"],
    answer: 1,
    explain: "Identifying relationships (to ID-dependent weak entities) are drawn with a solid line; non-identifying relationships (to non-ID-dependent weak entities, or between two strong entities) use a dashed line.",
  },
  {
    q: "What does 'degree' mean in the context of an E-R relationship?",
    options: [
      "The maximum cardinality of the relationship",
      "The number of distinct entity types participating in the relationship",
      "The number of attributes on the relationship",
      "Whether the relationship is mandatory or optional",
    ],
    answer: 1,
    explain: "Degree counts how many entity types are involved: one (unary), two (binary), or three (ternary) — a separate property from cardinality.",
  },
  {
    q: "'An EMPLOYEE supervises other EMPLOYEEs.' What is the degree of this relationship, and what is it also called?",
    options: [
      "Degree 2 (binary)",
      "Degree 1 (unary), also called a recursive relationship",
      "Degree 3 (ternary)",
      "Degree 0",
    ],
    answer: 1,
    explain: "Only one entity type (EMPLOYEE) participates, related back to itself — this is a unary, or recursive, relationship of degree 1.",
  },
  {
    q: "How is a recursive (unary) relationship like EMPLOYEE-supervises-EMPLOYEE typically implemented in SQL?",
    options: [
      "As two separate tables that never connect",
      "As a self-referencing foreign key (e.g., Supervisor referencing EmployeeNumber in the same table), queried with a self join",
      "It cannot be implemented in a relational database",
      "As a ternary relationship with a third table",
    ],
    answer: 1,
    explain: "A foreign key column on EMPLOYEE (e.g., Supervisor) that references EMPLOYEE's own primary key implements the recursive relationship; querying it uses a self join with two table aliases.",
  },
  {
    q: "Which relationship degree is the most common in real-world data models?",
    options: ["Unary", "Binary", "Ternary", "Quaternary"],
    answer: 1,
    explain: "Binary relationships (between two distinct entity types) are by far the most common shape — most textbook examples (department/employee, student/course) are binary.",
  },
  {
    q: "What characterizes a true ternary relationship, as opposed to three separate binary relationships?",
    options: [
      "It always has more attributes than a binary relationship",
      "A single fact genuinely requires all three entity types present simultaneously to be meaningful — decomposing it into pairwise relationships would lose information",
      "It can only exist between weak entities",
      "It must always be 1:1 on all three sides",
    ],
    answer: 1,
    explain: "A ternary relationship (e.g., SUPPLIER ships PART to WAREHOUSE) records a fact that ties three entities together at once; splitting it into three independent binary relationships loses the connection between which specific instances co-occurred.",
  },
  {
    q: "How is a ternary relationship typically implemented in a relational schema?",
    options: [
      "As three separate two-column tables",
      "As an associative entity with a foreign key to each of the three participating entities",
      "It cannot be implemented — ternary relationships are purely conceptual",
      "As a single column that lists all three IDs concatenated",
    ],
    answer: 1,
    explain: "A ternary relationship becomes one table (e.g., SHIPMENT) with foreign keys to all three participants, plus any attributes belonging to that three-way combination.",
  },
  {
    q: "Two systems both involve PROFESSOR, CLASS, and DEPARTMENT. One connects PROFESSOR directly to CLASS; the other connects PROFESSOR directly to DEPARTMENT. What determines which is 'correct'?",
    options: [
      "Only one of the two models can ever be correct in an absolute sense",
      "The context — specifically, which business questions the particular system must answer",
      "Whichever model has fewer entities is always correct",
      "PROFESSOR must always connect to both, with no exceptions",
    ],
    answer: 1,
    explain: "Both models can be equally valid; the correct choice depends on the system's purpose (e.g., an enrollment system needs PROFESSOR-CLASS; an HR system needs PROFESSOR-DEPARTMENT), not on some universally 'true' structure.",
  },
  {
    q: "A training center changes its policy from 'each class has exactly one instructor' to 'classes may be co-taught by multiple instructors.' How does this affect the INSTRUCTOR-CLASS relationship's cardinality?",
    options: [
      "It has no effect on cardinality, only on attributes",
      "It changes the relationship from 1:N to N:M, likely requiring a new associative entity",
      "It changes the relationship's degree from binary to ternary",
      "It makes INSTRUCTOR a weak entity",
    ],
    answer: 1,
    explain: "Since a CLASS can now have more than one INSTRUCTOR, the maximum cardinality on the CLASS side changes from one to many — flipping the relationship from 1:N to N:M, typically resolved with an associative entity like CLASS_ASSIGNMENT.",
  },
  {
    q: "A retailer only creates a CUSTOMER record after a completed purchase (no record for browsers). What should the minimum cardinality be on the CUSTOMER side of the CUSTOMER-PURCHASE relationship?",
    options: [
      "Zero, because purchases are optional",
      "One (mandatory), because being in CUSTOMER implies at least one PURCHASE already exists under this policy",
      "Cardinality doesn't apply to minimums, only maximums",
      "Undefined until the database is implemented",
    ],
    answer: 1,
    explain: "Given this specific business rule, every CUSTOMER row is guaranteed to have at least one related PURCHASE — so minimum cardinality on the CUSTOMER side is 1, not 0. A different policy (recording leads before any purchase) would require minimum 0 instead.",
  },
];
