// ── Module 08 — Advanced SQL (100) ───────────────────────────────────────────
QUESTIONS["08"] = [
  {
    q: "What does the ALTER TABLE statement allow you to do?",
    options: [
      "Modify the structure of an existing table — add, modify, or drop columns and constraints",
      "Only rename a table",
      "Only delete all rows from a table",
      "Create a brand-new database",
    ],
    answer: 0,
    explain: "ALTER TABLE modifies the structure of a table already created in the database, including adding/dropping columns and constraints.",
  },
  {
    q: "You need to add a NOT NULL column to a table that already has rows. What is the correct order of steps?",
    options: [
      "Add the column as NOT NULL directly; it will default new and existing rows to NULL automatically",
      "Add the column allowing NULLs, backfill every row with a value, then alter the column to enforce NOT NULL",
      "Drop the table and recreate it from scratch every time",
      "NOT NULL columns cannot ever be added to a table with existing rows",
    ],
    answer: 1,
    explain: "You must add the column as nullable first, update all existing rows with real values, and only then apply the NOT NULL constraint.",
  },
  {
    q: "Which clause is used to remove a column from an existing table?",
    options: ["REMOVE COLUMN", "DROP COLUMN", "DELETE COLUMN", "ALTER COLUMN REMOVE"],
    answer: 1,
    explain: "ALTER TABLE ... DROP COLUMN {ColumnName} removes a column from an existing table.",
  },
  {
    q: "Which clause is used to add a table-level CHECK or foreign key constraint to an existing table?",
    options: ["ADD CONSTRAINT", "NEW CONSTRAINT", "INSERT CONSTRAINT", "APPLY CONSTRAINT"],
    answer: 0,
    explain: "ALTER TABLE ... ADD CONSTRAINT {ConstraintName} {definition} adds a named constraint, whether CHECK, FOREIGN KEY, or otherwise.",
  },
  {
    q: "What problem does an upsert (MERGE-style) statement solve?",
    options: [
      "It permanently deletes duplicate rows",
      "It combines insert-or-update logic into a single atomic statement, avoiding a race condition between a separate SELECT-then-INSERT/UPDATE",
      "It creates a new index automatically",
      "It converts a table into a view",
    ],
    answer: 1,
    explain: "Checking for existence and then issuing a separate INSERT or UPDATE is a race condition under concurrent access; upsert statements do both in one atomic operation.",
  },
  {
    q: "In PostgreSQL, which clause implements upsert behavior on INSERT?",
    options: ["ON DUPLICATE KEY UPDATE", "ON CONFLICT ... DO UPDATE", "MERGE INTO", "WITH ROLLUP"],
    answer: 1,
    explain: "PostgreSQL uses INSERT ... ON CONFLICT (key) DO UPDATE SET ... to perform an upsert.",
  },
  {
    q: "In a PostgreSQL ON CONFLICT ... DO UPDATE clause, what does the keyword EXCLUDED refer to?",
    options: [
      "Rows that were skipped due to a WHERE clause",
      "The row values that would have been inserted, usable in the DO UPDATE SET clause",
      "A synonym for NULL",
      "Rows excluded from a set operator like EXCEPT",
    ],
    answer: 1,
    explain: "EXCLUDED represents the proposed new row's values — the ones that would have been inserted had there been no conflict.",
  },
  {
    q: "Which SQL dialect uses ON DUPLICATE KEY UPDATE for upserts, and does NOT support a standard MERGE statement?",
    options: ["PostgreSQL", "Oracle", "MySQL", "SQL Server"],
    answer: 2,
    explain: "MySQL has no MERGE statement; ON DUPLICATE KEY UPDATE is its closest equivalent, requiring a unique/primary key to detect conflicts.",
  },
  {
    q: "Which two database products support a standard MERGE statement (combining INSERT and UPDATE logic driven by a source table or query)?",
    options: ["MySQL and SQLite", "SQL Server and Oracle", "MongoDB and Redis", "PostgreSQL and MySQL"],
    answer: 1,
    explain: "Microsoft SQL Server and Oracle Database both support the standard MERGE statement; MySQL does not.",
  },
  {
    q: "What is an SQL view?",
    options: [
      "A physical copy of a table's data, refreshed nightly",
      "A virtual table with no data of its own, built from a stored SELECT statement",
      "A type of index used to speed up joins",
      "A backup mechanism for disaster recovery",
    ],
    answer: 1,
    explain: "A view stores no data itself — it's a saved SELECT statement that runs every time the view is queried, presented as if it were a table.",
  },
  {
    q: "Which of the following is NOT typically allowed inside the SELECT statement used to define a view?",
    options: ["A WHERE clause", "A JOIN", "An ORDER BY clause", "Column aliases"],
    answer: 2,
    explain: "Standard SQL doesn't allow ORDER BY inside a view's defining query — sort order must be applied by the query that later selects from the view.",
  },
  {
    q: "A view built from a single table with no aggregation or DISTINCT is generally...",
    options: [
      "Never queryable",
      "Updatable — INSERT/UPDATE/DELETE through it are translated onto the underlying table",
      "Automatically materialized permanently",
      "Only usable in PostgreSQL, not any other dialect",
    ],
    answer: 1,
    explain: "Simple single-table views without aggregation are usually updatable; multi-table joins or aggregated views generally are not directly updatable.",
  },
  {
    q: "What is the main problem with using a plain INNER JOIN between PROJECT and ASSIGNMENT when a brand-new project has no assignments yet?",
    options: [
      "It causes a syntax error",
      "The new project silently disappears from the result set because there's nothing to match on the right side",
      "It duplicates the new project's row many times",
      "It automatically inserts a placeholder assignment row",
    ],
    answer: 1,
    explain: "An inner join only returns rows with a match on both sides, so a project with zero matching assignment rows is dropped entirely from the output.",
  },
  {
    q: "Which join keeps every row from the left-hand table, filling unmatched right-hand columns with NULL?",
    options: ["INNER JOIN", "LEFT JOIN", "CROSS JOIN", "SELF JOIN"],
    answer: 1,
    explain: "LEFT JOIN preserves every row of the left table even when there's no match on the right, showing NULLs in place of unmatched right-side columns.",
  },
  {
    q: "What is an 'anti-join' typically used for?",
    options: [
      "Finding rows that DO match between two tables",
      "Finding rows in one table that have NO corresponding match in another (e.g., via NOT EXISTS)",
      "Deleting all rows from a joined result",
      "Sorting a joined result in reverse order",
    ],
    answer: 1,
    explain: "An anti-join, typically written with NOT EXISTS or a LEFT JOIN ... WHERE right.key IS NULL, finds rows in one table with no match in another.",
  },
  {
    q: "What makes a subquery 'correlated' rather than a regular (uncorrelated) subquery?",
    options: [
      "It uses a UNION instead of a JOIN",
      "It references a column from the outer query, effectively re-evaluating once per outer row",
      "It must always use EXISTS",
      "It can only be written against views, never base tables",
    ],
    answer: 1,
    explain: "A correlated subquery references the outer query's current row, so conceptually it re-runs for each row processed by the outer query.",
  },
  {
    q: "What does EXISTS test for in a correlated subquery?",
    options: [
      "The specific values returned by the subquery",
      "Only whether the subquery returns any rows at all",
      "Whether the subquery contains a syntax error",
      "Whether the outer table is empty",
    ],
    answer: 1,
    explain: "EXISTS/NOT EXISTS only check for the presence or absence of rows returned by the subquery — the actual values returned are irrelevant.",
  },
  {
    q: "In a recursive relationship like 'employee supervises employee', how is the relationship represented in the table design?",
    options: [
      "A separate SUPERVISOR table is always required",
      "A foreign key column in the EMPLOYEE table references EMPLOYEE's own primary key",
      "It cannot be represented in a relational database",
      "It requires a NoSQL graph database",
    ],
    answer: 1,
    explain: "A recursive (unary) relationship uses a foreign key that references the same table it lives in — e.g., supervisor_id referencing employee_number in the same EMPLOYEE table.",
  },
  {
    q: "What SQL construct is required to list every employee alongside their supervisor's name, both coming from the same EMPLOYEE table?",
    options: [
      "A UNION of two separate queries",
      "A self-join — the table joined to itself using two different aliases",
      "A CROSS JOIN with a dimension table",
      "A CHECK constraint",
    ],
    answer: 1,
    explain: "A self-join joins a table to itself, distinguished by aliases (e.g., e and s), letting you retrieve related rows from the same table.",
  },
  {
    q: "Why does a fixed-depth chain of self-joins fail for exploring an entire, arbitrarily deep management hierarchy?",
    options: [
      "Self-joins are not supported by any SQL dialect",
      "It only reaches as many levels as you explicitly wrote joins for — it can't adapt to hierarchies of unknown depth",
      "Self-joins always return zero rows for hierarchical data",
      "PostgreSQL disallows more than two self-joins",
    ],
    answer: 1,
    explain: "Stacking a fixed number of self-joins only reaches a fixed depth; a recursive CTE (WITH RECURSIVE) is needed to walk a hierarchy of unknown or variable depth.",
  },
  {
    q: "What are the two parts of a WITH RECURSIVE common table expression?",
    options: [
      "A CHECK constraint and a trigger",
      "An anchor member (starting point) and a recursive member (references the CTE itself)",
      "A SELECT and a DELETE",
      "A view and a materialized view",
    ],
    answer: 1,
    explain: "Every recursive CTE has a non-recursive anchor member that starts the process and a recursive member that repeatedly references the CTE's own growing result.",
  },
  {
    q: "In a recursive CTE walking a hierarchy, what stops the recursion from continuing forever?",
    options: [
      "The database engine always stops after exactly one iteration",
      "The engine stops once an iteration of the recursive member produces zero new rows (plus any explicit guard you add)",
      "Recursive CTEs run for a fixed, hardcoded 10 iterations always",
      "Recursion never actually stops; it must be manually cancelled",
    ],
    answer: 1,
    explain: "The recursive member re-runs until it produces no new rows; adding an explicit depth guard (e.g., WHERE level < 20) protects against cyclical/bad data causing infinite loops.",
  },
  {
    q: "Which SQL Server clause explicitly limits how many levels a recursive CTE can recurse?",
    options: ["MAXRECURSION", "LIMIT RECURSION", "STOP AFTER", "RECURSE_LIMIT"],
    answer: 0,
    explain: "SQL Server supports OPTION (MAXRECURSION n) to cap recursive CTE depth; PostgreSQL has no equivalent session setting and relies on an explicit WHERE guard instead.",
  },
  {
    q: "What must be true of two SELECT statements combined with a set operator like UNION or INTERSECT?",
    options: [
      "They must query the exact same table",
      "They must return the same number of columns, in the same order, with compatible data types",
      "They must both use GROUP BY",
      "They must both include an ORDER BY clause",
    ],
    answer: 1,
    explain: "Set operators require column-count, column-order, and data-type compatibility between the combined queries' result sets.",
  },
  {
    q: "What is the practical difference between UNION and UNION ALL?",
    options: [
      "UNION ALL requires fewer columns than UNION",
      "UNION removes duplicate rows from the combined result; UNION ALL keeps every row, including duplicates",
      "UNION can only combine two queries; UNION ALL can combine any number",
      "There is no difference — they are aliases for the same operator",
    ],
    answer: 1,
    explain: "UNION performs a deduplication pass across the combined results; UNION ALL skips that pass, keeping duplicates and running faster.",
  },
  {
    q: "Which set operator returns only rows that appear in both of two result sets?",
    options: ["UNION", "UNION ALL", "INTERSECT", "EXCEPT"],
    answer: 2,
    explain: "INTERSECT returns only the rows common to both queries — equivalent to a logical AND between the two sets.",
  },
  {
    q: "Which set operator returns rows from the first query that do NOT appear in the second?",
    options: ["INTERSECT", "EXCEPT", "UNION", "CROSS JOIN"],
    answer: 1,
    explain: "EXCEPT (MINUS in Oracle) returns the rows present in the first query's result but absent from the second — a set difference.",
  },
  {
    q: "Which version of MySQL first added support for the INTERSECT and EXCEPT set operators?",
    options: ["MySQL 5.7", "MySQL 8.0.0", "MySQL 8.0.31", "MySQL has never supported them"],
    answer: 2,
    explain: "MySQL did not support INTERSECT or EXCEPT until version 8.0.31 (released October 2022) — earlier versions required workarounds using JOIN/EXISTS/NOT EXISTS.",
  },
  {
    q: "What keyword does Oracle use in place of the standard EXCEPT operator?",
    options: ["MINUS", "DIFF", "SUBTRACT", "NOT UNION"],
    answer: 0,
    explain: "Oracle uses MINUS for set difference; the logic is identical to the standard EXCEPT operator used by PostgreSQL and SQL Server.",
  },
  {
    q: "A window function's OVER (PARTITION BY ... ORDER BY ...) clause is most similar to which other SQL clause, except that it doesn't collapse rows into one per group?",
    options: ["WHERE", "GROUP BY", "HAVING", "ORDER BY alone"],
    answer: 1,
    explain: "PARTITION BY defines groups the same way GROUP BY does, but every row of the input remains in the output instead of being collapsed into one row per group.",
  },
  {
    q: "Given three employees tied for the highest hours in a department, how do RANK() and DENSE_RANK() differ in the rank assigned to the row that comes after the tie?",
    options: [
      "They always behave identically",
      "RANK() skips ranks after a tie (e.g., 1, 1, 1, 4); DENSE_RANK() does not skip (e.g., 1, 1, 1, 2)",
      "DENSE_RANK() skips ranks; RANK() never does",
      "Both assign a unique, arbitrary number to every row regardless of ties",
    ],
    answer: 1,
    explain: "RANK() leaves gaps in the ranking sequence after ties (matching the count of tied rows); DENSE_RANK() assigns the next consecutive rank with no gap.",
  },
  {
    q: "Which window function looks backward to a previous row within the same ordered partition?",
    options: ["LEAD()", "LAG()", "RANK()", "ROW_NUMBER()"],
    answer: 1,
    explain: "LAG() retrieves a value from an earlier row in the window (e.g., the prior period), while LEAD() retrieves a value from a later row.",
  },
  {
    q: "How is a running total typically built with a window function?",
    options: [
      "SUM() OVER (ORDER BY date_column) with no PARTITION BY narrowing the window, so each row's window is 'everything up to and including this row'",
      "COUNT(*) OVER (PARTITION BY date_column)",
      "AVG() with a HAVING clause",
      "Running totals cannot be computed with window functions",
    ],
    answer: 0,
    explain: "Ordering without a narrowing PARTITION BY makes each row's frame include all prior rows plus itself, producing a cumulative/running total.",
  },
  {
    q: "In MySQL, why must a stored function's body be wrapped with a temporary DELIMITER change (e.g., DELIMITER $$)?",
    options: [
      "MySQL requires all functions to be written in Java",
      "MySQL's default statement terminator (;) would otherwise end the function body before it's complete",
      "DELIMITER is required only for views, not functions",
      "It has no real purpose and is purely stylistic",
    ],
    answer: 1,
    explain: "Because a function body itself contains semicolons ending its internal statements, MySQL requires temporarily switching the statement delimiter so the CREATE FUNCTION statement isn't cut off early.",
  },
  {
    q: "Which ALTER TABLE statement correctly adds a new nullable column `bonus_eligible` of type BOOLEAN to the WP `employee` table?",
    options: [
      "ALTER TABLE employee ADD COLUMN bonus_eligible BOOLEAN;",
      "ALTER TABLE employee NEW COLUMN bonus_eligible BOOLEAN;",
      "ALTER employee INSERT COLUMN bonus_eligible BOOLEAN;",
      "UPDATE employee ADD bonus_eligible BOOLEAN;",
    ],
    answer: 0,
    explain: "ALTER TABLE ... ADD COLUMN {name} {type} is the standard syntax for adding a new column to an existing table.",
  },
  {
    q: "You must add a NOT NULL column `region` to the `department` table, which already has rows. What is step 2 of the standard three-step process?",
    options: [
      "Drop the table and recreate it",
      "Backfill every existing row with a real value using UPDATE",
      "Immediately apply the NOT NULL constraint",
      "Rename the table",
    ],
    answer: 1,
    explain: "The three steps are: add the column allowing NULLs, backfill existing rows with real values (step 2), then enforce NOT NULL once every row has a value.",
  },
  {
    q: "In PostgreSQL, which clause changes an existing column's data type?",
    options: ["ALTER COLUMN ... TYPE", "MODIFY COLUMN", "CHANGE COLUMN", "SET COLUMN TYPE"],
    answer: 0,
    explain: "PostgreSQL uses ALTER TABLE ... ALTER COLUMN {name} TYPE {new_type} to change a column's data type.",
  },
  {
    q: "Which dialect historically favors MODIFY COLUMN instead of ALTER COLUMN ... TYPE for changing a column's data type?",
    options: ["PostgreSQL", "MySQL", "SQLite", "MongoDB"],
    answer: 1,
    explain: "MySQL accepts (and historically favored) MODIFY COLUMN office_phone VARCHAR(20) rather than the ALTER COLUMN ... TYPE syntax PostgreSQL uses.",
  },
  {
    q: "How does SQL Server's syntax for changing a column's type differ from PostgreSQL's?",
    options: [
      "SQL Server uses ALTER COLUMN office_phone VARCHAR(20) with no separate TYPE keyword",
      "SQL Server cannot change column types at all",
      "SQL Server requires dropping and recreating the table",
      "SQL Server and PostgreSQL use identical syntax with no differences",
    ],
    answer: 0,
    explain: "SQL Server's ALTER COLUMN clause omits the separate TYPE keyword that PostgreSQL requires, e.g. ALTER COLUMN office_phone VARCHAR(20).",
  },
  {
    q: "Which statement adds a named CHECK constraint ensuring a project's start_date is before its end_date, on a table that already exists?",
    options: [
      "ALTER TABLE project ADD CONSTRAINT check_project_dates CHECK (start_date < end_date);",
      "CREATE CONSTRAINT check_project_dates ON project (start_date < end_date);",
      "ALTER TABLE project INSERT CHECK (start_date < end_date);",
      "UPDATE project SET CONSTRAINT check_project_dates = (start_date < end_date);",
    ],
    answer: 0,
    explain: "ALTER TABLE ... ADD CONSTRAINT {name} CHECK (...) is the correct way to add a table-level CHECK constraint to an existing table.",
  },
  {
    q: "Which statement removes a previously-added named constraint from a table?",
    options: [
      "ALTER TABLE project DROP CONSTRAINT check_project_dates;",
      "ALTER TABLE project REMOVE CONSTRAINT check_project_dates;",
      "DELETE CONSTRAINT check_project_dates FROM project;",
      "DROP TABLE project CONSTRAINT check_project_dates;",
    ],
    answer: 0,
    explain: "ALTER TABLE ... DROP CONSTRAINT {name} removes a previously added constraint by its name.",
  },
  {
    q: "Which forms are described as the most portable across PostgreSQL, MySQL, and SQL Server for adding or dropping columns and constraints?",
    options: [
      "ADD COLUMN / DROP COLUMN and ADD CONSTRAINT / DROP CONSTRAINT",
      "MODIFY COLUMN exclusively",
      "CHANGE COLUMN exclusively",
      "There is no portable syntax at all across dialects",
    ],
    answer: 0,
    explain: "While type-change syntax varies significantly (ALTER COLUMN TYPE vs. MODIFY COLUMN vs. bare ALTER COLUMN), the ADD/DROP COLUMN and ADD/DROP CONSTRAINT forms are the most portable across the three dialects.",
  },
  {
    q: "Why is checking for a row's existence with a SELECT, then issuing a separate INSERT or UPDATE, considered unsafe under concurrent access?",
    options: [
      "SELECT statements are always slower than INSERT statements",
      "Another transaction could insert the same row between the SELECT check and the subsequent INSERT/UPDATE, creating a race condition",
      "SQL forbids running a SELECT before an INSERT",
      "It uses too much disk space",
    ],
    answer: 1,
    explain: "Between the check and the write, a concurrent transaction can slip in and change the same row, so the separate check-then-write pattern is a race condition; MERGE/upsert statements close that gap atomically.",
  },
  {
    q: "In PostgreSQL, what does this statement do?\n\nINSERT INTO department (department_id, department_name)\nVALUES (6, 'Analytics')\nON CONFLICT (department_id)\nDO UPDATE SET department_name = EXCLUDED.department_name;",
    options: [
      "It always inserts a new row, ignoring conflicts",
      "It inserts department 6 if it doesn't exist, or updates its department_name to 'Analytics' if department_id 6 already exists",
      "It deletes department 6 if it already exists",
      "It raises an error if department_id 6 already exists",
    ],
    answer: 1,
    explain: "ON CONFLICT (department_id) DO UPDATE performs an upsert: insert the new row, or if department_id 6 already exists, update department_name using EXCLUDED (the values that would have been inserted).",
  },
  {
    q: "Rewriting a PostgreSQL ON CONFLICT upsert for MySQL, which clause replaces ON CONFLICT ... DO UPDATE?",
    options: ["MERGE INTO ... WHEN MATCHED", "ON DUPLICATE KEY UPDATE", "REPLACE CONFLICT", "UPSERT INTO"],
    answer: 1,
    explain: "MySQL's closest equivalent to ON CONFLICT ... DO UPDATE is ON DUPLICATE KEY UPDATE, which also requires a unique or primary key to detect the conflict.",
  },
  {
    q: "In MySQL's ON DUPLICATE KEY UPDATE clause, which function references the value that was about to be inserted (the MySQL equivalent of Postgres's EXCLUDED)?",
    options: ["VALUES(column_name)", "EXCLUDED(column_name)", "NEW(column_name)", "SOURCE(column_name)"],
    answer: 0,
    explain: "MySQL uses VALUES(column_name) inside ON DUPLICATE KEY UPDATE to reference the incoming row's proposed value, playing the same role as PostgreSQL's EXCLUDED.",
  },
  {
    q: "Which of the following is true about the standard MERGE statement in SQL Server and Oracle, compared to ON CONFLICT or ON DUPLICATE KEY UPDATE?",
    options: [
      "MERGE can only affect a single hard-coded row per statement",
      "MERGE can drive its insert/update/delete logic off an entire source table or query result, and can even include WHEN MATCHED ... DELETE",
      "MERGE is not supported by any major relational database",
      "MERGE is identical in behavior to UNION ALL",
    ],
    answer: 1,
    explain: "MERGE is the most general of the three upsert approaches — it can be driven by a whole source table/query and supports matched, not-matched, and even delete branches.",
  },
  {
    q: "A MERGE statement includes both a WHEN MATCHED THEN UPDATE clause and a WHEN NOT MATCHED THEN INSERT clause. What determines which branch runs for a given source row?",
    options: [
      "Whichever branch is listed first in the statement always runs",
      "Whether the ON condition finds a matching row already in the target table for that source row",
      "The alphabetical order of the column names",
      "MERGE runs both branches for every row regardless of matching",
    ],
    answer: 1,
    explain: "MERGE evaluates the ON condition per source row: a match triggers WHEN MATCHED logic (e.g. UPDATE), and no match triggers WHEN NOT MATCHED logic (e.g. INSERT).",
  },
  {
    q: "Which database product has NO standard MERGE statement at all, relying instead on ON DUPLICATE KEY UPDATE?",
    options: ["Oracle", "SQL Server", "MySQL", "PostgreSQL (in newer versions)"],
    answer: 2,
    explain: "MySQL has no MERGE statement; ON DUPLICATE KEY UPDATE is its closest equivalent. Oracle and SQL Server both support standard MERGE.",
  },
  {
    q: "What is a SQL view, fundamentally?",
    options: [
      "A saved SELECT statement presented as a virtual table, storing no data of its own",
      "A physical, duplicated copy of a table's rows",
      "An index used to accelerate JOIN operations",
      "A scheduled backup job",
    ],
    answer: 0,
    explain: "A view stores no data itself — every time it's queried, the database runs the underlying saved SELECT statement and presents the result as if it were a table.",
  },
  {
    q: "Which of these is NOT one of the three main reasons views are useful, as commonly taught?",
    options: [
      "Hiding the complexity of a multi-table join behind a single reusable name",
      "Ensuring every downstream report uses the exact same join logic (consistency)",
      "Exposing only certain rows/columns of a sensitive table without granting direct table access (security)",
      "Guaranteeing the query behind the view runs faster than any equivalent index",
    ],
    answer: 3,
    explain: "Views don't inherently make queries faster than an equivalent indexed query — their core benefits are hiding complexity, ensuring consistency, and providing a security boundary, not a performance guarantee.",
  },
  {
    q: "Which clause is standard SQL disallow inside the SELECT statement that defines a view?",
    options: ["WHERE", "JOIN", "ORDER BY", "Column aliases"],
    answer: 2,
    explain: "Standard SQL doesn't permit ORDER BY inside a view's definition — sort order belongs to the query that later selects from the view, not the view itself.",
  },
  {
    q: "CREATE VIEW employee_project_hours_view AS SELECT p.project_name, e.first_name, e.last_name, a.hours_worked FROM employee e JOIN assignment a ON ... JOIN project p ON ...; Is this view directly updatable via INSERT/UPDATE/DELETE?",
    options: [
      "Yes, because it's still ultimately backed by real tables",
      "No — it joins multiple tables, so there's no single unambiguous underlying row to update",
      "Yes, but only on Tuesdays per the SQL standard",
      "No view is ever queryable at all",
    ],
    answer: 1,
    explain: "Views built from multi-table joins (or with aggregation/DISTINCT) are generally not directly updatable, since a change wouldn't map unambiguously back onto one underlying row.",
  },
  {
    q: "A view is built from a single table with no aggregation, DISTINCT, or GROUP BY. What is generally true of it?",
    options: [
      "It is usually updatable — changes made through it are translated onto the underlying table",
      "It can never be queried with a WHERE clause",
      "It always duplicates the underlying table's storage",
      "It must always include an ORDER BY",
    ],
    answer: 0,
    explain: "Simple single-table views without aggregation are usually updatable, and PostgreSQL translates INSERT/UPDATE/DELETE through them onto the base table.",
  },
  {
    q: "What PostgreSQL feature lets you define custom update behavior for a view that would otherwise not be automatically updatable (e.g., a joined or aggregated view)?",
    options: ["INSTEAD OF triggers", "GROUP BY ROLLUP", "MAXRECURSION", "The EXCLUDED keyword"],
    answer: 0,
    explain: "PostgreSQL supports CREATE VIEW ... WITH CHECK OPTION and INSTEAD OF triggers on views to define custom logic for updates that wouldn't otherwise be automatically applied.",
  },
  {
    q: "Wedgewood Pacific creates a brand-new PROJECT row with zero ASSIGNMENT rows yet. What happens if you run an INNER JOIN between project and assignment?",
    options: [
      "The new project appears with NULLs in the assignment columns",
      "The new project is silently dropped from the result set entirely",
      "The query raises a foreign key violation error",
      "The new project appears twice",
    ],
    answer: 1,
    explain: "An inner join only returns rows with a match on both sides, so a project with no matching assignment rows disappears from the output entirely — the classic motivation for using a LEFT JOIN instead.",
  },
  {
    q: "Which join keeps every row of the RIGHT-hand table, filling in NULLs for unmatched left-hand columns?",
    options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "CROSS JOIN"],
    answer: 1,
    explain: "RIGHT JOIN is the mirror image of LEFT JOIN — it preserves every row from the right-hand table, useful when you'd rather not reorder the FROM clause.",
  },
  {
    q: "Which pattern is the classic 'anti-join' equivalent of a LEFT JOIN ... WHERE right_key IS NULL?",
    options: ["INNER JOIN with a HAVING clause", "NOT EXISTS with a correlated subquery", "CROSS JOIN with DISTINCT", "UNION ALL of two identical queries"],
    answer: 1,
    explain: "NOT EXISTS with a correlated subquery is the anti-join idiom for 'rows on the left with no match on the right,' often considered clearer and sometimes faster than LEFT JOIN ... WHERE right.key IS NULL.",
  },
  {
    q: "SELECT p.project_id, p.project_name FROM project p WHERE NOT EXISTS (SELECT 1 FROM assignment a WHERE a.project_id = p.project_id); What does this query return?",
    options: [
      "Every project that has at least one assignment",
      "Every project that currently has zero assignments",
      "Every assignment with no matching project",
      "A syntax error, because NOT EXISTS requires a JOIN",
    ],
    answer: 1,
    explain: "This is the anti-join pattern: NOT EXISTS is true only when the correlated subquery finds no matching assignment rows for that project, so it returns projects with zero assignments.",
  },
  {
    q: "Why are LEFT JOIN X and RIGHT JOIN Y ... FROM X often described as interchangeable?",
    options: [
      "They are never actually interchangeable under any circumstances",
      "Swapping the table order in the FROM clause lets a RIGHT JOIN express the same logical result as an equivalent LEFT JOIN",
      "RIGHT JOIN is deprecated in all modern SQL dialects",
      "LEFT JOIN and RIGHT JOIN always return identical row counts regardless of table order",
    ],
    answer: 1,
    explain: "The same logical outer-join result can be written as either a LEFT JOIN or a RIGHT JOIN depending on which table is listed first in the FROM clause — most style guides prefer sticking to LEFT JOIN for readability.",
  },
  {
    q: "What makes a subquery 'correlated' as opposed to an ordinary, self-contained subquery?",
    options: [
      "It must use a set operator like INTERSECT",
      "It references a column from the outer query, so it conceptually re-evaluates once per row processed by the outer query",
      "It can only ever return a single scalar value",
      "It must be written using a CTE (WITH clause)",
    ],
    answer: 1,
    explain: "A correlated subquery reaches out to the outer query's current row (e.g., WHERE a.employee_number = e.employee_number), which conceptually forces it to re-run for each outer row, unlike an uncorrelated subquery that runs once.",
  },
  {
    q: "SELECT e1.employee_number, e1.last_name FROM employee e1 WHERE EXISTS (SELECT 1 FROM employee e2 WHERE e1.position = e2.position AND e1.employee_number <> e2.employee_number); What does this return?",
    options: [
      "Employees whose position is unique in the company",
      "Employees who share their position with at least one other employee",
      "All employees, regardless of position",
      "Only the employee with the lowest employee_number in each position",
    ],
    answer: 1,
    explain: "The correlated EXISTS subquery checks, for each e1 row, whether some other employee (e2, excluded by employee_number) shares the same position — true only when the position isn't unique to that employee.",
  },
  {
    q: "What does EXISTS actually check for, in a correlated subquery like WHERE EXISTS (SELECT 1 FROM assignment a WHERE a.project_id = p.project_id)?",
    options: [
      "The specific SUM of hours_worked returned by the subquery",
      "Only whether the subquery returns at least one row at all — the actual selected values are irrelevant",
      "Whether the project table has any foreign keys",
      "Whether the assignment table is completely empty",
    ],
    answer: 1,
    explain: "EXISTS only tests for the presence of at least one row from the subquery; because of that, it's idiomatic (and harmless) to SELECT a constant like 1 inside an EXISTS subquery.",
  },
  {
    q: "Which of these tasks would a correlated subquery-based 'top earner per department' query need to repeat once for every employee row, that a window function computes in a single pass instead?",
    options: [
      "Reading the CREATE TABLE statement",
      "Recomputing the department's maximum total-hours figure via a nested subquery",
      "Adding a new column to the employee table",
      "Committing the transaction",
    ],
    answer: 1,
    explain: "The correlated-subquery version has to re-derive each department's maximum total hours per outer row, which is exactly the repeated work a single RANK() OVER (PARTITION BY ...) avoids by computing it once per partition.",
  },
  {
    q: "Which dialects support EXISTS, NOT EXISTS, and correlated subqueries with essentially identical syntax?",
    options: [
      "Only PostgreSQL",
      "PostgreSQL, MySQL 8+, SQL Server, and Oracle all support the same syntax",
      "Only NoSQL document databases support correlated subqueries",
      "Only Oracle supports correlated subqueries",
    ],
    answer: 1,
    explain: "EXISTS/NOT EXISTS and correlated subqueries are one of the more portable corners of advanced SQL, working identically across PostgreSQL, MySQL 8+, SQL Server, and Oracle.",
  },
  {
    q: "In a recursive CTE that walks DOWN an org chart (finding everyone who reports to a given manager), what does the recursive member's JOIN condition typically look like?",
    options: [
      "e.supervisor_id = oc.employee_number, linking a new employee row to a manager already found in the growing CTE result",
      "e.employee_number = oc.supervisor_id, the reverse of the down-the-chart direction",
      "There is no JOIN in the recursive member",
      "e.department_id = oc.department_id",
    ],
    answer: 0,
    explain: "Walking down the chart means finding employees whose supervisor_id matches someone already added to the CTE result, so each pass adds the next layer down.",
  },
  {
    q: "What combinator connects the anchor member and the recursive member inside a WITH RECURSIVE CTE?",
    options: ["INTERSECT", "UNION ALL", "EXCEPT", "CROSS JOIN"],
    answer: 1,
    explain: "The anchor (non-recursive starting query) and the recursive member are combined with UNION ALL inside the CTE definition.",
  },
  {
    q: "A recursive CTE walking an org chart has a data-entry error creating a cycle: employee A supervises B, and B is listed as A's supervisor. What happens without an explicit guard?",
    options: [
      "PostgreSQL automatically detects and breaks the cycle without any guard",
      "The recursion could loop forever, since the recursive member keeps finding 'new' rows that reference each other",
      "The query returns a syntax error before execution",
      "The cycle is silently ignored and only one row is returned",
    ],
    answer: 1,
    explain: "A genuine cycle in the data can make the recursive member keep matching rows forever unless you add an explicit guard, such as WHERE oc.level < 20.",
  },
  {
    q: "Which SQL Server option explicitly caps how many levels a recursive CTE is allowed to recurse?",
    options: ["OPTION (MAXRECURSION n)", "SET recursion_limit = n", "LIMIT RECURSE n", "WITH DEPTH n"],
    answer: 0,
    explain: "SQL Server supports OPTION (MAXRECURSION n) to cap recursion depth; PostgreSQL has no equivalent session setting, so an explicit WHERE guard in the recursive member is the only protection there.",
  },
  {
    q: "A bill-of-materials hierarchy, where a PART can contain sub-PARTs which contain further sub-parts, is structurally most similar to which other recursive-CTE example from this module?",
    options: [
      "A star schema's fact and dimension tables",
      "An org chart walking parent_part_id / part_id the same way employee walks supervisor_id / employee_number",
      "A MERGE statement's WHEN MATCHED clause",
      "A CUBE aggregation",
    ],
    answer: 1,
    explain: "Bill-of-materials hierarchies are structurally identical to an org chart recursive CTE — just walking a parent/child part_id / parent_part_id relationship instead of employee_number / supervisor_id.",
  },
  {
    q: "What causes a WITH RECURSIVE query to naturally stop iterating, apart from any explicit guard you add?",
    options: [
      "The engine always stops after exactly 3 iterations by default",
      "An iteration of the recursive member produces zero new rows",
      "The anchor member is re-run one final time",
      "Recursive CTEs never stop on their own; a guard is always mandatory",
    ],
    answer: 1,
    explain: "The recursive member keeps re-running, fed by the previous iteration's new rows, until an iteration produces no new rows at all, at which point the engine stops naturally.",
  },
  {
    q: "Which two elements together make up every WITH RECURSIVE CTE?",
    options: [
      "A CHECK constraint and a foreign key",
      "A non-recursive anchor member and a recursive member that references the CTE's own name",
      "A view and a materialized view",
      "An INSERT and a DELETE statement",
    ],
    answer: 1,
    explain: "Every recursive CTE has an anchor member that starts the process (non-recursive) and a recursive member that repeatedly references the CTE itself to keep building on prior results.",
  },
  {
    q: "What must be true of two SELECT statements before they can be combined with UNION, INTERSECT, or EXCEPT?",
    options: [
      "They must be the exact same query written twice",
      "They must return the same number of columns, in the same order, with compatible data types",
      "They must both include a GROUP BY clause",
      "They must both query the same single table",
    ],
    answer: 1,
    explain: "Set operators require matching column count, matching column order, and compatible data types between the combined queries — table names and WHERE clauses can differ freely.",
  },
  {
    q: "Why should UNION ALL generally be preferred over UNION unless duplicates specifically need to be removed?",
    options: [
      "UNION ALL requires fewer columns to match",
      "UNION's deduplication pass compares every row against every other row, which costs real performance on large result sets",
      "UNION ALL is part of a newer SQL standard that UNION doesn't support",
      "UNION cannot combine more than two queries",
    ],
    answer: 1,
    explain: "UNION performs a dedup step across the combined rows, which is expensive at scale; UNION ALL skips that step entirely, so it should be the default unless duplicates truly must be removed.",
  },
  {
    q: "SELECT city FROM customer UNION SELECT city FROM employee; If 'Chicago' appears in both tables, how many times does 'Chicago' appear in the result?",
    options: ["Zero times", "Exactly once", "Exactly twice", "It depends on the number of employees in Chicago"],
    answer: 1,
    explain: "UNION removes duplicate rows from the combined result, so a city value present in both source queries appears only once in the final output.",
  },
  {
    q: "SELECT email_address FROM employee INTERSECT SELECT email_address FROM customer; What does this query return?",
    options: [
      "Every email address from either table, with duplicates removed",
      "Only email addresses that appear in BOTH the employee and customer tables",
      "Only email addresses unique to the employee table",
      "An error, because INTERSECT requires identical table names",
    ],
    answer: 1,
    explain: "INTERSECT returns only the rows common to both queries — in this case, addresses appearing in both employee and customer, i.e. people who are both an employee and a customer.",
  },
  {
    q: "SELECT department_id FROM department EXCEPT SELECT department_id FROM employee; What does this return?",
    options: [
      "Department IDs that have at least one employee",
      "Department IDs that exist in department but have no matching employee row",
      "Employee IDs with no department",
      "Every department_id, duplicated once per employee",
    ],
    answer: 1,
    explain: "EXCEPT returns rows from the first query not present in the second — here, departments with no corresponding employee rows, a set-based alternative to a NOT EXISTS anti-join.",
  },
  {
    q: "What keyword does Oracle use instead of EXCEPT to express the exact same set-difference logic?",
    options: ["DIFF", "MINUS", "SUBTRACT", "NOT IN"],
    answer: 1,
    explain: "Oracle spells set difference as MINUS rather than EXCEPT; the underlying logic is identical to PostgreSQL and SQL Server's EXCEPT.",
  },
  {
    q: "Before MySQL 8.0.31, how would a developer typically fake an EXCEPT / MINUS-style set difference?",
    options: [
      "Using NOT EXISTS or a LEFT JOIN ... WHERE right.key IS NULL",
      "It was genuinely impossible to express set difference before that version",
      "By upgrading to Oracle temporarily",
      "Using GROUP BY ROLLUP",
    ],
    answer: 0,
    explain: "MySQL didn't support INTERSECT or EXCEPT until version 8.0.31 (October 2022); before that, developers faked EXCEPT/MINUS with NOT EXISTS or a LEFT JOIN ... WHERE right.key IS NULL, and faked INTERSECT with an INNER JOIN or EXISTS.",
  },
  {
    q: "Which SQL Server version first introduced support for UNION, INTERSECT, and EXCEPT?",
    options: ["SQL Server 2000", "SQL Server 2005", "SQL Server 2016", "SQL Server has never supported EXCEPT"],
    answer: 1,
    explain: "SQL Server has supported UNION, INTERSECT, and EXCEPT since SQL Server 2005.",
  },
  {
    q: "What is the closest non-window-function analogy to a window function's OVER (PARTITION BY ...) clause?",
    options: [
      "GROUP BY, except every input row remains in the output instead of being collapsed into one row per group",
      "ORDER BY alone, with no grouping semantics whatsoever",
      "WHERE, filtering rows before aggregation",
      "HAVING, filtering groups after aggregation",
    ],
    answer: 0,
    explain: "PARTITION BY defines groups the same way GROUP BY does, but window functions keep every row instead of collapsing each group down into a single output row.",
  },
  {
    q: "Three employees are tied for the most hours worked in a department. How does ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY total_hours DESC) handle the tie?",
    options: [
      "It assigns the same number to all three tied rows",
      "It assigns a different number to each tied row anyway, using an arbitrary tiebreak",
      "It raises an error because of the tie",
      "It skips numbers proportional to the number of ties",
    ],
    answer: 1,
    explain: "Unlike RANK() or DENSE_RANK(), ROW_NUMBER() always assigns a unique, sequential number to every row even when there's a tie in the ORDER BY column — the tiebreak order is otherwise arbitrary.",
  },
  {
    q: "Given ranks 1, 2, 2, 4 produced for four rows with a tie at rank 2, which ranking function produced this exact sequence?",
    options: ["ROW_NUMBER()", "RANK()", "DENSE_RANK()", "LAG()"],
    answer: 1,
    explain: "RANK() leaves a gap after ties equal to the number of tied rows — two rows tied at rank 2 causes the next rank to jump to 4, which is exactly this sequence.",
  },
  {
    q: "Given ranks 1, 2, 2, 3 produced for four rows with a tie at rank 2, which ranking function produced this sequence?",
    options: ["ROW_NUMBER()", "RANK()", "DENSE_RANK()", "LEAD()"],
    answer: 2,
    explain: "DENSE_RANK() assigns the same rank to tied rows but does not skip the next rank number afterward, producing a consecutive sequence like 1, 2, 2, 3.",
  },
  {
    q: "SELECT d.year, d.month_name, SUM(f.sale_amount) AS monthly_revenue, LAG(SUM(f.sale_amount)) OVER (ORDER BY d.year, d.quarter) AS prior_period_revenue FROM fact_sales f JOIN dim_date d ... GROUP BY d.year, d.month_name, d.quarter; What does the prior_period_revenue column show for the very first row in the ordering?",
    options: [
      "The same value as monthly_revenue for that row",
      "NULL, since there is no earlier row for LAG() to look back to",
      "Zero, always",
      "The value from the LAST row instead, wrapping around",
    ],
    answer: 1,
    explain: "LAG() looks backward to a previous row within the ordered window; for the very first row in the ordering, there is no prior row, so LAG() returns NULL.",
  },
  {
    q: "Which window function looks FORWARD to a later row within the same ordered partition?",
    options: ["LAG()", "LEAD()", "RANK()", "ROW_NUMBER()"],
    answer: 1,
    explain: "LEAD() retrieves a value from a later row in the ordered window, the mirror image of LAG(), which looks backward.",
  },
  {
    q: "SELECT d.full_date, SUM(f.sale_amount) AS daily_revenue, SUM(SUM(f.sale_amount)) OVER (ORDER BY d.full_date) AS running_total FROM fact_sales f JOIN dim_date d ... GROUP BY d.full_date ORDER BY d.full_date; What does running_total represent for a given row?",
    options: [
      "Only that single day's revenue, duplicated",
      "The cumulative sum of daily_revenue for that date and every date before it",
      "The average daily revenue across the entire table",
      "The revenue for the following day only",
    ],
    answer: 1,
    explain: "Ordering by full_date without a narrowing PARTITION BY makes each row's window include all prior rows plus itself, which is exactly how a running/cumulative total is built with a window function.",
  },
  {
    q: "Why must a ranked query like RANK() OVER (PARTITION BY department_id ORDER BY SUM(hours) DESC) AS hours_rank be wrapped in an outer subquery before filtering WHERE hours_rank = 1?",
    options: [
      "A window function's result can't be directly filtered by the same SELECT's WHERE clause, since window functions run after WHERE in logical query order",
      "RANK() cannot be combined with PARTITION BY",
      "WHERE clauses are not allowed in any query that includes a JOIN",
      "hours_rank must first be cast to an integer manually",
    ],
    answer: 0,
    explain: "Window functions are computed after WHERE/GROUP BY in logical processing order, so their computed alias (like hours_rank) can't be referenced in that same query's WHERE clause — an outer wrapping query is required to filter on it.",
  },
  {
    q: "Which set of window functions work with essentially identical syntax across PostgreSQL, SQL Server (2012+), MySQL (8.0+), and Oracle?",
    options: [
      "ROW_NUMBER, RANK, DENSE_RANK, LAG, and LEAD",
      "Only ROW_NUMBER — the others vary significantly by dialect",
      "None of them; every dialect has entirely different window syntax",
      "Only in Oracle and SQL Server, never in open-source databases",
    ],
    answer: 0,
    explain: "ROW_NUMBER, RANK, DENSE_RANK, LAG, and LEAD are described as genuinely portable, working with nearly identical syntax across all four major dialects covered in this course.",
  },
  {
    q: "In the 'top earner per department' window-function query, why does RANK() get layered on top of SUM(a.hours_worked) rather than the raw hours_worked column?",
    options: [
      "Window functions run after GROUP BY/aggregation in logical query order, so RANK() operates on the one row per employee that SUM() already produced",
      "RANK() cannot be used with any aggregate function under any circumstances",
      "SUM() must always be the very last function evaluated in a query",
      "PARTITION BY requires the column being ranked to be a raw, non-aggregated value",
    ],
    answer: 0,
    explain: "Because window functions run after GROUP BY/aggregation, RANK() here ranks the per-employee SUM(hours_worked) rows produced by the GROUP BY, rather than individual assignment rows.",
  },
  {
    q: "What is SQL/PSM, in the context of user-defined functions?",
    options: [
      "A NoSQL query language",
      "The SQL standard's umbrella term for code stored inside the database itself — functions, triggers, and stored procedures",
      "A synonym for a materialized view",
      "A cloud-only feature unavailable in on-premises databases",
    ],
    answer: 1,
    explain: "SQL/PSM (Persistent Stored Modules) is the standard's umbrella term for database-resident code: user-defined functions, triggers, and stored procedures.",
  },
  {
    q: "CREATE FUNCTION name_concatenation(p_first VARCHAR, p_last VARCHAR) RETURNS VARCHAR AS $$ BEGIN RETURN p_last || ', ' || p_first; END; $$ LANGUAGE plpgsql; What does calling name_concatenation('Ana', 'Silva') return?",
    options: ["'Ana, Silva'", "'Silva, Ana'", "'Ana Silva'", "NULL"],
    answer: 1,
    explain: "The function body returns p_last || ', ' || p_first, so passing first='Ana', last='Silva' produces 'Silva, Ana'.",
  },
  {
    q: "What procedural extension does plpgsql add to plain SQL inside a PostgreSQL function body?",
    options: [
      "Nothing — plpgsql is just an alias for standard SQL",
      "Variables, IF/LOOP control flow, and BEGIN...END blocks",
      "A completely separate query language unrelated to SQL",
      "Support only for SELECT statements, no other logic",
    ],
    answer: 1,
    explain: "plpgsql is Postgres's procedural extension to SQL, adding variables, conditional/loop control flow, and BEGIN...END blocks inside function bodies.",
  },
  {
    q: "Which keyword does Oracle's PL/SQL use in a function definition where PostgreSQL uses RETURNS?",
    options: ["RETURN", "OUTPUT", "YIELDS", "GIVES"],
    answer: 0,
    explain: "Oracle's PL/SQL syntax uses RETURN VARCHAR2 (singular) rather than PostgreSQL's RETURNS VARCHAR in the function header.",
  },
  {
    q: "Beyond user-defined functions, what other two categories of database-resident code does SQL/PSM cover?",
    options: [
      "Views and indexes",
      "Triggers and stored procedures",
      "Data marts and fact tables",
      "Foreign keys and CHECK constraints",
    ],
    answer: 1,
    explain: "SQL/PSM also covers triggers (code that fires automatically on INSERT/UPDATE/DELETE) and stored procedures (database-resident programs invoked directly), alongside user-defined functions.",
  },
  {
    q: "Project 08, the course's capstone, is described as deliberately combining which three advanced-SQL features into one deliverable?",
    options: [
      "A data mart, a hypervisor, and a NoSQL document store",
      "A view, a recursive CTE, and window functions",
      "MERGE, GROUP BY ROLLUP, and JSONB",
      "An anti-join, a hybrid cloud deployment, and MapReduce",
    ],
    answer: 1,
    explain: "The course wrap-up describes Project 08 as combining a view, a recursive CTE, and window functions into one deliverable — the final proof that these Module 08 pieces fit together.",
  },
  {
    q: "What is the general structure of a WITH RECURSIVE CTE used to walk an employee-management chain?",
    options: [
      "A single SELECT with no UNION, filtered by a WHERE clause",
      "A base case (anchor member) selecting the starting row(s), UNION ALL'd with a recursive member that joins the CTE back to the source table, repeating until no new rows are produced",
      "A CREATE FUNCTION statement with no SELECT at all",
      "A plain self join with no CTE required",
    ],
    answer: 1,
    explain: "A recursive CTE always has an anchor (non-recursive) member establishing the starting point, combined with UNION ALL to a recursive member that references the CTE's own name — repeating until the recursive member returns no additional rows.",
  },
  {
    q: "Why is UNION ALL used instead of plain UNION inside a recursive CTE's recursive member?",
    options: [
      "UNION is not valid SQL syntax inside a CTE",
      "UNION ALL avoids the overhead (and potential logic errors) of de-duplicating rows on every recursive step, and recursive CTEs are required to use UNION ALL by the SQL standard",
      "UNION ALL runs the query only once instead of repeatedly",
      "There is no difference; either works identically",
    ],
    answer: 1,
    explain: "The SQL standard requires UNION ALL (not UNION) between a recursive CTE's anchor and recursive members — this also avoids the cost of duplicate elimination on every iteration of the recursion.",
  },
  {
    q: "What does a NOT EXISTS anti-join pattern accomplish that a plain LEFT JOIN alone does not directly show?",
    options: [
      "It returns matched rows only, like an inner join",
      "It directly expresses 'rows in the left table with no corresponding row in the right table' as the query's intent, typically paired with a correlated subquery rather than a post-join NULL check",
      "It is functionally impossible to express the same result with a LEFT JOIN",
      "NOT EXISTS only works with numeric columns",
    ],
    answer: 1,
    explain: "NOT EXISTS (SELECT 1 FROM right_table WHERE right_table.fk = left_table.pk) reads as 'give me left-table rows where no matching right-table row exists' — logically equivalent to a LEFT JOIN ... WHERE right.col IS NULL anti-join pattern, just expressed as a correlated subquery instead of a post-join filter.",
  },
  {
    q: "Which statement about updatable views is accurate?",
    options: [
      "Every view, no matter how it's defined, can always be used in INSERT/UPDATE/DELETE statements",
      "A view is typically updatable only if it maps straightforwardly to a single underlying table without aggregation, DISTINCT, GROUP BY, or set operators obscuring the row-to-row mapping",
      "Views can never be queried with SELECT, only modified",
      "Updatable views require a stored procedure to function at all",
    ],
    answer: 1,
    explain: "A view built from a simple SELECT against one table (no aggregation, GROUP BY, DISTINCT, or joins that make the row mapping ambiguous) is generally updatable; views involving aggregation or multiple joined tables usually are not, or need special rules (like INSTEAD OF triggers) to become updatable.",
  },
];
