// ── Module 02 — The Relational Model (32) ────────────────────────────────
QUESTIONS["02"] = [
  {
    q: "In formal relational terminology, what is the equivalent of a 'table'?",
    options: ["Tuple", "Relation", "Domain", "Schema"],
    answer: 1,
    explain: "A relation is the formal term for what is casually called a table.",
  },
  {
    q: "In formal relational terminology, what is the equivalent of a 'row'?",
    options: ["Attribute", "Domain", "Tuple", "Relation"],
    answer: 2,
    explain: "A tuple is the formal term for a row, representing one occurrence of the relation's theme.",
  },
  {
    q: "In formal relational terminology, what is the equivalent of a 'column'?",
    options: ["Tuple", "Attribute", "Relation", "Key"],
    answer: 1,
    explain: "An attribute is the formal term for a column — a named characteristic shared by every tuple.",
  },
  {
    q: "What is the 'domain' of an attribute?",
    options: [
      "The website hosting the database",
      "The set of legal values the attribute can hold",
      "The primary key of the table",
      "The number of rows in the table",
    ],
    answer: 1,
    explain: "A domain is the set of allowable values for an attribute, similar to (but conceptually broader than) a SQL data type.",
  },
  {
    q: "Is every SQL 'table' guaranteed to be a formally valid 'relation'?",
    options: [
      "Yes, always, by definition",
      "Not necessarily — a table can violate relational rules (e.g., store non-atomic values) while SQL still calls it a table",
      "No, SQL tables are never relations",
      "Only if it has a foreign key",
    ],
    answer: 1,
    explain: "SQL and everyday usage apply the word 'table' loosely, even to structures that break formal relation rules like atomicity.",
  },
  {
    q: "Which of the following is NOT one of the four defining characteristics of a relation covered in this module?",
    options: [
      "No duplicate rows",
      "Row order doesn't matter",
      "Every cell must contain a numeric value",
      "Every cell holds a single atomic value",
    ],
    answer: 2,
    explain: "Relations don't require numeric-only cells — they require atomic (single) values, which can be of any data type.",
  },
  {
    q: "Why must a relation have no duplicate rows?",
    options: [
      "Because SQL cannot store duplicate data physically",
      "Because if two rows were fully identical there would be no way to reliably distinguish or refer to one over the other",
      "Because duplicate rows slow down queries",
      "Because primary keys are optional",
    ],
    answer: 1,
    explain: "Without uniqueness, there would be no reliable way to identify a specific row — which is exactly the problem keys are designed to solve.",
  },
  {
    q: "A table lists rows sorted by LastName in one query and by EmployeeNumber in another. Does this change which relation it represents?",
    options: [
      "Yes, they are now two different relations",
      "No — row order is not part of a relation's definition; ORDER BY only affects display",
      "Only if the primary key changes",
      "Only in MySQL",
    ],
    answer: 1,
    explain: "A relation is a set of rows; row order carries no meaning. ORDER BY is a display/query concern, not a structural one.",
  },
  {
    q: "A column stores 'SQL, Excel, Salesforce' as a single value for one employee. Which relational rule does this violate?",
    options: [
      "No duplicate rows",
      "Row order doesn't matter",
      "Atomic (single) value per cell",
      "Column order doesn't matter",
    ],
    answer: 2,
    explain: "Packing multiple values into one cell violates the atomicity rule — each cell must hold exactly one value.",
  },
  {
    q: "What is a key, in relational terms?",
    options: [
      "Any column that stores text",
      "One or more columns used to uniquely identify a row in a relation",
      "A column with a NULL default",
      "A column that only appears once in the schema",
    ],
    answer: 1,
    explain: "A key is one or more columns whose value(s) uniquely identify a specific row.",
  },
  {
    q: "What is a candidate key?",
    options: [
      "Any column that could uniquely identify each row, whether or not it was chosen as the primary key",
      "A key that has not yet been created",
      "Only a key made of two or more columns",
      "A foreign key that references itself",
    ],
    answer: 0,
    explain: "A candidate key is any column or column-set capable of uniquely identifying rows; the primary key is the one candidate key actually chosen.",
  },
  {
    q: "In the WP EMPLOYEE table, both EmployeeNumber and EmailAddress could each uniquely identify a row. If EmployeeNumber is chosen as the primary key, what is EmailAddress called?",
    options: ["A surrogate key", "An alternate key", "A composite key", "A transitive key"],
    answer: 1,
    explain: "A candidate key that exists but was not chosen as the primary key is called an alternate key.",
  },
  {
    q: "What is a composite key?",
    options: [
      "A key that changes value over time",
      "A key made of two or more columns together, where no single column alone is unique",
      "A key generated automatically by the DBMS",
      "A foreign key with a default value",
    ],
    answer: 1,
    explain: "A composite key requires the combination of two or more columns to guarantee uniqueness; the WP ASSIGNMENT table's (ProjectID, EmployeeNumber) is a classic example.",
  },
  {
    q: "In the WP ASSIGNMENT table (ProjectID, EmployeeNumber, HoursWorked), why is neither ProjectID nor EmployeeNumber alone a valid primary key?",
    options: [
      "Because HoursWorked is always NULL",
      "Because one project has many employees, and one employee works on many projects — only the pair is unique",
      "Because ASSIGNMENT has no primary key at all",
      "Because ProjectID is a foreign key and cannot be part of any key",
    ],
    answer: 1,
    explain: "Neither column alone is unique in ASSIGNMENT; only the combination (ProjectID, EmployeeNumber) uniquely identifies a row, making it a composite key.",
  },
  {
    q: "What is a surrogate key?",
    options: [
      "A real-world identifier like an email address or SSN used as a key",
      "An artificial, DBMS-generated identifier (often a plain integer) added purely to serve as the primary key",
      "A key that references another table",
      "A key that can hold duplicate values",
    ],
    answer: 1,
    explain: "A surrogate key is an artificial identifier with no business meaning, added specifically to serve as a stable primary key.",
  },
  {
    q: "What is a natural key?",
    options: [
      "A key made only of numbers",
      "A candidate key composed of data that has inherent real-world meaning, such as an email address or department name",
      "A key that is never unique",
      "A key added automatically by PostgreSQL",
    ],
    answer: 1,
    explain: "A natural key uses real business data (rather than an artificial identifier) as the unique identifier for a row.",
  },
  {
    q: "Why is DepartmentName a risky primary key choice for WP's DEPARTMENT table?",
    options: [
      "Text columns cannot be primary keys in SQL",
      "If the department is ever renamed, every referencing foreign key value elsewhere must also be updated to match",
      "DepartmentName is always NULL",
      "PostgreSQL forbids VARCHAR primary keys",
    ],
    answer: 1,
    explain: "A natural key that can change value (like a name) risks costly, error-prone cascading updates across every table that references it. A surrogate DepartmentID avoids this.",
  },
  {
    q: "What are the qualities of an ideal surrogate key?",
    options: ["Long, alphabetic, and frequently changing", "Short, numeric, and never changes", "Always a composite of 3+ columns", "Human-readable and meaningful"],
    answer: 1,
    explain: "A good surrogate key is short, numeric, and stable — it never changes once assigned to a row.",
  },
  {
    q: "What is a foreign key?",
    options: [
      "A primary key of one relation placed as a column in another relation, to represent a relationship",
      "A key that always has a NULL value",
      "A column that stores foreign currency amounts",
      "A duplicate copy of the primary key within the same table",
    ],
    answer: 0,
    explain: "A foreign key is a column (or columns) in one table holding the primary key value of a row in another (or the same) table, representing a relationship.",
  },
  {
    q: "In the WP schema, EMPLOYEE.Department is a foreign key referencing which table's primary key?",
    options: ["PROJECT", "ASSIGNMENT", "DEPARTMENT", "EMPLOYEE itself"],
    answer: 2,
    explain: "EMPLOYEE.Department is a foreign key referencing DEPARTMENT's primary key, linking each employee to their department.",
  },
  {
    q: "What does a self-referencing foreign key, like EMPLOYEE.Supervisor referencing EMPLOYEE.EmployeeNumber, typically represent?",
    options: [
      "A data entry error",
      "A hierarchical relationship, such as an org chart where each employee's supervisor is also an employee",
      "A many-to-many relationship requiring a linking table",
      "An invalid schema that PostgreSQL will reject",
    ],
    answer: 1,
    explain: "A self-referencing foreign key is a common way to model hierarchies (like org charts) within a single table.",
  },
  {
    q: "In PostgreSQL, which clause enforces that a column's value must exist as a primary key value in another table?",
    options: ["CHECK", "REFERENCES", "DEFAULT", "UNIQUE"],
    answer: 1,
    explain: "REFERENCES table(column) declares a foreign key constraint, enforcing referential integrity.",
  },
  {
    q: "Which auto-increment syntax matches SQL Server?",
    options: ["SERIAL", "AUTO_INCREMENT", "IDENTITY(1,1)", "GENERATED ALWAYS AS IDENTITY (Oracle style)"],
    answer: 2,
    explain: "SQL Server uses IDENTITY(1,1) for auto-incrementing columns; PostgreSQL uses SERIAL, MySQL uses AUTO_INCREMENT.",
  },
  {
    q: "A functional dependency X → Y means...",
    options: [
      "X and Y are always equal",
      "Knowing the value of X tells you, with certainty, the value of Y",
      "Y must be a foreign key",
      "X is always the primary key",
    ],
    answer: 1,
    explain: "X → Y ('X determines Y') means every value of X corresponds to exactly one value of Y.",
  },
  {
    q: "In a functional dependency X → Y, what is X called?",
    options: ["The dependent", "The determinant", "The surrogate", "The domain"],
    answer: 1,
    explain: "X, the column(s) on the left of the arrow, is called the determinant.",
  },
  {
    q: "Why does the primary key of a relation always functionally determine every other attribute?",
    options: [
      "Because primary keys are always numeric",
      "Because the primary key uniquely identifies each row, so it pins down every other column's value for that row",
      "This is not actually true in general",
      "Because SQL enforces this automatically at the storage level",
    ],
    answer: 1,
    explain: "Since a primary key uniquely identifies a row, knowing its value tells you exactly which row you're looking at — and therefore every other attribute's value in that row.",
  },
  {
    q: "What is a partial dependency?",
    options: [
      "A dependency between two non-key columns",
      "A non-key column that depends on only part of a composite primary key, rather than the whole key",
      "A foreign key that is sometimes NULL",
      "A dependency that only holds true half the time",
    ],
    answer: 1,
    explain: "A partial dependency occurs when a non-key attribute depends on just part of a composite key rather than needing the entire key.",
  },
  {
    q: "ASSIGNMENT's key is (ProjectID, EmployeeNumber). A column EmployeeDepartment is added, and it only depends on EmployeeNumber. What is this called?",
    options: ["A full functional dependency", "A partial dependency", "A candidate key", "A surrogate key"],
    answer: 1,
    explain: "EmployeeDepartment depends on only part of the composite key (EmployeeNumber), making this a partial dependency — and a design smell.",
  },
  {
    q: "What is a transitive dependency?",
    options: [
      "A dependency where a non-key column depends on another non-key column, rather than directly on the key",
      "A dependency that changes over time",
      "A dependency involving three or more tables",
      "Any dependency involving a foreign key",
    ],
    answer: 0,
    explain: "A transitive dependency exists when a non-key column's value depends on another non-key column, which in turn depends on the key — 'key → non-key → non-key'.",
  },
  {
    q: "EMPLOYEE stores Department and DepartmentPhone, where DepartmentPhone depends on Department, not directly on EmployeeNumber. What kind of dependency is EmployeeNumber → DepartmentPhone?",
    options: ["A full functional dependency", "A partial dependency", "A transitive dependency", "Not a dependency at all"],
    answer: 2,
    explain: "EmployeeNumber → DepartmentPhone only holds transitively, through Department (EmployeeNumber → Department → DepartmentPhone) — a transitive dependency.",
  },
  {
    q: "What kind of dependency is HoursWorked on in ASSIGNMENT (ProjectID, EmployeeNumber, HoursWorked)?",
    options: [
      "A partial dependency on EmployeeNumber only",
      "A full functional dependency on the entire composite key (ProjectID, EmployeeNumber)",
      "A transitive dependency through ProjectID",
      "No dependency — HoursWorked is independent",
    ],
    answer: 1,
    explain: "HoursWorked genuinely requires both ProjectID and EmployeeNumber to be determined — it's specific to one employee working on one project — making it a full functional dependency.",
  },
  {
    q: "Why does this course introduce full, partial, and transitive dependencies before teaching normal forms?",
    options: [
      "Normal forms are unrelated to functional dependencies",
      "Because normalization (taught in Module 05) is built directly on this dependency vocabulary — it's the groundwork needed first",
      "Because PostgreSQL requires dependencies to be declared before tables are created",
      "Because normal forms were deprecated in modern SQL",
    ],
    answer: 1,
    explain: "Functional dependency vocabulary (full, partial, transitive) is the foundation the normalization process in Module 05 is built on.",
  },
];
